// security.ts
//
// Circle AI security layer — portable schema only.
//
// Covers:
//   ThreatVector   — stable enum of detectable attack/anomaly vectors
//   AnomalySignal  — immutable record describing a single detected anomaly
//
// The actual watchdog implementation (response policy, quarantine, host
// integration) stays C# host-side. This module ports just the data types
// that detection sites in any language need to emit, so the signals are
// interchangeable across the polyglot SDK.
//
// CRITICAL: ThreatVector ordinals (0..7) are part of the wire/storage contract.
// They MUST stay in this exact declaration order so ordinals match the C#
// reference implementation and all other-language ports.

import { randomUUID } from 'node:crypto';

// ---------------------------------------------------------------------------
// ThreatVector
// ---------------------------------------------------------------------------

/**
 * Classification of a locally-detected runtime threat or anomaly.
 *
 * Distinct from any peer-security event kind (which classifies external peer
 * events); ThreatVector classifies threats observed in the LOCAL execution
 * environment.
 *
 * Ordinals are stable across language ports — new values must be appended
 * to preserve serialised compatibility.
 */
export enum ThreatVector {
  /**
   * Unexpected change in a runtime data structure's layout or content —
   * possible memory injection or buffer corruption.
   */
  MemoryAnomaly = 0,

  /**
   * Execution flow deviated from the expected call graph —
   * possible ROP/JOP chain or code-reuse attack.
   */
  ControlFlowDrift = 1,

  /**
   * A module or user session attempted to acquire capabilities
   * it is not authorised to hold.
   */
  PrivilegeEscalation = 2,

  /**
   * A biometric authentication attempt was detected as a spoofing or
   * replay attack against the `UHID` profile.
   */
  BiometricSpoofAttempt = 3,

  /**
   * An attacker appears to be attempting lateral movement from a
   * compromised mesh node into the local execution namespace.
   */
  NetworkPivot = 4,

  /**
   * The AffectState or another core state vector was mutated by an
   * unexpected code path outside the trusted companion pipeline.
   */
  StateCorruption = 5,

  /**
   * A software patch generated by an agent loop failed the BugHunter
   * quality gate — possible malicious or incorrect code generation.
   */
  AgentPatchRejected = 6,

  /** Catch-all for anomalies that do not map to a specific vector. */
  Unknown = 7,
}

// ---------------------------------------------------------------------------
// AnomalySignal
// ---------------------------------------------------------------------------

/**
 * An immutable record describing a locally-detected runtime anomaly.
 * Created at the detection site (e.g. the companion pipeline, the biometric
 * verifier, or an agent patch gate) and consumed by the host-side security
 * watchdog.
 */
export interface AnomalySignal {
  /** Stable identifier for this signal instance (UUID v4). */
  readonly id: string;

  /** Classification of the detected threat. */
  readonly vector: ThreatVector;

  /**
   * Confidence that this is a genuine threat, in [0.0, 1.0].
   * 1.0 = definitive; 0.0 = speculative.
   */
  readonly confidence: number;

  /**
   * The module or subsystem where the anomaly was detected
   * (e.g. `"Circle.AI.Companion"`, `"Circle.AI.Identity"`).
   */
  readonly affectedModule: string;

  /** Human-readable description of the anomaly. */
  readonly description: string;

  /**
   * Structured evidence attached by the detection site.
   * Keys are evidence labels; values are serialised data or hashes.
   */
  readonly evidence: Readonly<Record<string, string>>;

  /** UTC timestamp of detection. */
  readonly detectedAt: Date;
}

/**
 * Creates a new {@link AnomalySignal} with a fresh UUID v4 id and a
 * `detectedAt` stamp of the current UTC time. `confidence` is clamped
 * to `[0.0, 1.0]`. `evidence` is defensively copied; when omitted, an
 * empty object is used.
 */
export function createAnomalySignal(
  vector: ThreatVector,
  confidence: number,
  affectedModule: string,
  description: string,
  evidence?: Record<string, string>,
): AnomalySignal {
  return {
    id: randomUUID(),
    vector,
    confidence: Math.min(1, Math.max(0, confidence)),
    affectedModule,
    description,
    evidence: evidence ? { ...evidence } : {},
    detectedAt: new Date(),
  };
}
