"""Generate every static drawing of the CircleAI mark from ONE set of numbers.

THE MARK LIVES IN MarkView.cs. That class draws it live, in C#, on a Canvas, and
it is the only place the geometry is decided. Everything this script writes is a
projection of it:

    Resources/drawable/ic_launcher_foreground.xml   native Android head, launcher
    Resources/AppIcon/appiconfg.svg                 MAUI head, launcher foreground
    Resources/AppIcon/appicon.svg                   MAUI head, launcher plate
    Resources/Splash/splash.svg                     MAUI head, splash

WHY A GENERATOR AND NOT FOUR HAND-DRAWN FILES. There used to be two drawings and
they had already diverged: the launcher icon was a half circle open on the RIGHT
with three solid arcs, while the live mark is open at the TOP with three arcs
that fade 235/150/80. Nobody caught it because an icon and a home screen are
never on screen together. Four copies would have diverged four ways.

So: change MarkView.OnDraw, change the constants here to match, re-run. The test
suite asserts the shipped files are what this script produces, so a hand edit
fails the build instead of shipping a second logo.

    python tools/brand-mark/gen_mark.py

THE COLOURS ARE NOT INTERCHANGEABLE, and which goes where is a decision:

  splash    blue mark on #121A21, the colour Home's page actually measures. The
            splash exists to be the bridge INTO the app, so it wears the app's
            own background. A white default flashing into a dark app is the
            defect this replaces.
  launcher  white mark on #2196F3. Inverted, because a launcher icon sits on
            somebody else's wallpaper and needs the contrast Home gets from its
            dark page.
"""
import math
import pathlib
import sys

# -- the geometry, read off MarkView.OnDraw -----------------------------------
RING_R, RING_W = 0.46, 0.11          # radius and stroke, as fractions of r
ARC_W          = 0.085
ARC_SPREAD     = [0.16 + 0.16 * i for i in range(3)]
IDLE_ALPHA     = [235, 150, 80]      # the Idle branch of _arc.Alpha
RING_START, RING_SWEEP = -50.0, 280.0
ARC_START,  ARC_SWEEP  = -34.0, 68.0

BLUE  = "#2196F3"
WHITE = "#ffffff"
PAGE  = "#121A21"                    # Ui.Bg = Shade(Slate, 0.42f), measured on device

REPO = pathlib.Path(__file__).resolve().parent.parent.parent


def arc_path(cx, cy, R, start, sweep):
    """One arc as an SVG/vector-drawable `A` command.

    y grows DOWNWARD in both an SVG viewport and an Android canvas, so a positive
    sweep is clockwise in each and the sweep-flag is 1 with no sign flip. Getting
    that wrong does not fail a build. It silently mirrors the mark.
    """
    def pt(deg):
        a = math.radians(deg)
        return cx + R * math.cos(a), cy + R * math.sin(a)

    x0, y0 = pt(start)
    x1, y1 = pt(start + sweep)
    large = 1 if sweep > 180 else 0
    return f"M {x0:.2f} {y0:.2f} A {R:.2f} {R:.2f} 0 {large} 1 {x1:.2f} {y1:.2f}"


def strokes(canvas, r):
    """(pathData, opacity, strokeWidth) for the ring, then the three arcs."""
    c = canvas / 2
    out = [(arc_path(c, c, RING_R * r, RING_START, RING_SWEEP), 1.0, RING_W * r)]
    for spread, alpha in zip(ARC_SPREAD, IDLE_ALPHA):
        out.append((arc_path(c, c, (RING_R + spread) * r, ARC_START, ARC_SWEEP),
                    alpha / 255.0, ARC_W * r))
    return out


def fit(canvas, safe_fraction):
    """The r that puts the outermost stroke EDGE exactly on the safe radius.

    The outermost thing drawn is the third arc plus half its own stroke. Sizing
    off the arc centre-line instead leaves half a stroke outside the safe zone,
    which a launcher mask crops, and the crop only shows on the phones using that
    mask shape.
    """
    return (canvas / 2 * safe_fraction) / (RING_R + ARC_SPREAD[-1] + ARC_W / 2)


# -- Android vector drawable (native head) -----------------------------------
def android_vector():
    canvas = 108.0
    r = fit(canvas, 72.0 / 108.0)      # 72dp safe zone in a 108dp canvas
    body = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!--',
        '    GENERATED by tools/brand-mark/gen_mark.py from MarkView.OnDraw.',
        '    Do not hand-edit: BrandMarkAssetTests fails when this drifts from the',
        '    generator, which is how the previous hand-drawn icon became a different',
        '    logo - a half circle open on the wrong side with three solid arcs.',
        '',
        '    App icon foreground: white mark over the @color/ic_launcher_background',
        '    plate, inside the 72dp safe zone. Anything outside that can be cropped',
        '    away by the launcher mask.',
        '',
        '    No halo: it is a 28-alpha fill and the plate behind it is opaque, so it',
        '    would draw nothing.',
        '-->',
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="108dp"',
        '    android:height="108dp"',
        '    android:viewportWidth="108"',
        '    android:viewportHeight="108">',
        '',
    ]
    names = ["the ring, open at the top",
             "arc 1 of 3 - nearest, brightest",
             "arc 2 of 3",
             "arc 3 of 3 - outermost, quietest"]
    for (d, op, w), label in zip(strokes(canvas, r), names):
        body.append(f'    <!-- {label} -->')
        body.append('    <path')
        body.append(f'        android:strokeColor="{WHITE}"')
        if op < 1.0:
            # strokeAlpha is API 24+, and SupportedOSPlatformVersion is 24, so it
            # holds at the floor rather than only on newer phones.
            body.append(f'        android:strokeAlpha="{op:.3f}"')
        body.append(f'        android:strokeWidth="{w:.2f}"')
        body.append('        android:strokeLineCap="round"')
        body.append('        android:fillColor="#00000000"')
        body.append(f'        android:pathData="{d}" />')
        body.append('')
    body.append('</vector>')
    return "\n".join(body) + "\n"


# -- SVG (MAUI head) ---------------------------------------------------------
def svg(canvas, safe_fraction, colour, background, note):
    r = fit(canvas, safe_fraction)
    out = ['<?xml version="1.0" encoding="UTF-8" standalone="no"?>',
           f'<!-- GENERATED by tools/brand-mark/gen_mark.py from MarkView.OnDraw. {note} -->',
           f'<svg width="{canvas:.0f}" height="{canvas:.0f}" '
           f'viewBox="0 0 {canvas:.0f} {canvas:.0f}" version="1.1" '
           'xmlns="http://www.w3.org/2000/svg">']
    if background:
        out.append(f'    <rect x="0" y="0" width="{canvas:.0f}" height="{canvas:.0f}" '
                   f'fill="{background}" />')
    for d, op, w in strokes(canvas, r):
        out.append(f'    <path d="{d}" fill="none" stroke="{colour}" '
                   f'stroke-opacity="{op:.3f}" stroke-width="{w:.2f}" '
                   'stroke-linecap="round" />')
    out.append('</svg>')
    return "\n".join(out) + "\n"


def outputs():
    """Every file this script owns, as {path: content}."""
    hyb = REPO / "samples" / "CircleAI.Samples.It.Hybrid" / "CircleAI.Samples.It.App"
    return {
        REPO / "samples" / "CircleAI.Samples.It.Android" / "Resources" / "drawable"
             / "ic_launcher_foreground.xml": android_vector(),

        # MauiIcon: appicon.svg is the plate, appiconfg.svg the mark laid over it.
        # MAUI generates every density from these two, which is why this head
        # needs no mipmap folders at all.
        hyb / "Resources" / "AppIcon" / "appicon.svg":
            svg(456, 1.0, BLUE, BLUE, "Launcher plate - flat brand blue."),
        hyb / "Resources" / "AppIcon" / "appiconfg.svg":
            # 66% keeps the mark inside the adaptive-icon safe zone once MAUI has
            # placed the foreground over the plate.
            svg(456, 0.66, WHITE, None, "Launcher foreground - white mark, transparent."),

        # MauiSplashScreen: the svg carries the mark, the csproj Color= carries the
        # background. Both are stated, so the file also reads correctly on its own.
        # 0.95, not 0.52. A splash has no launcher mask to survive and no
        # foreground to sit inside - it is one mark on a full-bleed colour - so
        # the safe zone the icons need was costing it half its size for nothing.
        # At 0.52 on a 128dp BaseSize the mark drew at about 66dp: a small logo
        # adrift in the middle of a dark screen. The 5% left over is optical
        # margin, so the arcs do not touch the edge of the image itself.
        hyb / "Resources" / "Splash" / "splash.svg":
            svg(456, 0.95, BLUE, PAGE,
                "Splash - blue mark on the app's own page colour, so there is no "
                "white flash and no colour jump into Home. Near full-bleed: "
                "nothing crops a splash, so nothing needs a safe zone."),
    }


def main():
    check = "--check" in sys.argv
    stale = []
    for path, text in outputs().items():
        if check:
            actual = path.read_text(encoding="utf-8") if path.exists() else None
            if actual != text:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"  {path.relative_to(REPO)}  {len(text)} bytes")

    if check:
        for p in stale:
            print(f"  STALE {p.relative_to(REPO)}")
        print("all generated assets are current" if not stale
              else f"{len(stale)} file(s) differ from the generator")
        return 1 if stale else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
