// SampleLanguages.cs
//
// The languages the sample offers, and what to say in each.
//
// THIS TABLE IS SHARED BECAUSE IT IS CHECKED BY HAND. Every endonym and every
// greeting was verified by somebody, and where a greeting could not be
// confirmed the entry is left null so the screen names the language in its own
// words instead of inventing a sentence. A demo that mispronounces a made-up
// phrase at a native speaker is worse than one that says less.
//
// It lived inside the native Android picker until the hybrid heads arrived.
// Copying it would have created a second table to keep right, and a language
// missing from one copy is INVISIBLE to whoever is choosing, however correct
// the model registry is - that already happened to Korean, whose row read the
// literal string "ko" because the catalogue had it and this table did not.
//
// Generated by tools, from the picker, once. Edit here now.

using System.Collections.Generic;

namespace CircleAI.Samples.It;

/// <summary>One language the sample can speak.</summary>
/// <param name="Tag">BCP-47 tag, as the model registry spells it.</param>
/// <param name="Name">English name, for someone who does not read the script.</param>
/// <param name="Native">What speakers call it, in their own script.</param>
/// <param name="Greeting">A checked sentence to speak, or null when none was confirmed.</param>
public sealed record SampleLanguage(string Tag, string Name, string Native, string? Greeting);

/// <summary>The catalogue of offered languages, in tag order.</summary>
public static class SampleLanguages
{
    /// <summary>Every language the sample lists, keyed by registry tag.</summary>
    public static IReadOnlyDictionary<string, SampleLanguage> All { get; } =
        new Dictionary<string, SampleLanguage>
        {
            ["af"] = new("af", "Afrikaans", "Afrikaans", "Hallo wêreld. Hoe gaan dit met jou?"),
            ["ak"] = new("ak", "Akan", "Twi", "Akwaaba. Wo ho te sɛn?"),
            ["am"] = new("am", "Amharic", "አማርኛ", "ሰላም ለዓለም። እንዴት ናችሁ?"),
            ["ar"] = new("ar", "Arabic", "العربية", "مرحبا بالعالم. كيف حالك؟"),
            ["bem"] = new("bem", "Bemba", "Ichibemba", "Muli shani? Ndi bwino."),
            ["bm"] = new("bm", "Bambara", "Bamanankan", "I ni ce. I ka kɛnɛ wa?"),
            ["bn"] = new("bn", "Bengali", "বাংলা", "হ্যালো বিশ্ব। আপনি কেমন আছেন?"),
            ["ee"] = new("ee", "Ewe", "Eʋegbe", "Ŋdi na wò. Èfɔa nyuie a?"),
            ["en"] = new("en", "English", "English", "Hello world. How are you today?"),
            ["es-ES"] = new("es-ES", "Spanish (Spain)", "Español (España)", "Hola mundo. ¿Cómo estás hoy?"),
            ["es-MX"] = new("es-MX", "Spanish (Mexico)", "Español (México)", "Hola mundo. ¿Cómo estás hoy?"),
            ["fa"] = new("fa", "Persian", "فارسی", "سلام دنیا. حال شما چطور است؟"),
            ["ff"] = new("ff", "Fula", "Fulfulde", "Jam waali. No mbaɗɗaa?"),
            ["fon"] = new("fon", "Fon", "Fɔngbè", "Kúdó. A fɔ́n gánjí à?"),
            ["fr"] = new("fr", "French", "Français", "Bonjour le monde. Comment allez-vous ?"),
            ["gn"] = new("gn", "Guarani", "Avañe'ẽ", "Mba'éichapa. Iporãnte."),
            ["gu"] = new("gu", "Gujarati", "ગુજરાતી", "નમસ્તે વિશ્વ. તમે કેમ છો?"),
            ["ha"] = new("ha", "Hausa", "Harshen Hausa", "Sannu duniya. Yaya kake?"),
            ["hi"] = new("hi", "Hindi", "हिन्दी", "नमस्ते दुनिया। आप कैसे हैं?"),
            ["ht"] = new("ht", "Haitian Creole", "Kreyòl", "Bonjou monn. Kijan ou ye?"),
            ["id"] = new("id", "Indonesian", "Bahasa Indonesia", "Halo dunia. Apa kabar?"),
            ["ig"] = new("ig", "Igbo", "Asụsụ Igbo", "Ndewo ụwa. Kedu ka ị mere?"),
            ["ja"] = new("ja", "Japanese", "日本語", "こんにちは世界。お元気ですか。"),
            ["jv"] = new("jv", "Javanese", "Basa Jawa", "Sugeng enjing. Piye kabare?"),
            ["ki"] = new("ki", "Kikuyu", "Gĩkũyũ", "Ũhoro waku? Nĩ mwega."),
            ["kn"] = new("kn", "Kannada", "ಕನ್ನಡ", "ನಮಸ್ಕಾರ ಜಗತ್ತು. ಹೇಗಿದ್ದೀರಿ?"),
            ["kr"] = new("kr", "Kanuri", "Kanuri", "Ndaram. Awo cira?"),
            ["ko"] = new("ko", "Korean", "한국어", "안녕하세요 세계. 어떻게 지내세요?"),
            ["lg"] = new("lg", "Luganda", "Luganda", "Oli otya? Ndi bulungi."),
            ["lgg"] = new("lgg", "Lugbara", "Lugbarati", "Mi ngoni? Ma muke."),
            ["ln"] = new("ln", "Lingala", "Lingála", "Mbote na yo. Ozali malamu?"),
            ["mg"] = new("mg", "Malagasy", "Malagasy", "Manao ahoana. Salama tsara."),
            ["ml"] = new("ml", "Malayalam", "മലയാളം", "നമസ്കാരം ലോകം. സുഖമാണോ?"),
            ["mos"] = new("mos", "Mossi", "Mooré", "Ne y windga. Y kibare?"),
            ["mr"] = new("mr", "Marathi", "मराठी", "नमस्कार जग. तुम्ही कसे आहात?"),
            ["my"] = new("my", "Burmese", "မြန်မာ", "မင်္ဂလာပါ ကမ္ဘာ။ နေကောင်းလား။"),
            ["ne"] = new("ne", "Nepali", "नेपाली", "नमस्ते संसार। तपाईं कस्तो हुनुहुन्छ?"),
            ["nl-NL"] = new("nl-NL", "Dutch", "Nederlands", "Hallo wereld. Hoe gaat het met je?"),
            ["nl-BE"] = new("nl-BE", "Flemish", "Vlaams", "Hallo wereld. Hoe gaat het met je?"),
            ["nr"] = new("nr", "isiNdebele", "isiNdebele", "Lotjhani phasi. Unjani namhlanje?"),
            ["nso"] = new("nso", "Sepedi", "Sepedi", "Dumela lefase. O kae lehono?"),
            ["ny"] = new("ny", "Chichewa", "Chichewa", "Moni. Muli bwanji?"),
            ["nyn"] = new("nyn", "Nyankole", "Runyankole", "Agandi? Nimarungi."),
            ["om"] = new("om", "Oromo", "Afaan Oromoo", "Akkam jirta? Nagaa dha."),
            ["pa"] = new("pa", "Punjabi", "ਪੰਜਾਬੀ", "ਸਤ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨੀਆ। ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ?"),
            ["pt-BR"] = new("pt-BR", "Portuguese (Brazil)", "Português (Brasil)", "Olá mundo. Como você está hoje?"),
            ["pt-PT"] = new("pt-PT", "Portuguese (Portugal)", "Português (Portugal)", "Olá mundo. Como está hoje?"),
            ["qu"] = new("qu", "Quechua", "Runa Simi", "Allillanchu? Allinmi kani."),
            ["rn"] = new("rn", "Kirundi", "Ikirundi", "Amakuru? Ni meza."),
            ["ru"] = new("ru", "Russian", "Русский", "Привет мир. Как дела сегодня?"),
            ["rw"] = new("rw", "Kinyarwanda", "Ikinyarwanda", "Amakuru? Ni meza."),
            ["sg"] = new("sg", "Sango", "Sängö", "Bara ala. Tongana nyen?"),
            ["si"] = new("si", "Sinhala", "සිංහල", "ආයුබෝවන් ලෝකය. කොහොමද?"),
            ["sn"] = new("sn", "Shona", "chiShona", "Mhoro nyika. Wakadii nhasi?"),
            ["so"] = new("so", "Somali", "Soomaali", "Salaan aduunka. Sidee tahay?"),
            ["ss"] = new("ss", "siSwati", "siSwati", "Sawubona live. Unjani lamuhla?"),
            ["st"] = new("st", "Sesotho", "Sesotho", "Dumela lefatshe. O phela joang?"),
            ["su"] = new("su", "Sundanese", "Basa Sunda", "Wilujeng énjing. Kumaha damang?"),
            ["sw"] = new("sw", "Swahili", "Kiswahili", "Habari dunia. Hujambo leo?"),
            ["ta"] = new("ta", "Tamil", "தமிழ்", "வணக்கம் உலகம். எப்படி இருக்கிறீர்கள்?"),
            ["te"] = new("te", "Telugu", "తెలుగు", "నమస్కారం ప్రపంచం. ఎలా ఉన్నారు?"),
            ["th"] = new("th", "Thai", "ไทย", "สวัสดีชาวโลก สบายดีไหม"),
            ["ti"] = new("ti", "Tigrinya", "ትግርኛ", "ሰላም ዓለም። ከመይ ኣለኻ?"),
            ["tl"] = new("tl", "Filipino", "Tagalog", "Kumusta mundo. Kumusta ka ngayon?"),
            ["tn"] = new("tn", "Setswana", "Setswana", "Dumela lefatshe. O tsogile jang?"),
            ["tpi"] = new("tpi", "Tok Pisin", "Tok Pisin", "Gude world. Yu orait?"),
            ["ts"] = new("ts", "Xitsonga", "Xitsonga", "Avuxeni misava. U njhani namuntlha?"),
            ["ur"] = new("ur", "Urdu", "اردو", "ہیلو دنیا۔ آپ کیسے ہیں؟"),
            ["ve"] = new("ve", "Tshivenda", "Tshivenḓa", "Ndaa shango. Vho vuwa hani?"),
            ["vi"] = new("vi", "Vietnamese", "Tiếng Việt", "Xin chào thế giới. Bạn khỏe không?"),
            ["xh"] = new("xh", "isiXhosa", "isiXhosa", "Molo mhlaba. Unjani namhlanje?"),
            ["yo"] = new("yo", "Yoruba", "Yorùbá", "Pẹlẹ o ayé. Bawo ni o ṣe wà?"),
            ["yue"] = new("yue", "Cantonese", "粵語", "你好世界。你今日好嗎？"),
            ["zh"] = new("zh", "Mandarin", "中文", "你好世界。你今天好吗？"),
            ["zu"] = new("zu", "isiZulu", "isiZulu", "Sawubona mhlaba. Unjani namuhla?"),
        };

    /// <summary>
    /// The language, or null when this tag is not offered.
    /// </summary>
    /// <remarks>
    /// Null rather than a fabricated row. A caller that invents
    /// <c>(tag, tag, null)</c> for a missing entry produces a screen that names a
    /// language "ko" and offers to speak the word "ko" aloud.
    /// </remarks>
    public static SampleLanguage? Find(string? tag)
        => tag is not null && All.TryGetValue(tag, out var l) ? l : null;
}
