// sync-registry
//
// Generates Models/embedded_registry.json (runtime, array form) FROM
// registry.json (keyed form), so the two can no longer drift by hand.
//
//   dotnet run --project tools/sync-registry            # write
//   dotnet run --project tools/sync-registry -- --check # verify only, exit 1 on drift
//
// Why: the SHAs/sizes live in registry.json (produced by recalibrate-registry-sha
// for ModelScope, hf-hash for Hugging Face) and a HUMAN retyped them into the
// embedded file. RegistryDriftTests catches divergence after the fact; this
// removes the opportunity. Runtime-only fields on the embedded side
// (QualityRank, MinRamGb, MinStorageGb, Capabilities, FallbackModelId,
// MemoryHintBytes, MinVramGb) are PRESERVED from the existing embedded entry —
// they are hand-tuned and must not be clobbered by a regeneration.

using System.Text.Json;
using System.Text.Json.Nodes;

var root = FindRepoRoot() ?? throw new InvalidOperationException("repo root (capabilities.json) not found");
var keyedPath = Path.Combine(root, "src", "CircleAI.Core", "registry.json");
var embeddedPath = Path.Combine(root, "src", "CircleAI.Core", "Models", "embedded_registry.json");
var checkOnly = args.Contains("--check");

var keyed = JsonNode.Parse(File.ReadAllText(keyedPath))!.AsObject();
var embedded = JsonNode.Parse(File.ReadAllText(embeddedPath))!.AsObject();

// Index the existing embedded entries so hand-tuned runtime fields survive.
var existing = new Dictionary<string, JsonObject>(StringComparer.OrdinalIgnoreCase);
if (embedded["Models"] is JsonArray oldModels)
    foreach (var m in oldModels)
        if (m is JsonObject o && o["Name"]?.GetValue<string>() is { } n)
            existing[n] = o;

// Fields that belong to the RUNTIME file only — never sourced from keyed.
string[] runtimeOnly =
[
    "QualityRank", "MinRamGb", "MinStorageGb", "Capabilities",
    "FallbackModelId", "MemoryHintBytes", "MinVramGb",
];

var models = new JsonArray();
var names = new List<string>();

foreach (var (name, node) in keyed)
{
    if (node is not JsonObject src) continue;              // skips "Notes"
    if (src["BundleFiles"] is null && src["Url"] is null) continue;

    names.Add(name);
    var dst = new JsonObject { ["Name"] = name };

    // Facts come from the keyed file — the tool-produced source of truth.
    Copy(src, dst, "Version");
    dst["Quantization"] = src["QuantizationType"]?.DeepClone() ?? src["Quantization"]?.DeepClone();
    Copy(src, dst, "Repo");
    Copy(src, dst, "Source");
    Copy(src, dst, "Modality");
    Copy(src, dst, "Architecture");
    Copy(src, dst, "TotalBytes");
    Copy(src, dst, "Url");
    Copy(src, dst, "Checksum");

    // Runtime-only fields: preserve whatever the embedded file already had.
    if (existing.TryGetValue(name, out var prev))
        foreach (var f in runtimeOnly)
            if (prev[f] is { } v) dst[f] = v.DeepClone();

    // BundleFiles verbatim — these are the pinned hashes.
    if (src["BundleFiles"] is JsonArray bf) dst["BundleFiles"] = bf.DeepClone();

    models.Add(dst);
}

var result = new JsonObject
{
    ["RegistryUrl"] = embedded["RegistryUrl"]?.DeepClone(),
    ["LastUpdated"] = embedded["LastUpdated"]?.DeepClone(),
    ["Notes"] = "GENERATED by tools/sync-registry from ../registry.json. Do not hand-edit the "
              + "facts (Repo/Source/Modality/TotalBytes/BundleFiles) — edit registry.json and "
              + "re-run. Runtime-only fields (QualityRank, MinRamGb, MinStorageGb, Capabilities, "
              + "FallbackModelId, MemoryHintBytes, MinVramGb) ARE hand-tuned here and are preserved.",
    ["Models"] = models,
};

var opts = new JsonSerializerOptions { WriteIndented = true };
var rendered = result.ToJsonString(opts);

if (checkOnly)
{
    var current = JsonNode.Parse(File.ReadAllText(embeddedPath))!.ToJsonString(opts);
    if (current == rendered) { Console.WriteLine($"in sync ({models.Count} models)"); return 0; }
    Console.Error.WriteLine("DRIFT: embedded_registry.json differs from what registry.json generates.");
    Console.Error.WriteLine("Run: dotnet run --project tools/sync-registry");
    return 1;
}

File.WriteAllText(embeddedPath, rendered);
Console.WriteLine($"wrote {models.Count} models -> {embeddedPath}");
foreach (var n in names) Console.WriteLine("  " + n);
return 0;

static void Copy(JsonObject src, JsonObject dst, string field)
{
    if (src[field] is { } v) dst[field] = v.DeepClone();
}

static string? FindRepoRoot()
{
    var d = new DirectoryInfo(AppContext.BaseDirectory);
    while (d is not null && !File.Exists(Path.Combine(d.FullName, "capabilities.json"))) d = d.Parent;
    return d?.FullName;
}
