"""The constant ubiquity rails — the decisions that turn the substrate into
something reachable where people actually are.

GENERATED by python/tools/gen_rails.py. Do not edit by hand; edit the table.

ubiquity.py alongside this holds the rails that HOLD STATE: the app-store
submitter, the signed delta updater, the abuse-safe mode and its safety phrase.
This file is the other half — the ones whose whole content is a decision.

Which stores and package managers it ships through, which connectors exist,
what the regulators have and have not approved, what happens when the network
or the disk runs out, what a user costs, and what the product will not do to a
child or to somebody in a dangerous house.

WHY THESE ARE CONSTANTS AND NOT CONFIGURATION. Every one of them is a DECISION
somebody made and has to be able to defend. A regulator approval that could be
flipped by a config file is not an approval; a cost ceiling that a deployment
can raise is not a ceiling. They live in the code so that changing one is a
commit with a name on it.

Money is in MINOR UNITS as integers throughout.
"""

from __future__ import annotations

from abc import ABC, abstractmethod

class IOemPreloadCatalog(ABC):
    """OEMs with a preload agreement. Mid-tier and below, because that is what
    people here actually buy."""

    @property
    @abstractmethod
    def partners(self): ...

class DefaultOemPreloadCatalog(IOemPreloadCatalog):
    """The decision as it stands."""

    @property
    def partners(self):
        return ['Tecno', 'Itel', 'Samsung mid-tier', 'Xiaomi', 'Huawei']

class ICarrierPreloadCatalog(ABC):
    """Carriers with a preload agreement."""

    @property
    @abstractmethod
    def carriers(self): ...

class DefaultCarrierPreloadCatalog(ICarrierPreloadCatalog):
    """The decision as it stands."""

    @property
    def carriers(self):
        return ['MTN', 'Vodacom', 'Cell C', 'Telkom', 'Safaricom', 'Airtel']

class IPwaFallback(ABC):
    """Where a device with no installable package goes instead."""

    @property
    @abstractmethod
    def pwa_url(self): ...

class DefaultPwaFallback(IPwaFallback):
    """The decision as it stands."""

    @property
    def pwa_url(self):
        return 'https://app.circle.ai'

class ISideloadChannel(ABC):
    """Formats somebody can be handed directly, without a store."""

    @property
    @abstractmethod
    def formats(self): ...

class DefaultSideloadChannel(ISideloadChannel):
    """The decision as it stands."""

    @property
    def formats(self):
        return ['APK', 'IPA', 'MSIX']

class ILinuxRepoFanout(ABC):
    """Package managers the Linux build fans out to."""

    @property
    @abstractmethod
    def repos(self): ...

class DefaultLinuxRepoFanout(ILinuxRepoFanout):
    """The decision as it stands."""

    @property
    def repos(self):
        return ['apt', 'yum', 'pacman', 'brew', 'flatpak', 'snap']

class IThirdPartySecurityAuditPublisher(ABC):
    """Where the third-party audit is published. A claim nobody can check is a
    claim, not evidence."""

    @property
    @abstractmethod
    def report_url(self): ...

class DefaultThirdPartySecurityAuditPublisher(IThirdPartySecurityAuditPublisher):
    """The decision as it stands."""

    @property
    def report_url(self):
        return 'https://trust.circle.ai/audit'

class IComplianceCertifications(ABC):
    """Certifications held."""

    @property
    @abstractmethod
    def certifications(self): ...

class DefaultComplianceCertifications(IComplianceCertifications):
    """The decision as it stands."""

    @property
    def certifications(self):
        return ['SOC 2 Type II', 'ISO 27001', 'ISO 27701']

class IBugBountyChannel(ABC):
    """Where to report a vulnerability, and on what platform."""

    @property
    @abstractmethod
    def platform(self): ...

    @property
    @abstractmethod
    def submission_url(self): ...

class DefaultBugBountyChannel(IBugBountyChannel):
    """The decision as it stands."""

    @property
    def platform(self):
        return 'HackerOne'

    @property
    def submission_url(self):
        return 'https://h1.com/circleai'

class IPrivacyRegulationCompliance(ABC):
    """Privacy laws this is built to comply with. POPIA is second because it is
    the one that governs most of the people using it."""

    @property
    @abstractmethod
    def laws(self): ...

class DefaultPrivacyRegulationCompliance(IPrivacyRegulationCompliance):
    """The decision as it stands."""

    @property
    def laws(self):
        return ['GDPR', 'POPIA', 'CCPA', 'LGPD']

class IVerifiablePrivacyProof(ABC):
    """A reproducible build and a source URL: the two things that let somebody
    CHECK the privacy claim instead of believing it."""

    @property
    @abstractmethod
    def build_is_reproducible(self): ...

    @property
    @abstractmethod
    def source_url(self): ...

class DefaultVerifiablePrivacyProof(IVerifiablePrivacyProof):
    """The decision as it stands."""

    @property
    def build_is_reproducible(self):
        return True

    @property
    def source_url(self):
        return 'https://github.com/bhengubv/CircleAI'

class IPluginMarketplaceRevenueShare(ABC):
    """What a plugin author keeps. Verified-safe plugins take a smaller share
    because verification costs something and somebody has to pay for it."""

    @property
    @abstractmethod
    def author_share(self): ...

    @property
    @abstractmethod
    def verified_safe_share(self): ...

class DefaultPluginMarketplaceRevenueShare(IPluginMarketplaceRevenueShare):
    """The decision as it stands."""

    @property
    def author_share(self):
        return 0.7

    @property
    def verified_safe_share(self):
        return 0.5

class ICarrierRevenueShare(ABC):
    """What a carrier takes on a preload."""

    @property
    @abstractmethod
    def carrier_share(self): ...

class DefaultCarrierRevenueShare(ICarrierRevenueShare):
    """The decision as it stands."""

    @property
    def carrier_share(self):
        return 0.25

class ISaServiceConnectors(ABC):
    """South African banks and wallets with a connector."""

    @property
    @abstractmethod
    def banks(self): ...

    @property
    @abstractmethod
    def wallets(self): ...

class DefaultSaServiceConnectors(ISaServiceConnectors):
    """The decision as it stands."""

    @property
    def banks(self):
        return ['Capitec', 'FNB', 'Standard', 'Absa', 'Nedbank']

    @property
    def wallets(self):
        return ['PayFast', 'SnapScan']

class ICrossBorderCorridors(ABC):
    """Cross-border corridors money can move along."""

    @property
    @abstractmethod
    def corridors(self): ...

class DefaultCrossBorderCorridors(ICrossBorderCorridors):
    """The decision as it stands."""

    @property
    def corridors(self):
        return ['SADC', 'ECOWAS', 'EAC']

class IEmailConnectorRegistry(ABC):
    """Mail providers with a connector. IMAP is LAST and is the one that means
    somebody with an unlisted provider is not shut out."""

    @property
    @abstractmethod
    def providers(self): ...

class DefaultEmailConnectorRegistry(IEmailConnectorRegistry):
    """The decision as it stands."""

    @property
    def providers(self):
        return ['Gmail', 'Outlook', 'iCloud', 'ProtonMail', 'Yandex', 'Yahoo', 'IMAP']

class ICalendarConnectorRegistry(ABC):
    """Calendar providers. CalDAV plays the same role IMAP does above."""

    @property
    @abstractmethod
    def providers(self): ...

class DefaultCalendarConnectorRegistry(ICalendarConnectorRegistry):
    """The decision as it stands."""

    @property
    def providers(self):
        return ['Google', 'Outlook', 'Apple', 'Yahoo', 'CalDAV']

class ICrmConnectorRegistry(ABC):
    """CRMs with a connector."""

    @property
    @abstractmethod
    def providers(self): ...

class DefaultCrmConnectorRegistry(ICrmConnectorRegistry):
    """The decision as it stands."""

    @property
    def providers(self):
        return ['HubSpot', 'Salesforce', 'Pipedrive', 'Zoho', 'Bitrix']

class IAccountingConnectorRegistry(ABC):
    """Accounting packages with a connector."""

    @property
    @abstractmethod
    def providers(self): ...

class DefaultAccountingConnectorRegistry(IAccountingConnectorRegistry):
    """The decision as it stands."""

    @property
    def providers(self):
        return ['Xero', 'Sage', 'QuickBooks', 'Wave', 'Manager.io']

class IBankingConnectorRegistry(ABC):
    """Open-banking rails, by jurisdiction. Named by STANDARD rather than by
    bank, because the standard is what a connector actually speaks."""

    @property
    @abstractmethod
    def providers(self): ...

class DefaultBankingConnectorRegistry(IBankingConnectorRegistry):
    """The decision as it stands."""

    @property
    def providers(self):
        return ['open-banking-ZA', 'open-banking-NG', 'open-banking-KE']

class IKaiOsSupport(ABC):
    """KaiOS is compiled for. A feature phone is still a phone."""

    @property
    @abstractmethod
    def is_compiled(self): ...

class DefaultKaiOsSupport(IKaiOsSupport):
    """The decision as it stands."""

    @property
    def is_compiled(self):
        return True

class ILowRamPhoneSupport(ABC):
    """The RAM floor. Below this is not a target device; AT this it must still
    work."""

    @property
    @abstractmethod
    def floor_mb(self): ...

class DefaultLowRamPhoneSupport(ILowRamPhoneSupport):
    """The decision as it stands."""

    @property
    def floor_mb(self):
        return 512

class ILowCpuOptimization(ABC):
    """The CPU floor. Optimising for a slow CPU is on by default, not a tuning
    option: the devices this is for are the slow ones."""

    @property
    @abstractmethod
    def floor_mhz(self): ...

class DefaultLowCpuOptimization(ILowCpuOptimization):
    """The decision as it stands."""

    @property
    def floor_mhz(self):
        return 600

class ISarbSandboxStatus(ABC):
    """SARB sandbox status. FALSE, and it stays false until it is not — a
    regulatory claim defaulting to true is the one lie that ends a company."""

    @property
    @abstractmethod
    def approved(self): ...

class DefaultSarbSandboxStatus(ISarbSandboxStatus):
    """The decision as it stands."""

    @property
    def approved(self):
        return False

class IIcasaApprovalStatus(ABC):
    """ICASA status. False for the same reason."""

    @property
    @abstractmethod
    def approved(self): ...

class DefaultIcasaApprovalStatus(IIcasaApprovalStatus):
    """The decision as it stands."""

    @property
    def approved(self):
        return False

class IGlobalRegulatorEngagement(ABC):
    """Jurisdictions with active regulator engagement."""

    @property
    @abstractmethod
    def active_jurisdictions(self): ...

class DefaultGlobalRegulatorEngagement(IGlobalRegulatorEngagement):
    """The decision as it stands."""

    @property
    def active_jurisdictions(self):
        return ['ZA', 'NG', 'KE', 'US', 'CA', 'UK', 'EU']

class ITaxInvoiceRegistry(ABC):
    """Invoice tax schemes that can be issued under."""

    @property
    @abstractmethod
    def schemes(self): ...

class DefaultTaxInvoiceRegistry(ITaxInvoiceRegistry):
    """The decision as it stands."""

    @property
    def schemes(self):
        return ['VAT', 'GST', 'Sales Tax', 'DST']

class ILawfulInterceptCompliance(ABC):
    """The posture, in one line, because it is the sentence a regulator asks
    for. Money is auditable; conversations are not, and cannot be made so
    later."""

    @property
    @abstractmethod
    def posture(self): ...

class DefaultLawfulInterceptCompliance(ILawfulInterceptCompliance):
    """The decision as it stands."""

    @property
    def posture(self):
        return 'Money decryptable to law, comms permanently blind'

class IBrainUnreachableMode(ABC):
    """When the remote brain cannot be reached the local one takes over. A
    device that stops working when a server does is not on-device."""

    @property
    @abstractmethod
    def local_takeover_enabled(self): ...

class DefaultBrainUnreachableMode(IBrainUnreachableMode):
    """The decision as it stands."""

    @property
    def local_takeover_enabled(self):
        return True

class INoInternetCacheTarget(ABC):
    """The share of requests that must be answerable with no internet at all."""

    @property
    @abstractmethod
    def hit_rate_target(self): ...

class DefaultNoInternetCacheTarget(INoInternetCacheTarget):
    """The decision as it stands."""

    @property
    def hit_rate_target(self):
        return 0.8

class IStorageFullDegradationPolicy(ABC):
    """What is given up first when the disk fills. 'nothing' is last and is
    LITERAL: the assistant never deletes what somebody said to it."""

    @property
    @abstractmethod
    def degrade_order(self): ...

class DefaultStorageFullDegradationPolicy(IStorageFullDegradationPolicy):
    """The decision as it stands."""

    @property
    def degrade_order(self):
        return 'cache > old-snapshots > chat-history > nothing'

class IPublicDisasterMode(ABC):
    """Current disaster posture."""

    @property
    @abstractmethod
    def current_state(self): ...

class DefaultPublicDisasterMode(IPublicDisasterMode):
    """The decision as it stands."""

    @property
    def current_state(self):
        return 'normal'

class ISustainablePerUserCostMath(ABC):
    """Minor units, not floats. Money in fractional binary is how a total stops
    matching the sum of its parts."""

    @property
    @abstractmethod
    def monthly_revenue_per_user_minor(self): ...

    @property
    @abstractmethod
    def monthly_marginal_cost_per_user_minor(self): ...

class DefaultSustainablePerUserCostMath(ISustainablePerUserCostMath):
    """The decision as it stands."""

    @property
    def monthly_revenue_per_user_minor(self):
        return 1900

    @property
    def monthly_marginal_cost_per_user_minor(self):
        return 380

class IPerCallCostCeiling(ABC):
    """A single call may not cost more than this."""

    @property
    @abstractmethod
    def ceiling_micro_usd(self): ...

class DefaultPerCallCostCeiling(IPerCallCostCeiling):
    """The decision as it stands."""

    @property
    def ceiling_micro_usd(self):
        return 400000

class IFreeTierCostCapping(ABC):
    """What the free tier is allowed to cost, per user, per month."""

    @property
    @abstractmethod
    def monthly_cap_micro_usd(self): ...

class DefaultFreeTierCostCapping(IFreeTierCostCapping):
    """The decision as it stands."""

    @property
    def monthly_cap_micro_usd(self):
        return 200000

class ILocalFirstRouting(ABC):
    """On-device first, always, unless something says otherwise."""

    @property
    @abstractmethod
    def preferred(self): ...

class DefaultLocalFirstRouting(ILocalFirstRouting):
    """The decision as it stands."""

    @property
    def preferred(self):
        return True

class IReferralProgramme(ABC):
    """The referral reward, in the local currency's minor unit."""

    @property
    @abstractmethod
    def reward_minor(self): ...

    @property
    @abstractmethod
    def currency(self): ...

class DefaultReferralProgramme(IReferralProgramme):
    """The decision as it stands."""

    @property
    def reward_minor(self):
        return 1900

    @property
    def currency(self):
        return 'ZAR'

class IFamilyAiSharing(ABC):
    """How many people share one family plan."""

    @property
    @abstractmethod
    def max_members(self): ...

class DefaultFamilyAiSharing(IFamilyAiSharing):
    """The decision as it stands."""

    @property
    def max_members(self):
        return 6

class ICrossProviderFederation(ABC):
    """Federating with other providers is on. A network that only talks to
    itself is a walled garden with extra steps."""

    @property
    @abstractmethod
    def enabled(self): ...

class DefaultCrossProviderFederation(ICrossProviderFederation):
    """The decision as it stands."""

    @property
    def enabled(self):
        return True

class IGroupNetworkEffects(ABC):
    """The group shapes people actually organise into here. Stokvel FIRST,
    because it is the one a foreign product always leaves out."""

    @property
    @abstractmethod
    def group_types(self): ...

class DefaultGroupNetworkEffects(IGroupNetworkEffects):
    """The decision as it stands."""

    @property
    def group_types(self):
        return ['Stokvel', 'Church', 'Community']

class IUserGrowthFlywheel(ABC):
    """The growth mechanic, stated plainly so it can be argued with."""

    @property
    @abstractmethod
    def mechanic(self): ...

class DefaultUserGrowthFlywheel(IUserGrowthFlywheel):
    """The decision as it stands."""

    @property
    def mechanic(self):
        return 'user invites friend; both get a month free'

class IThirdPartyHarmLiability(ABC):
    """Who answers when a third party is harmed."""

    @property
    @abstractmethod
    def framework(self): ...

class DefaultThirdPartyHarmLiability(IThirdPartyHarmLiability):
    """The decision as it stands."""

    @property
    def framework(self):
        return 'Operator-of-record indemnity backed by insurance pool'

class IChildProtectionMode(ABC):
    """COPPA and GDPR-K."""

    @property
    @abstractmethod
    def coppa_compliant(self): ...

    @property
    @abstractmethod
    def gdpr_k_compliant(self): ...

class DefaultChildProtectionMode(IChildProtectionMode):
    """The decision as it stands."""

    @property
    def coppa_compliant(self):
        return True

    @property
    def gdpr_k_compliant(self):
        return True

class IReligiousAccommodation(ABC):
    """Accommodations that change when the assistant SPEAKS AT ALL."""

    @property
    @abstractmethod
    def supported_modes(self): ...

class DefaultReligiousAccommodation(IReligiousAccommodation):
    """The decision as it stands."""

    @property
    def supported_modes(self):
        return ['prayer times', 'Shabbat mode', 'Eid silence']

class IIndigenousDataSovereignty(ABC):
    """The standard indigenous data is held to. CARE, not just FAIR: FAIR makes
    data usable, CARE asks whose it is."""

    @property
    @abstractmethod
    def standard(self): ...

class DefaultIndigenousDataSovereignty(IIndigenousDataSovereignty):
    """The decision as it stands."""

    @property
    def standard(self):
        return 'CARE Principles'

__all__ = [
    "DefaultAccountingConnectorRegistry",
    "DefaultBankingConnectorRegistry",
    "DefaultBrainUnreachableMode",
    "DefaultBugBountyChannel",
    "DefaultCalendarConnectorRegistry",
    "DefaultCarrierPreloadCatalog",
    "DefaultCarrierRevenueShare",
    "DefaultChildProtectionMode",
    "DefaultComplianceCertifications",
    "DefaultCrmConnectorRegistry",
    "DefaultCrossBorderCorridors",
    "DefaultCrossProviderFederation",
    "DefaultEmailConnectorRegistry",
    "DefaultFamilyAiSharing",
    "DefaultFreeTierCostCapping",
    "DefaultGlobalRegulatorEngagement",
    "DefaultGroupNetworkEffects",
    "DefaultIcasaApprovalStatus",
    "DefaultIndigenousDataSovereignty",
    "DefaultKaiOsSupport",
    "DefaultLawfulInterceptCompliance",
    "DefaultLinuxRepoFanout",
    "DefaultLocalFirstRouting",
    "DefaultLowCpuOptimization",
    "DefaultLowRamPhoneSupport",
    "DefaultNoInternetCacheTarget",
    "DefaultOemPreloadCatalog",
    "DefaultPerCallCostCeiling",
    "DefaultPluginMarketplaceRevenueShare",
    "DefaultPrivacyRegulationCompliance",
    "DefaultPublicDisasterMode",
    "DefaultPwaFallback",
    "DefaultReferralProgramme",
    "DefaultReligiousAccommodation",
    "DefaultSaServiceConnectors",
    "DefaultSarbSandboxStatus",
    "DefaultSideloadChannel",
    "DefaultStorageFullDegradationPolicy",
    "DefaultSustainablePerUserCostMath",
    "DefaultTaxInvoiceRegistry",
    "DefaultThirdPartyHarmLiability",
    "DefaultThirdPartySecurityAuditPublisher",
    "DefaultUserGrowthFlywheel",
    "DefaultVerifiablePrivacyProof",
    "IAccountingConnectorRegistry",
    "IBankingConnectorRegistry",
    "IBrainUnreachableMode",
    "IBugBountyChannel",
    "ICalendarConnectorRegistry",
    "ICarrierPreloadCatalog",
    "ICarrierRevenueShare",
    "IChildProtectionMode",
    "IComplianceCertifications",
    "ICrmConnectorRegistry",
    "ICrossBorderCorridors",
    "ICrossProviderFederation",
    "IEmailConnectorRegistry",
    "IFamilyAiSharing",
    "IFreeTierCostCapping",
    "IGlobalRegulatorEngagement",
    "IGroupNetworkEffects",
    "IIcasaApprovalStatus",
    "IIndigenousDataSovereignty",
    "IKaiOsSupport",
    "ILawfulInterceptCompliance",
    "ILinuxRepoFanout",
    "ILocalFirstRouting",
    "ILowCpuOptimization",
    "ILowRamPhoneSupport",
    "INoInternetCacheTarget",
    "IOemPreloadCatalog",
    "IPerCallCostCeiling",
    "IPluginMarketplaceRevenueShare",
    "IPrivacyRegulationCompliance",
    "IPublicDisasterMode",
    "IPwaFallback",
    "IReferralProgramme",
    "IReligiousAccommodation",
    "ISaServiceConnectors",
    "ISarbSandboxStatus",
    "ISideloadChannel",
    "IStorageFullDegradationPolicy",
    "ISustainablePerUserCostMath",
    "ITaxInvoiceRegistry",
    "IThirdPartyHarmLiability",
    "IThirdPartySecurityAuditPublisher",
    "IUserGrowthFlywheel",
    "IVerifiablePrivacyProof",
]
