# circle_ai/__init__.py — Circle AI Python SDK
#
# Re-exports every public symbol so callers can do:
#   from circle_ai import AffectState, KnownLanguages, IChatGenerator, ...

# models
from .models.models import ChatMessage, DownloadProgress

# memory
from .memory.affect_state import AffectState, AffectVad
from .memory.episodic_memory import EpisodicMemoryEntry
from .memory.feedback_signal import FeedbackPolarity, FeedbackSignal
from .memory.goal import Goal, GoalPriority, GoalStatus
from .memory.persona_state import PersonaState
from .memory.stores import (
    IAffectStore,
    IEpisodicMemoryStore,
    IFeedbackStore,
    IGoalStore,
    InMemoryFeedbackStore,
    IPersonaStore,
)
from .memory.in_memory_episodic_store import InMemoryEpisodicStore
from .memory.feedback_analyser import FeedbackAnalyser, PersonaAdaptation
from .memory.rag import ITextEmbedder, RagContextBuilder, RagPipelineBuilder
from .memory.multimodal import (
    CaptionResult,
    HeuristicMultimodalCaptioner,
    IMultimodalCaptioner,
    IMultimodalMemoryStore,
    InMemoryMultimodalMemoryStore,
    IngestionResult,
    MediaModality,
    MultimodalMemoryEntry,
    MultimodalMemoryIngester,
)
from .memory.compression import (
    BetaCodebook,
    BetaLloydMaxCodebook,
    BitPacker,
    COMPRESSED_TAG_KEY,
    CompressedEpisodicMemoryStore,
    CompressedMultimodalMemoryStore,
    EmbeddingPayloadCodec,
    OrthogonalRotation,
    TurboQuantCodec,
    TurboQuantPayload,
)
# memory — companion-state sync layer
from .memory.sync import (
    CompanionConversationSyncBridge,
    CompanionStateSyncEngine,
    ConversationStateDelta,
    HybridLogicalClock,
    ICompanionStateChannel,
    ICompanionStateSyncEngine,
    ISyncableEntryStore,
    InMemorySyncableEntryStore,
    InProcessCompanionStateChannel,
    InProcessSyncHub,
    LoraAdapterSnapshot,
    LoraAdapterSyncBridge,
    PersonaStateSyncBridge,
    RequestItem,
    StateVectorEntry,
    SyncEnvelope,
    SyncEnvelopeKind,
    SyncableEntry,
)
# memory — pipeline host runtime
from .memory.runtime import CompanionRuntime, CompanionRuntimeOptions

# security
from .security import AnomalySignal, ThreatVector

# identity
from .identity.identity_types import CircleIdentity, IdentityTier, RegisteredDevice
from .identity.biometric_profile import BiometricProfile
from .identity.biometric_store import IBiometricStore
from .identity.biometric_matcher import cosine_similarity, is_match

# languages
from .languages.language_types import DetectionResult, LanguageTag, WritingSystem
from .languages.known_languages import DefaultLanguageRegistry, KnownLanguages

# companion
from .companion.companion_types import (
    CompanionContext,
    CompanionProactiveEvent,
    CompanionTurn,
    InterfaceKind,
)
from .companion.face_affect_mapper import apply as apply_face_affect
from .companion.face_companion_bridge import CONFUSION_THRESHOLD, observe
from .companion.herjarvis_contracts import (
    AcquiredSkill,
    AgentToAgentMessage,
    AnticipatedNeed,
    BioSignal,
    CausalPrediction,
    CodeGenJob,
    ConfidenceBand,
    DelegationCredential,
    EmotionFrame,
    EpisodeRecord,
    FineTuneJobStatus,
    FirstTokenBudget,
    FusedPercept,
    IAgentPeerNetwork,
    IAlwaysOnPresence,
    IBioSignalStream,
    ICalibratedConfidence,
    ICodeGenerationLoop,
    IContinuousLearner,
    ICryptoDelegation,
    IEmotionSensor,
    IEpisodicMemory,
    IFederatedFineTuner,
    IFirstTokenOptimizer,
    IFusedPerception,
    IGoalPursuer,
    IIdentitySync,
    IInnerMonologue,
    ILiveWorldKnowledge,
    IPersonalKnowledgeGraph,
    IPhysicalActuator,
    IPredictiveEngine,
    ISelfImprovementLoop,
    ISkillAcquisition,
    ITheoryOfMind,
    IVoiceIdentity,
    IWorldModel,
    KnowledgeNode,
    KnowledgeRelation,
    LongHorizonGoal,
    OtherMindEstimate,
    PhysicalCommand,
    PhysicalCommandResult,
    SelfImprovementVerdict,
    SelfReflection,
    WorldFact,
)
from .companion.world_model import BayesianWorldModel, FrequencyWorldModel
from .companion.predictive_engine import (
    HistogramPredictiveEngine,
    SequencePredictiveEngine,
)
from .companion.inner_monologue import (
    ReasoningLoopInnerMonologue,
    TemplateInnerMonologue,
)
from .companion.theory_of_mind import BeliefTrackerTheoryOfMind
from .companion.herjarvis_impl import (
    AdjacencyPersonalKnowledgeGraph,
    ChannelBioSignalStream,
    ChannelFusedPerception,
    DemoStoreSkillAcquisition,
    EnergyBandVoiceIdentity,
    EwaContinuousLearner,
    HeartbeatAlwaysOnPresence,
    HistoricalCalibratedConfidence,
    HmacCryptoDelegation,
    ISignatureProvider,
    InMemoryFederatedFineTuner,
    InMemoryGoalPursuer,
    JsonIdentitySync,
    KeywordEmotionSensor,
    MailboxAgentPeerNetwork,
    RegistryPhysicalActuator,
    SlidingP50FirstTokenOptimizer,
    SyntaxCheckingCodeGenerationLoop,
    TfEpisodicMemory,
    TopicLiveWorldKnowledge,
    TrackingSelfImprovementLoop,
)
from .companion.capability_registry import (
    CapabilityEntry,
    ExternalCapabilityRegistry,
)
from .companion.self_bench_loop import SelfBenchSelfImprovementLoop
from .companion.session_factory import (
    CompanionSessionFactory,
    ICompanionSessionFactory,
)
from .companion.voice_listener import (
    IVoiceListener,
    VoiceCompanionListener,
)
from .companion.proactive_briefing import (
    IBriefingNotifier,
    ProactiveBriefingOptions,
    ProactiveBriefingService,
)
from .companion.proactive import (
    CronExpression,
    DelegateProactiveTaskRunner,
    IProactiveScheduler,
    IProactiveTaskRunner,
    IProactiveTaskSource,
    InMemoryProactiveTaskSource,
    NullProactiveTaskRunner,
    NullProactiveTaskSource,
    ProactiveScheduler,
    ProactiveTask,
    ProactiveTaskLoadError,
    ProactiveTaskRunResult,
    ProactiveTrigger,
)

# inference — full runtime surface
from .inference import (
    BundleFileSpec,
    ChatCapability,
    ChatFragment,
    ChatFragmentKind,
    ContextWindowBudgetManager,
    DeterministicChatGenerator,
    FileBackedFeedbackTrainingQueue,
    FileUrlFetcher,
    GenerationOptions,
    IChatGenerator,
    IFeedbackTrainingQueue,
    IFileFetcher,
    IKvCompressionNative,
    ILayerStreamingRunner,
    ILoRANative,
    IModelDownloadService,
    IModelSelector,
    InMemoryKvCompressionNative,
    InMemoryLoRANative,
    KvCompressionApplyResult,
    KvCompressionMode,
    LayerActivations,
    LayerShardDiscovery,
    LayerStreamingOrchestrator,
    LayerStreamingPlan,
    LayerWeightShard,
    LoRAAdapterManager,
    MnnKvCompression,
    ModelDownloadService,
    ModelSelection,
    NightlyAdapterTrainer,
    NightlyAdapterTrainerOptions,
    NullLayerStreamingRunner,
    PowerBudget,
    PowerBudgetPolicy,
    PowerBudgetResolution,
    PrefixCacheService,
    TrainingNotSupportedError,
    TrainingSample,
    VisionInput,
    build_qwen_chat_prompt,
    char_tokenizer,
    find_stop_sequence,
    generate_response_async,
    route_text,
    stream_fragments_async,
    strip_sha_algorithm_prefix,
)

# hosting — inference bridge
from .hosting.inference_bridge import (
    DeviceCapabilities,
    IInferenceBridge,
    InferenceFragment,
    InferenceFragmentKind,
    InferenceRequest,
    InferenceResponse,
    InferenceStatus,
    LocalProcessInferenceBridge,
    MockInferenceBridge,
    ModelDescriptor,
    ModelFormat,
)

# hosting — runtime + sub-hosts (AIService, endpoints, scheduler, triggers,
# proactive reasoning, thermal, warmup, tools, generative UI, observers,
# cloud-fallback chain, MCP dispatcher, multiplayer hub)
from .hosting import (
    AetherAIObserver,
    AIApiClient,
    AIChatEvent,
    AIHttpClient,
    AIOptions,
    AIService,
    AIStreamEvent,
    AIToolEvent,
    ArrivalForecast,
    BackgroundInferenceWorker,
    BackupBrainOrchestrator,
    BackupBrainPolicy,
    BrainHealth,
    BrainStatus,
    BrownoutReason,
    ButlerApiResponse,
    CloudFallbackChain,
    CronJob,
    CronJobState,
    CronScheduleParser,
    DefaultAvailableRamProbe,
    DeliveryTarget,
    FakeConfigurableChatGenerator,
    FallbackAIService,
    GuestPeerIdentity,
    HistogramRequestPredictor,
    HttpLoopbackEndpoint,
    IAIEndpoint,
    IAIObserver,
    IAIService,
    IAvailableRamProbe,
    IButlerApiTransport,
    ICircleAetherTransport,
    IConfigurableChatGenerator,
    IdleTrigger,
    IGenerativeUIRenderer,
    IMcpResourceProvider,
    IMcpTool,
    IMemoryPressureSource,
    IMultiplayerPeerIdentity,
    InMemoryScheduledTaskStore,
    InMemoryToolCatalog,
    InProcessButlerApiTransport,
    InProcessEndpoint,
    IProactiveReasoningService,
    IPushNotificationSender,
    IRequestPredictor,
    IScheduledTaskStore,
    IThermalThrottleService,
    IToolCatalog,
    IToolExecutor,
    IToolProvider,
    ITriggerCondition,
    JobCompletedEventArgs,
    JsonRenderParser,
    ManualMemoryPressureSource,
    McpDispatcher,
    McpResource,
    McpResourceContent,
    McpServerInfo,
    McpToolException,
    MemoryPressureLevel,
    MultiplayerHub,
    NullMemoryPressureSource,
    PeerState,
    PredictiveWarmupController,
    PredictiveWarmupOptions,
    ProactiveContext,
    ProactiveMessageEventArgs,
    ProactiveReasoningService,
    PushAIObserver,
    RecordingGenerativeUIRenderer,
    ScheduledAIService,
    ScheduleTrigger,
    ThermalState,
    ThermalThrottleService,
    ToolDescriptor,
    ToolExecutionResult,
    UiCatalogEntry,
    UiCatalogs,
    UiComponent,
    colour_for,
    generate_random_token,
    import_from_async,
    parse_tool_call,
)

# inference_server — OpenAI-compatible server (in-memory handlers)
from .inference_server import (
    AdminHandler,
    AdmissionControl,
    ApiKeyAuthHandler,
    AuthSchemes,
    ChatCompletionsHandler,
    CompanionTurnHandler,
    DeterministicBridgeFactory,
    EmbeddingsHandler,
    EndpointResult,
    IBridgeFactory,
    ICompanionSessionResolver,
    IInferenceServerModelRegistry,
    IModelLifecycleManager,
    INativeRuntimeStatus,
    InferenceServerModelRegistry,
    InferenceServerOptions,
    InMemoryCompanionSessionResolver,
    ModelLifecycleManager,
    NativeRuntimeStatus,
    ServerCounters,
    UnconfiguredBridgeFactory,
)

# inference_server_enterprise — multi-tenant / batch / shard / offload
from .inference_server_enterprise import (
    EvenSplitModelShardPlanner,
    IBatchScheduler,
    ICrossTierOffload,
    IModelShardPlanner,
    ITenantRouter,
    InMemoryBatchScheduler,
    NullBatchScheduler,
    NullCrossTierOffload,
    NullModelShardPlanner,
    NullTenantRouter,
    PolicyCrossTierOffload,
    RoundRobinTenantRouter,
    ServerTier,
)

# tools
from .tools.tool_types import ToolDefinition, ToolInvocation, ToolParameter, ToolResult
from .tools.facial_metric_matrix import (
    FaceBoundingBox,
    FaceExpressionClassification,
    FacialMetricMatrix,
)

# sync
from .sync.sync_types import SchedulingHint, SyncDeliveryMode, SyncDelta, SyncDomainKeys
from .sync.sync_channel import ISyncChannel
from .sync.sync_primitives import SyncReconciliation, VersionVector
from .sync.memory_sync_service import IMemorySyncService, MemorySyncService

# core — model-management runtime
from .core import (
    BundleFileEntry,
    BundleFileInfo,
    CircleAIAuditEntry,
    CircleAIAuditQuery,
    CircleAIAuditing,
    CircleEngine,
    DownloadProgressReport,
    HuggingFaceSource,
    ICircleAIAuditLog,
    ICircleAITenantContext,
    ICircleModule,
    IEmbeddingService,
    IModelDownloader,
    IModelLoader,
    IModelManager,
    IModelSource,
    LocalModelLoader,
    LocalModelManager,
    LoggerAuditLog,
    ModelDownloader,
    ModelEntry,
    ModelInfo,
    ModelScopeSource,
    NoopAuditLog,
    NullTenantContext,
    SafeModelHandle,
    ShardCompressedFrame,
    ShardKvCodec,
    SingleTenantContext,
    SourceDownloadHelper,
    load_model,
)

# embeddings — text embedding + local store/index
from .embeddings import (
    DeterministicEmbeddingBackend,
    EmbeddingDocument,
    EmbeddingIndexHit,
    EmbeddingSearchHit,
    HnswEmbeddingStore,
    ICircleEmbeddingStore,
    IEmbeddingBackend,
    IEmbeddingEncoder,
    IEmbeddingIndex,
    InMemoryEmbeddingStore,
    TextEmbedder,
    TurboVecEmbeddingIndex,
)

__all__ = [
    # models
    "ChatMessage",
    "DownloadProgress",
    # memory
    "AffectState",
    "AffectVad",
    "EpisodicMemoryEntry",
    "FeedbackPolarity",
    "FeedbackSignal",
    "Goal",
    "GoalPriority",
    "GoalStatus",
    "PersonaState",
    "IAffectStore",
    "IEpisodicMemoryStore",
    "IFeedbackStore",
    "IGoalStore",
    "IPersonaStore",
    "InMemoryEpisodicStore",
    "InMemoryFeedbackStore",
    "FeedbackAnalyser",
    "PersonaAdaptation",
    "ITextEmbedder",
    "RagContextBuilder",
    "RagPipelineBuilder",
    "CaptionResult",
    "HeuristicMultimodalCaptioner",
    "IMultimodalCaptioner",
    "IMultimodalMemoryStore",
    "InMemoryMultimodalMemoryStore",
    "IngestionResult",
    "MediaModality",
    "MultimodalMemoryEntry",
    "MultimodalMemoryIngester",
    "BetaCodebook",
    "BetaLloydMaxCodebook",
    "BitPacker",
    "COMPRESSED_TAG_KEY",
    "CompressedEpisodicMemoryStore",
    "CompressedMultimodalMemoryStore",
    "EmbeddingPayloadCodec",
    "OrthogonalRotation",
    "TurboQuantCodec",
    "TurboQuantPayload",
    # memory — companion-state sync layer
    "HybridLogicalClock",
    "SyncableEntry",
    "SyncEnvelope",
    "SyncEnvelopeKind",
    "StateVectorEntry",
    "RequestItem",
    "ISyncableEntryStore",
    "InMemorySyncableEntryStore",
    "ICompanionStateChannel",
    "InProcessCompanionStateChannel",
    "InProcessSyncHub",
    "ICompanionStateSyncEngine",
    "CompanionStateSyncEngine",
    "PersonaStateSyncBridge",
    "LoraAdapterSnapshot",
    "LoraAdapterSyncBridge",
    "CompanionConversationSyncBridge",
    "ConversationStateDelta",
    # memory — pipeline host runtime
    "CompanionRuntime",
    "CompanionRuntimeOptions",
    # identity
    "CircleIdentity",
    "IdentityTier",
    "RegisteredDevice",
    "BiometricProfile",
    "IBiometricStore",
    "cosine_similarity",
    "is_match",
    # languages
    "DetectionResult",
    "DefaultLanguageRegistry",
    "KnownLanguages",
    "LanguageTag",
    "WritingSystem",
    # companion
    "CompanionContext",
    "CompanionProactiveEvent",
    "CompanionTurn",
    "InterfaceKind",
    "CONFUSION_THRESHOLD",
    "apply_face_affect",
    "observe",
    # companion — HER/Jarvis reasoning core (contracts + records)
    "AcquiredSkill",
    "AgentToAgentMessage",
    "AnticipatedNeed",
    "BioSignal",
    "CausalPrediction",
    "CodeGenJob",
    "ConfidenceBand",
    "DelegationCredential",
    "EmotionFrame",
    "EpisodeRecord",
    "FineTuneJobStatus",
    "FirstTokenBudget",
    "FusedPercept",
    "IAgentPeerNetwork",
    "IAlwaysOnPresence",
    "IBioSignalStream",
    "ICalibratedConfidence",
    "ICodeGenerationLoop",
    "IContinuousLearner",
    "ICryptoDelegation",
    "IEmotionSensor",
    "IEpisodicMemory",
    "IFederatedFineTuner",
    "IFirstTokenOptimizer",
    "IFusedPerception",
    "IGoalPursuer",
    "IIdentitySync",
    "IInnerMonologue",
    "ILiveWorldKnowledge",
    "IPersonalKnowledgeGraph",
    "IPhysicalActuator",
    "IPredictiveEngine",
    "ISelfImprovementLoop",
    "ISkillAcquisition",
    "ITheoryOfMind",
    "IVoiceIdentity",
    "IWorldModel",
    "KnowledgeNode",
    "KnowledgeRelation",
    "LongHorizonGoal",
    "OtherMindEstimate",
    "PhysicalCommand",
    "PhysicalCommandResult",
    "SelfImprovementVerdict",
    "SelfReflection",
    "WorldFact",
    # companion — HER/Jarvis reasoning core (implementations)
    "BayesianWorldModel",
    "FrequencyWorldModel",
    "SequencePredictiveEngine",
    "HistogramPredictiveEngine",
    "ReasoningLoopInnerMonologue",
    "TemplateInnerMonologue",
    "BeliefTrackerTheoryOfMind",
    "AdjacencyPersonalKnowledgeGraph",
    "ChannelBioSignalStream",
    "ChannelFusedPerception",
    "DemoStoreSkillAcquisition",
    "EnergyBandVoiceIdentity",
    "EwaContinuousLearner",
    "HeartbeatAlwaysOnPresence",
    "HistoricalCalibratedConfidence",
    "HmacCryptoDelegation",
    "ISignatureProvider",
    "InMemoryFederatedFineTuner",
    "InMemoryGoalPursuer",
    "JsonIdentitySync",
    "KeywordEmotionSensor",
    "MailboxAgentPeerNetwork",
    "RegistryPhysicalActuator",
    "SlidingP50FirstTokenOptimizer",
    "SyntaxCheckingCodeGenerationLoop",
    "TfEpisodicMemory",
    "TopicLiveWorldKnowledge",
    "TrackingSelfImprovementLoop",
    "SelfBenchSelfImprovementLoop",
    # companion — capability registry + factory
    "CapabilityEntry",
    "ExternalCapabilityRegistry",
    "CompanionSessionFactory",
    "ICompanionSessionFactory",
    "IVoiceListener",
    "VoiceCompanionListener",
    # companion — proactive briefing
    "IBriefingNotifier",
    "ProactiveBriefingOptions",
    "ProactiveBriefingService",
    # companion — proactive scheduling substrate
    "CronExpression",
    "DelegateProactiveTaskRunner",
    "IProactiveScheduler",
    "IProactiveTaskRunner",
    "IProactiveTaskSource",
    "InMemoryProactiveTaskSource",
    "NullProactiveTaskRunner",
    "NullProactiveTaskSource",
    "ProactiveScheduler",
    "ProactiveTask",
    "ProactiveTaskLoadError",
    "ProactiveTaskRunResult",
    "ProactiveTrigger",
    # inference — full runtime surface
    "GenerationOptions",
    "IChatGenerator",
    "ChatCapability",
    "ChatFragment",
    "ChatFragmentKind",
    "ModelSelection",
    "IModelSelector",
    "PowerBudget",
    "PowerBudgetPolicy",
    "PowerBudgetResolution",
    "generate_response_async",
    "stream_fragments_async",
    "DeterministicChatGenerator",
    "build_qwen_chat_prompt",
    "find_stop_sequence",
    "route_text",
    "KvCompressionMode",
    "KvCompressionApplyResult",
    "MnnKvCompression",
    "IKvCompressionNative",
    "InMemoryKvCompressionNative",
    "ContextWindowBudgetManager",
    "PrefixCacheService",
    "VisionInput",
    "BundleFileSpec",
    "IFileFetcher",
    "FileUrlFetcher",
    "IModelDownloadService",
    "ModelDownloadService",
    "strip_sha_algorithm_prefix",
    "ILayerStreamingRunner",
    "NullLayerStreamingRunner",
    "LayerStreamingOrchestrator",
    "LayerShardDiscovery",
    "LayerStreamingPlan",
    "LayerWeightShard",
    "LayerActivations",
    "IFeedbackTrainingQueue",
    "FileBackedFeedbackTrainingQueue",
    "TrainingSample",
    "NightlyAdapterTrainer",
    "NightlyAdapterTrainerOptions",
    "LoRAAdapterManager",
    "ILoRANative",
    "InMemoryLoRANative",
    "TrainingNotSupportedError",
    "char_tokenizer",
    # hosting — inference bridge
    "IInferenceBridge",
    "LocalProcessInferenceBridge",
    "ModelDescriptor",
    "ModelFormat",
    "InferenceRequest",
    "InferenceResponse",
    "InferenceStatus",
    "InferenceFragment",
    "InferenceFragmentKind",
    "DeviceCapabilities",
    # inference_server — OpenAI-compatible server
    "InferenceServerOptions",
    "ServerCounters",
    "AdmissionControl",
    "ApiKeyAuthHandler",
    "AuthSchemes",
    "IInferenceServerModelRegistry",
    "InferenceServerModelRegistry",
    "INativeRuntimeStatus",
    "NativeRuntimeStatus",
    "IModelLifecycleManager",
    "ModelLifecycleManager",
    "ICompanionSessionResolver",
    "InMemoryCompanionSessionResolver",
    "IBridgeFactory",
    "UnconfiguredBridgeFactory",
    "DeterministicBridgeFactory",
    "EndpointResult",
    "ChatCompletionsHandler",
    "EmbeddingsHandler",
    "CompanionTurnHandler",
    "AdminHandler",
    # inference_server_enterprise
    "ServerTier",
    "ITenantRouter",
    "IBatchScheduler",
    "IModelShardPlanner",
    "ICrossTierOffload",
    "RoundRobinTenantRouter",
    "InMemoryBatchScheduler",
    "EvenSplitModelShardPlanner",
    "PolicyCrossTierOffload",
    "NullTenantRouter",
    "NullBatchScheduler",
    "NullModelShardPlanner",
    "NullCrossTierOffload",
    # tools
    "FaceBoundingBox",
    "FaceExpressionClassification",
    "FacialMetricMatrix",
    "ToolDefinition",
    "ToolInvocation",
    "ToolParameter",
    "ToolResult",
    # sync
    "SchedulingHint",
    "SyncDeliveryMode",
    "SyncDelta",
    "SyncDomainKeys",
    "ISyncChannel",
    "SyncReconciliation",
    "VersionVector",
    "IMemorySyncService",
    "MemorySyncService",
    # security
    "AnomalySignal",
    "ThreatVector",
    # core — model-management runtime
    "IModelLoader",
    "LocalModelLoader",
    "ModelInfo",
    "BundleFileInfo",
    "IModelManager",
    "LocalModelManager",
    "IModelDownloader",
    "ModelDownloader",
    "ModelEntry",
    "BundleFileEntry",
    "DownloadProgressReport",
    "IModelSource",
    "ModelScopeSource",
    "HuggingFaceSource",
    "SourceDownloadHelper",
    "SafeModelHandle",
    "load_model",
    "CircleEngine",
    "ICircleModule",
    "IEmbeddingService",
    "ICircleAITenantContext",
    "NullTenantContext",
    "SingleTenantContext",
    "ICircleAIAuditLog",
    "CircleAIAuditEntry",
    "CircleAIAuditQuery",
    "NoopAuditLog",
    "LoggerAuditLog",
    "CircleAIAuditing",
    "ShardKvCodec",
    "ShardCompressedFrame",
    # embeddings — text embedding + local store/index
    "TextEmbedder",
    "IEmbeddingBackend",
    "DeterministicEmbeddingBackend",
    "IEmbeddingEncoder",
    "EmbeddingDocument",
    "EmbeddingSearchHit",
    "ICircleEmbeddingStore",
    "EmbeddingIndexHit",
    "IEmbeddingIndex",
    "InMemoryEmbeddingStore",
    "TurboVecEmbeddingIndex",
    "HnswEmbeddingStore",
]
