# circle_ai/__init__.py — Circle AI Python SDK
#
# Re-exports every public symbol so callers can do:
#   from circle_ai import AffectState, KnownLanguages, IChatGenerator, ...

# models
from .models.models import ChatMessage, DownloadProgress

# memory
from .memory.affect_state import AffectState, AffectVad
from .memory.episodic_memory import EpisodicMemoryEntry
from .memory.feedback_signal import FeedbackPolarity, FeedbackSignal
from .memory.goal import Goal, GoalPriority, GoalStatus
from .memory.persona_state import PersonaState
from .memory.stores import (
    IAffectStore,
    IEpisodicMemoryStore,
    IFeedbackStore,
    IGoalStore,
    InMemoryFeedbackStore,
    IPersonaStore,
)
from .memory.in_memory_episodic_store import InMemoryEpisodicStore
from .memory.feedback_analyser import FeedbackAnalyser, PersonaAdaptation
from .memory.rag import ITextEmbedder, RagContextBuilder, RagPipelineBuilder
from .memory.multimodal import (
    CaptionResult,
    HeuristicMultimodalCaptioner,
    IMultimodalCaptioner,
    IMultimodalMemoryStore,
    InMemoryMultimodalMemoryStore,
    IngestionResult,
    MediaModality,
    MultimodalMemoryEntry,
    MultimodalMemoryIngester,
)
from .memory.compression import (
    BetaCodebook,
    BetaLloydMaxCodebook,
    BitPacker,
    COMPRESSED_TAG_KEY,
    CompressedEpisodicMemoryStore,
    CompressedMultimodalMemoryStore,
    EmbeddingPayloadCodec,
    OrthogonalRotation,
    TurboQuantCodec,
    TurboQuantPayload,
)
# memory — companion-state sync layer
from .memory.sync import (
    CompanionConversationSyncBridge,
    CompanionStateSyncEngine,
    ConversationStateDelta,
    HybridLogicalClock,
    ICompanionStateChannel,
    ICompanionStateSyncEngine,
    ISyncableEntryStore,
    InMemorySyncableEntryStore,
    InProcessCompanionStateChannel,
    InProcessSyncHub,
    LoraAdapterSnapshot,
    LoraAdapterSyncBridge,
    PersonaStateSyncBridge,
    RequestItem,
    StateVectorEntry,
    SyncEnvelope,
    SyncEnvelopeKind,
    SyncableEntry,
)
# memory — pipeline host runtime
from .memory.runtime import CompanionRuntime, CompanionRuntimeOptions

# security — peer-intelligence pipeline (local immune system + transport-agnostic peer trust)
from .security import (
    AISecurityLayerService,
    AetherIntelligenceService,
    AnomalyDispatchOutcome,
    AnomalyDispatchResult,
    AnomalySignal,
    DefaultAnomalyEventDispatcher,
    DefaultSecurityWatchdog,
    DirectivePublisher,
    IAnomalyEventDispatcher,
    IPeerDirectiveConsumer,
    IPeerIntelligence,
    IPeerSecurityEventFeed,
    IPeerSecurityLayer,
    ISecurityWatchdog,
    NodeTrustEntry,
    NodeTrustRegistry,
    PeerDirective,
    PeerDirectiveKind,
    PeerIntelligenceService,
    PeerNetworkHealthReport,
    PeerRoutingAdvice,
    PeerSecurityEvent,
    PeerSecurityEventKind,
    PeerSecurityPosture,
    PeerThreatAssessment,
    PeerThreatLevel,
    PeerTrustScoreUpdate,
    RedactedEvidenceJsonConverter,
    SecurityCheckpoint,
    SecurityLayerService,
    SecurityOptions,
    SecurityResponse,
    SecurityResponseKind,
    ThreatDetector,
    ThreatVector,
    UhidKeyRing,
)

# aether — the Aether <-> BhenguAI contract boundary (5 contracts)
from .aether import (
    AetherInstallLevel,
    AetherNetworkEvent,
    AetherNetworkEventKind,
    AetherNodeEvent,
    AetherNodeEventKind,
    AetherNodeHealth,
    AetherRouteEvent,
    AetherRouteEventKind,
    AetherSecurityEvent,
    AetherSecurityEventKind,
    AetherThreatLevel,
    AetherTransportEvent,
    AetherTransportEventKind,
    AetherTransportKind,
    AetherVersion,
    AuthChallengeReason,
    AuthChallengeResult,
    AuthMethod,
    IAISecurityLayer,
    IAetherContext,
    IAetherIntelligence,
    IAetherTelemetry,
    IAetherTelemetryObserver,
    IAuthChallenge,
    InMemoryAISecurityLayer,
    InMemoryAetherContext,
    InMemoryAetherIntelligence,
    InMemoryAetherTelemetry,
    InMemoryAuthChallenge,
    ISecurityDirectiveConsumer,
    NetworkHealthReport,
    NullAetherTelemetry,
    RoutingAdvice,
    SecurityDirective,
    SecurityDirectiveKind,
    SecurityPosture,
    ThreatAssessment,
    TrustScoreUpdate,
)

# aethernet — CircleAI <-> AetherNet mesh runtime bindings + capability registry
from .aethernet import (
    AetherNetCompanionStateChannel,
    AetherNetContextAdapter,
    AetherNetDirectiveSink,
    AetherNetInboundDirectiveBridge,
    AetherNetTelemetryAdapter,
    CircleAiAetherNetAiProvider,
    EventTranslator,
    IMeshCapabilityBroadcaster,
    IMeshCapabilityRegistry,
    InMemoryMeshCapabilityRegistry,
    MeshCapabilityAdvertisement,
    NullMeshCapabilityBroadcaster,
)

# security_aethernet — AetherNet-specific security bindings (mesh directive gate)
from .security_aethernet import (
    AetherIntelligenceAdapter,
    AetherMapper,
    AetherSecurityBridge,
    GateDecision,
    MeshDirectiveStore,
    MeshGatedCompanionSession,
    MeshSecurityBlockedException,
    MeshSecurityGate,
)

# speech — CircleAI.Speech + CircleAI.Speech.Cloud: ASR / TTS / wake-word / VAD /
# end-of-turn / echo-cancel / noise-reduce / G.711 conversion + voice-intent router
from .speech import (
    AudioCodec,
    AudioFormatConverter,
    DeepFilterNetNoiseReducer,
    EndOfTurnResult,
    EnergyVoiceActivityDetector,
    IEchoCanceller,
    IEchoCancellerModelRunner,
    IEndOfTurnDetector,
    INoiseReducer,
    INoiseReducerModelRunner,
    IOpticalCharacterRecognizer,
    ISpeechRecognizer,
    ISpeechSynthesizer,
    ITurnModelRunner,
    IVadModelRunner,
    IVoiceIntentRouter,
    KeywordSpeechRecognizer,
    KeywordVoiceIntentRouter,
    KeywordWakeWordDetector,
    KrispNoiseReducer,
    NlmsEchoCanceller,
    NullEchoCanceller,
    NullEndOfTurnDetector,
    NullNoiseReducer,
    NullOpticalCharacterRecognizer,
    NullSpeechRecognizer,
    NullSpeechSynthesizer,
    NullVoiceIntentRouter,
    OcrResult,
    OcrTextBlock,
    RuleBasedEndOfTurnDetector,
    SileroVoiceActivityDetector,
    SmartTurnDetector,
    SpectralSubtractionNoiseReducer,
    SynthesisResult,
    TemplateSpeechSynthesizer,
    TranscribedSegment,
    VadFrameResult,
    VoiceIntent,
    VoiceIntentMatch,
    WebRtcEchoCanceller,
)
from .speech import IVoiceActivityDetector as ISpeechVoiceActivityDetector
from .speech import IWakeWordDetector as ISpeechWakeWordDetector
from .speech import NullVoiceActivityDetector as NullSpeechVoiceActivityDetector
from .speech import NullWakeWordDetector as NullSpeechWakeWordDetector
from .speech import TranscriptionResult as SpeechTranscriptionResult
from .speech import WakeWordEvent as SpeechWakeWordEvent

# voice — CircleAI.Voice: audio capture, wake-word, VAD, transcription, TTS,
# speaker-identity, speech-emotion + the VoicePipeline composition
from .voice import (
    AudioFormat,
    EnergyVadDetector,
    EnergyWakeWordDetector,
    EnrolledSpeaker,
    IAudioCapture,
    IEmotionClassifier,
    ISpeakerEmbedder,
    ISpeakerIdentity,
    ISpeechEmotionDetector,
    ITtsEngine,
    IVoiceTranscriber,
    NullAudioCapture,
    NullTtsEngine,
    NullVoiceTranscriber,
    OnnxSpeakerIdentity,
    OnnxSpeechEmotionDetector,
    PartialTranscription,
    PCM16_MONO_16K,
    SpeakerEmbedderInputKind,
    SpeakerIdentityConfig,
    SpeechEmotionConfig,
    SpeechEmotionFrame,
    TranscribedEventArgs,
    TtsSynthesisResult,
    VadSegment,
    VoicePipeline,
    WakeWordDetectedEventArgs,
)
from .voice import IVoiceActivityDetector as IVoiceVoiceActivityDetector
from .voice import IWakeWordDetector as IVoiceWakeWordDetector
from .voice import NullVoiceActivityDetector as NullVoiceVoiceActivityDetector
from .voice import NullWakeWordDetector as NullVoiceWakeWordDetector
from .voice import TranscriptionResult as VoiceTranscriptionResult

# vision — CircleAI.Vision: camera capture, CV runtime, face detect/embed/liveness,
# KYC document verification, license-plate recognition, BLE/RF anomaly detection.
# ONNX YOLO/ArcFace models + native codecs are injected behind the I*ModelRunner seams.
from .vision import (
    BluetoothAnomaly,
    BluetoothAnomalyHandler,
    BoundingBox,
    DetectedFace,
    DocumentField,
    DocumentVerificationResult,
    FaceDetectorModelOutput,
    FaceEmbedding,
    IBluetoothAnomalyDetector,
    IComputerVisionRuntime,
    IDocumentVerifier,
    IFaceDetector,
    IFaceDetectorModelRunner,
    IFaceEmbedder,
    IFaceEmbedderModelRunner,
    IFaceLivenessDetector,
    IPlateModelRunner,
    IPlateRecognizer,
    IVideoCapture,
    LandmarkPoint,
    LivenessResult,
    NullBluetoothAnomalyDetector,
    NullComputerVisionRuntime,
    NullDocumentVerifier,
    NullFaceDetector,
    NullFaceEmbedder,
    NullFaceLivenessDetector,
    NullPlateRecognizer,
    NullVideoCapture,
    OnnxFaceDetector,
    OnnxFaceDetectorOptions,
    OnnxFaceEmbedder,
    OnnxFaceEmbedderOptions,
    OnnxPlateRecognizer,
    OnnxPlateRecognizerOptions,
    PlateModelOutput,
    PlateRecognitionResult,
    VideoFrame,
    VideoPixelFormat,
)
from .vision import IDisposable as IVisionDisposable

# vision.cloud — CircleAI.Vision.Cloud: image generation (OpenAI / Stability),
# a null default and a fallback-chain composite; real providers speak HTTP behind
# the injected IImageHttpTransport seam.
from .vision.cloud import (
    IImageGenerator,
    IImageHttpTransport,
    ImageArtifact,
    ImageGenerationRequest,
    ImageGeneratorFallbackChain,
    InMemoryImageHttpTransport,
    NullImageGenerator,
    OpenAiImageGenerator,
    OpenAiImageOptions,
    StabilityImageGenerator,
    StabilityImageOptions,
)
from .vision.cloud import HttpRequest as ImageHttpRequest
from .vision.cloud import HttpResponse as ImageHttpResponse

# video — CircleAI.Video: short-video generation behind txtMe Video Mail —
# IVideoGenerator + IStyleScript + IStyleReference. CogVideoX-2B / LTX-Video are injected.
from .video import (
    AudioTrack,
    InMemoryStyleReference,
    IStyleReference,
    IStyleScript,
    IVideoGenerator,
    NullStyleScript,
    NullVideoGenerator,
    StyleAttribution,
    StyleId,
    StyleReference,
    StyleReferenceFrame,
    StyleScriptRequest,
    StyleScriptResult,
    VideoGenerationRequest,
    VideoGenerationResult,
    VideoResolution,
)

# identity
from .identity.identity_types import CircleIdentity, IdentityTier, RegisteredDevice
from .identity.biometric_profile import BiometricProfile
from .identity.biometric_store import IBiometricStore
from .identity.biometric_matcher import cosine_similarity, is_match

# languages
from .languages.language_types import DetectionResult, LanguageTag, WritingSystem
from .languages.known_languages import DefaultLanguageRegistry, KnownLanguages

# companion
from .companion.companion_types import (
    CompanionContext,
    CompanionProactiveEvent,
    CompanionTurn,
    InterfaceKind,
)
from .companion.face_affect_mapper import apply as apply_face_affect
from .companion.face_companion_bridge import CONFUSION_THRESHOLD, observe
from .companion.herjarvis_contracts import (
    AcquiredSkill,
    AgentToAgentMessage,
    AnticipatedNeed,
    BioSignal,
    CausalPrediction,
    CodeGenJob,
    ConfidenceBand,
    DelegationCredential,
    EmotionFrame,
    EpisodeRecord,
    FineTuneJobStatus,
    FirstTokenBudget,
    FusedPercept,
    IAgentPeerNetwork,
    IAlwaysOnPresence,
    IBioSignalStream,
    ICalibratedConfidence,
    ICodeGenerationLoop,
    IContinuousLearner,
    ICryptoDelegation,
    IEmotionSensor,
    IEpisodicMemory,
    IFederatedFineTuner,
    IFirstTokenOptimizer,
    IFusedPerception,
    IGoalPursuer,
    IIdentitySync,
    IInnerMonologue,
    ILiveWorldKnowledge,
    IPersonalKnowledgeGraph,
    IPhysicalActuator,
    IPredictiveEngine,
    ISelfImprovementLoop,
    ISkillAcquisition,
    ITheoryOfMind,
    IVoiceIdentity,
    IWorldModel,
    KnowledgeNode,
    KnowledgeRelation,
    LongHorizonGoal,
    OtherMindEstimate,
    PhysicalCommand,
    PhysicalCommandResult,
    SelfImprovementVerdict,
    SelfReflection,
    WorldFact,
)
from .companion.world_model import BayesianWorldModel, FrequencyWorldModel
from .companion.predictive_engine import (
    HistogramPredictiveEngine,
    SequencePredictiveEngine,
)
from .companion.inner_monologue import (
    ReasoningLoopInnerMonologue,
    TemplateInnerMonologue,
)
from .companion.theory_of_mind import BeliefTrackerTheoryOfMind
from .companion.herjarvis_impl import (
    AdjacencyPersonalKnowledgeGraph,
    ChannelBioSignalStream,
    ChannelFusedPerception,
    DemoStoreSkillAcquisition,
    EnergyBandVoiceIdentity,
    EwaContinuousLearner,
    HeartbeatAlwaysOnPresence,
    HistoricalCalibratedConfidence,
    HmacCryptoDelegation,
    ISignatureProvider,
    InMemoryFederatedFineTuner,
    InMemoryGoalPursuer,
    JsonIdentitySync,
    KeywordEmotionSensor,
    MailboxAgentPeerNetwork,
    RegistryPhysicalActuator,
    SlidingP50FirstTokenOptimizer,
    SyntaxCheckingCodeGenerationLoop,
    TfEpisodicMemory,
    TopicLiveWorldKnowledge,
    TrackingSelfImprovementLoop,
)
from .companion.capability_registry import (
    CapabilityEntry,
    ExternalCapabilityRegistry,
)
from .companion.self_bench_loop import SelfBenchSelfImprovementLoop
from .companion.session_factory import (
    CompanionSessionFactory,
    ICompanionSessionFactory,
)
from .companion.voice_listener import (
    IVoiceListener,
    VoiceCompanionListener,
)
from .companion.proactive_briefing import (
    IBriefingNotifier,
    ProactiveBriefingOptions,
    ProactiveBriefingService,
)
from .companion.proactive import (
    CronExpression,
    DelegateProactiveTaskRunner,
    IProactiveScheduler,
    IProactiveTaskRunner,
    IProactiveTaskSource,
    InMemoryProactiveTaskSource,
    NullProactiveTaskRunner,
    NullProactiveTaskSource,
    ProactiveScheduler,
    ProactiveTask,
    ProactiveTaskLoadError,
    ProactiveTaskRunResult,
    ProactiveTrigger,
)

# inference — full runtime surface
from .inference import (
    BundleFileSpec,
    ChatCapability,
    ChatFragment,
    ChatFragmentKind,
    ContextWindowBudgetManager,
    DeterministicChatGenerator,
    FileBackedFeedbackTrainingQueue,
    FileUrlFetcher,
    GenerationOptions,
    IChatGenerator,
    IFeedbackTrainingQueue,
    IFileFetcher,
    IKvCompressionNative,
    ILayerStreamingRunner,
    ILoRANative,
    IModelDownloadService,
    IModelSelector,
    InMemoryKvCompressionNative,
    InMemoryLoRANative,
    KvCompressionApplyResult,
    KvCompressionMode,
    LayerActivations,
    LayerShardDiscovery,
    LayerStreamingOrchestrator,
    LayerStreamingPlan,
    LayerWeightShard,
    LoRAAdapterManager,
    MnnKvCompression,
    ModelDownloadService,
    ModelSelection,
    NightlyAdapterTrainer,
    NightlyAdapterTrainerOptions,
    NullLayerStreamingRunner,
    PowerBudget,
    PowerBudgetPolicy,
    PowerBudgetResolution,
    PrefixCacheService,
    TrainingNotSupportedError,
    TrainingSample,
    VisionInput,
    build_qwen_chat_prompt,
    char_tokenizer,
    find_stop_sequence,
    generate_response_async,
    route_text,
    stream_fragments_async,
    strip_sha_algorithm_prefix,
)

# hosting — inference bridge
from .hosting.inference_bridge import (
    DeviceCapabilities,
    IInferenceBridge,
    InferenceFragment,
    InferenceFragmentKind,
    InferenceRequest,
    InferenceResponse,
    InferenceStatus,
    LocalProcessInferenceBridge,
    MockInferenceBridge,
    ModelDescriptor,
    ModelFormat,
)

# hosting — runtime + sub-hosts (AIService, endpoints, scheduler, triggers,
# proactive reasoning, thermal, warmup, tools, generative UI, observers,
# cloud-fallback chain, MCP dispatcher, multiplayer hub)
from .hosting import (
    AetherAIObserver,
    AIApiClient,
    AIChatEvent,
    AIHttpClient,
    AIOptions,
    AIService,
    AIStreamEvent,
    AIToolEvent,
    ArrivalForecast,
    BackgroundInferenceWorker,
    BackupBrainOrchestrator,
    BackupBrainPolicy,
    BrainHealth,
    BrainStatus,
    BrownoutReason,
    ButlerApiResponse,
    CloudFallbackChain,
    CronJob,
    CronJobState,
    CronScheduleParser,
    DefaultAvailableRamProbe,
    DeliveryTarget,
    FakeConfigurableChatGenerator,
    FallbackAIService,
    GuestPeerIdentity,
    HistogramRequestPredictor,
    HttpLoopbackEndpoint,
    IAIEndpoint,
    IAIObserver,
    IAIService,
    IAvailableRamProbe,
    IButlerApiTransport,
    ICircleAetherTransport,
    IConfigurableChatGenerator,
    IdleTrigger,
    IGenerativeUIRenderer,
    IMcpResourceProvider,
    IMcpTool,
    IMemoryPressureSource,
    IMultiplayerPeerIdentity,
    InMemoryScheduledTaskStore,
    InMemoryToolCatalog,
    InProcessButlerApiTransport,
    InProcessEndpoint,
    IProactiveReasoningService,
    IPushNotificationSender,
    IRequestPredictor,
    IScheduledTaskStore,
    IThermalThrottleService,
    IToolCatalog,
    IToolExecutor,
    IToolProvider,
    ITriggerCondition,
    JobCompletedEventArgs,
    JsonRenderParser,
    ManualMemoryPressureSource,
    McpDispatcher,
    McpResource,
    McpResourceContent,
    McpServerInfo,
    McpToolException,
    MemoryPressureLevel,
    MultiplayerHub,
    NullMemoryPressureSource,
    PeerState,
    PredictiveWarmupController,
    PredictiveWarmupOptions,
    ProactiveContext,
    ProactiveMessageEventArgs,
    ProactiveReasoningService,
    PushAIObserver,
    RecordingGenerativeUIRenderer,
    ScheduledAIService,
    ScheduleTrigger,
    ThermalState,
    ThermalThrottleService,
    ToolDescriptor,
    ToolExecutionResult,
    UiCatalogEntry,
    UiCatalogs,
    UiComponent,
    colour_for,
    generate_random_token,
    import_from_async,
    parse_tool_call,
)

# inference_server — OpenAI-compatible server (in-memory handlers)
from .inference_server import (
    AdminHandler,
    AdmissionControl,
    ApiKeyAuthHandler,
    AuthSchemes,
    ChatCompletionsHandler,
    CompanionTurnHandler,
    DeterministicBridgeFactory,
    EmbeddingsHandler,
    EndpointResult,
    IBridgeFactory,
    ICompanionSessionResolver,
    IInferenceServerModelRegistry,
    IModelLifecycleManager,
    INativeRuntimeStatus,
    InferenceServerModelRegistry,
    InferenceServerOptions,
    InMemoryCompanionSessionResolver,
    ModelLifecycleManager,
    NativeRuntimeStatus,
    ServerCounters,
    UnconfiguredBridgeFactory,
)

# inference_server_enterprise — multi-tenant / batch / shard / offload
from .inference_server_enterprise import (
    EvenSplitModelShardPlanner,
    IBatchScheduler,
    ICrossTierOffload,
    IModelShardPlanner,
    ITenantRouter,
    InMemoryBatchScheduler,
    NullBatchScheduler,
    NullCrossTierOffload,
    NullModelShardPlanner,
    NullTenantRouter,
    PolicyCrossTierOffload,
    RoundRobinTenantRouter,
    ServerTier,
)

# tools
from .tools.tool_types import ToolDefinition, ToolInvocation, ToolParameter, ToolResult
from .tools.facial_metric_matrix import (
    FaceBoundingBox,
    FaceExpressionClassification,
    FacialMetricMatrix,
)

# sync
from .sync.sync_types import SchedulingHint, SyncDeliveryMode, SyncDelta, SyncDomainKeys
from .sync.sync_channel import ISyncChannel
from .sync.sync_primitives import SyncReconciliation, VersionVector
from .sync.memory_sync_service import IMemorySyncService, MemorySyncService

# core — model-management runtime
from .core import (
    BundleFileEntry,
    BundleFileInfo,
    CircleAIAuditEntry,
    CircleAIAuditQuery,
    CircleAIAuditing,
    CircleEngine,
    DownloadProgressReport,
    HuggingFaceSource,
    ICircleAIAuditLog,
    ICircleAITenantContext,
    ICircleModule,
    IEmbeddingService,
    IModelDownloader,
    IModelLoader,
    IModelManager,
    IModelSource,
    LocalModelLoader,
    LocalModelManager,
    LoggerAuditLog,
    ModelDownloader,
    ModelEntry,
    ModelInfo,
    ModelScopeSource,
    NoopAuditLog,
    NullTenantContext,
    SafeModelHandle,
    ShardCompressedFrame,
    ShardKvCodec,
    SingleTenantContext,
    SourceDownloadHelper,
    load_model,
)

# embeddings — text embedding + local store/index
from .embeddings import (
    DeterministicEmbeddingBackend,
    EmbeddingDocument,
    EmbeddingIndexHit,
    EmbeddingSearchHit,
    HnswEmbeddingStore,
    ICircleEmbeddingStore,
    IEmbeddingBackend,
    IEmbeddingEncoder,
    IEmbeddingIndex,
    InMemoryEmbeddingStore,
    TextEmbedder,
    TurboVecEmbeddingIndex,
)

# content_policy — safety-guardrails contracts + fast keyword/regex filters
from .content_policy import (
    CommonKeywordRules,
    IContentFilter,
    IPromptInjectionDetector,
    IRefusalPolicy,
    ISafetyAuditLog,
    KeywordContentFilter,
    KeywordPromptInjectionDetector,
    KeywordRule,
    NullContentFilter,
    NullPromptInjectionDetector,
    NullRefusalPolicy,
    NullSafetyAuditLog,
    SafetyAuditEntry,
    SafetyFinding,
    SafetyVerdict,
    ThresholdRefusalPolicy,
)

# model_alignment — targeted-abliteration toolkit + refuse-aligned-publish auditor
from .model_alignment import (
    AlignmentProfile,
    AlignmentResult,
    IAlignmentAuditor,
    IAlignmentToolkit,
    InMemoryAlignmentToolkit,
    NullAlignmentAuditor,
    NullAlignmentToolkit,
    RefuseAlignedPublishAuditor,
)

# safety — personal-safety domain pack (incidents / hazards / emergency contacts)
from .safety import (
    EmergencyContact,
    Hazard,
    Incident,
    IncidentSeverity,
    InMemorySafetyBoard,
    ISafetyBoard,
    SafetyDomainContext,
)

# safety_child — child-safety domain pack (trusted-adult ring / geofences / check-ins)
from .safety_child import (
    CheckIn,
    Geofence,
    IChildSafetyBoard,
    InMemoryChildSafetyBoard,
    SafetyChildDomainContext,
    TrustedAdult,
)
# networking — transport abstraction the 10 concrete transports implement
from .networking import (
    AetherHopTelemetry,
    AetherNetworkTransport,
    AetherPacketSummary,
    AetherPeer,
    AetherPeerDiscovery,
    AetherPeerKind,
    AetherSyncChannel,
    BluetoothCapabilityProfile,
    BluetoothCapabilityProfiles,
    BluetoothConnectionState,
    BluetoothEndpointDescriptor,
    BluetoothNetworkTransport,
    BluetoothThroughputSample,
    ConnectivityState,
    DefaultNetworkPolicy,
    DefaultTransportSelector,
    DtnBundle,
    DtnCustodyRecord,
    DtnPriority,
    DtnSyncChannel,
    GrpcCallSummary,
    GrpcChannelDescriptor,
    GrpcChannelState,
    GrpcNetworkTransport,
    GrpcRetryPolicies,
    GrpcRetryPolicy,
    GrpcSendNotSupportedError,
    HttpCacheKey,
    HttpEndpointDescriptor,
    HttpNetworkTransport,
    HttpRequestException,
    HttpRequestFailedError,
    HttpRequestSummary,
    HttpStatusFamily,
    HttpTransientError,
    IAetherMeshEngine,
    IBleGattAdapter,
    IConnectivityMonitor,
    IGrpcChannel,
    IHttpMessageSender,
    IMeshNetwork,
    IMessageChannel,
    IMessageSerializer,
    INetworkPolicy,
    INetworkTransport,
    IPeerDiscovery,
    ITransportSelector,
    InboundChannel,
    InMemoryAetherMeshEngine,
    InMemoryAetherNetRegistry,
    InMemoryBleGattAdapter,
    InMemoryBluetoothTransportRegistry,
    InMemoryConnectivityMonitor,
    InMemoryDtnBundleStore,
    InMemoryGrpcCallMetrics,
    InMemoryGrpcChannel,
    InMemoryHttpMessageSender,
    InMemoryHttpRequestMetrics,
    InMemoryMeshNetwork,
    InMemoryNetworkTransport,
    InMemoryWire,
    JsonMessageSerializer,
    MessagePriority,
    NetworkContext,
    NetworkPayload,
    NetworkPolicyBuilder,
    PeerInfo,
    PeerRole,
    TransportKind,
    TransportMessageChannel,
    # networking wave B — MQTT / NearLink / TCP / WebSocket / WiFi
    BROADCAST_ADDRESS,
    IMqttClient,
    INearLinkAdapter,
    ITcpStream,
    IUdpSocket,
    IWebSocketConnection,
    InMemoryMqttBroker,
    InMemoryMqttClient,
    InMemoryNearLinkAdapter,
    InMemoryNearLinkRegistry,
    InMemoryTcpConnectionRegistry,
    InMemoryTcpStream,
    InMemoryUdpBus,
    InMemoryUdpSocket,
    InMemoryWebSocketConnection,
    InMemoryWebSocketSessionRegistry,
    MqttClientDescriptor,
    MqttNetworkTransport,
    MqttQos,
    MqttRetainedMessage,
    MqttTopicDescriptor,
    NearLinkDevice,
    NearLinkPairingState,
    NearLinkPowerProfile,
    NearLinkSession,
    NearLinkThroughputSample,
    NearLinkTransport,
    TcpConnectionState,
    TcpEndpointDescriptor,
    TcpKnownPorts,
    TcpNetworkTransport,
    TcpStreamClosedError,
    TcpThroughputSample,
    UdpReceiveResult,
    WebSocketEndpointDescriptor,
    WebSocketFrameSummary,
    WebSocketLinkState,
    WebSocketMessageType,
    WebSocketReceiveResult,
    WebSocketTransport,
    WiFiNetworkTransport,
    WiFiPeerDiscovery,
)

__all__ = [
    # models
    "ChatMessage",
    "DownloadProgress",
    # memory
    "AffectState",
    "AffectVad",
    "EpisodicMemoryEntry",
    "FeedbackPolarity",
    "FeedbackSignal",
    "Goal",
    "GoalPriority",
    "GoalStatus",
    "PersonaState",
    "IAffectStore",
    "IEpisodicMemoryStore",
    "IFeedbackStore",
    "IGoalStore",
    "IPersonaStore",
    "InMemoryEpisodicStore",
    "InMemoryFeedbackStore",
    "FeedbackAnalyser",
    "PersonaAdaptation",
    "ITextEmbedder",
    "RagContextBuilder",
    "RagPipelineBuilder",
    "CaptionResult",
    "HeuristicMultimodalCaptioner",
    "IMultimodalCaptioner",
    "IMultimodalMemoryStore",
    "InMemoryMultimodalMemoryStore",
    "IngestionResult",
    "MediaModality",
    "MultimodalMemoryEntry",
    "MultimodalMemoryIngester",
    "BetaCodebook",
    "BetaLloydMaxCodebook",
    "BitPacker",
    "COMPRESSED_TAG_KEY",
    "CompressedEpisodicMemoryStore",
    "CompressedMultimodalMemoryStore",
    "EmbeddingPayloadCodec",
    "OrthogonalRotation",
    "TurboQuantCodec",
    "TurboQuantPayload",
    # memory — companion-state sync layer
    "HybridLogicalClock",
    "SyncableEntry",
    "SyncEnvelope",
    "SyncEnvelopeKind",
    "StateVectorEntry",
    "RequestItem",
    "ISyncableEntryStore",
    "InMemorySyncableEntryStore",
    "ICompanionStateChannel",
    "InProcessCompanionStateChannel",
    "InProcessSyncHub",
    "ICompanionStateSyncEngine",
    "CompanionStateSyncEngine",
    "PersonaStateSyncBridge",
    "LoraAdapterSnapshot",
    "LoraAdapterSyncBridge",
    "CompanionConversationSyncBridge",
    "ConversationStateDelta",
    # memory — pipeline host runtime
    "CompanionRuntime",
    "CompanionRuntimeOptions",
    # identity
    "CircleIdentity",
    "IdentityTier",
    "RegisteredDevice",
    "BiometricProfile",
    "IBiometricStore",
    "cosine_similarity",
    "is_match",
    # languages
    "DetectionResult",
    "DefaultLanguageRegistry",
    "KnownLanguages",
    "LanguageTag",
    "WritingSystem",
    # companion
    "CompanionContext",
    "CompanionProactiveEvent",
    "CompanionTurn",
    "InterfaceKind",
    "CONFUSION_THRESHOLD",
    "apply_face_affect",
    "observe",
    # companion — HER/Jarvis reasoning core (contracts + records)
    "AcquiredSkill",
    "AgentToAgentMessage",
    "AnticipatedNeed",
    "BioSignal",
    "CausalPrediction",
    "CodeGenJob",
    "ConfidenceBand",
    "DelegationCredential",
    "EmotionFrame",
    "EpisodeRecord",
    "FineTuneJobStatus",
    "FirstTokenBudget",
    "FusedPercept",
    "IAgentPeerNetwork",
    "IAlwaysOnPresence",
    "IBioSignalStream",
    "ICalibratedConfidence",
    "ICodeGenerationLoop",
    "IContinuousLearner",
    "ICryptoDelegation",
    "IEmotionSensor",
    "IEpisodicMemory",
    "IFederatedFineTuner",
    "IFirstTokenOptimizer",
    "IFusedPerception",
    "IGoalPursuer",
    "IIdentitySync",
    "IInnerMonologue",
    "ILiveWorldKnowledge",
    "IPersonalKnowledgeGraph",
    "IPhysicalActuator",
    "IPredictiveEngine",
    "ISelfImprovementLoop",
    "ISkillAcquisition",
    "ITheoryOfMind",
    "IVoiceIdentity",
    "IWorldModel",
    "KnowledgeNode",
    "KnowledgeRelation",
    "LongHorizonGoal",
    "OtherMindEstimate",
    "PhysicalCommand",
    "PhysicalCommandResult",
    "SelfImprovementVerdict",
    "SelfReflection",
    "WorldFact",
    # companion — HER/Jarvis reasoning core (implementations)
    "BayesianWorldModel",
    "FrequencyWorldModel",
    "SequencePredictiveEngine",
    "HistogramPredictiveEngine",
    "ReasoningLoopInnerMonologue",
    "TemplateInnerMonologue",
    "BeliefTrackerTheoryOfMind",
    "AdjacencyPersonalKnowledgeGraph",
    "ChannelBioSignalStream",
    "ChannelFusedPerception",
    "DemoStoreSkillAcquisition",
    "EnergyBandVoiceIdentity",
    "EwaContinuousLearner",
    "HeartbeatAlwaysOnPresence",
    "HistoricalCalibratedConfidence",
    "HmacCryptoDelegation",
    "ISignatureProvider",
    "InMemoryFederatedFineTuner",
    "InMemoryGoalPursuer",
    "JsonIdentitySync",
    "KeywordEmotionSensor",
    "MailboxAgentPeerNetwork",
    "RegistryPhysicalActuator",
    "SlidingP50FirstTokenOptimizer",
    "SyntaxCheckingCodeGenerationLoop",
    "TfEpisodicMemory",
    "TopicLiveWorldKnowledge",
    "TrackingSelfImprovementLoop",
    "SelfBenchSelfImprovementLoop",
    # companion — capability registry + factory
    "CapabilityEntry",
    "ExternalCapabilityRegistry",
    "CompanionSessionFactory",
    "ICompanionSessionFactory",
    "IVoiceListener",
    "VoiceCompanionListener",
    # companion — proactive briefing
    "IBriefingNotifier",
    "ProactiveBriefingOptions",
    "ProactiveBriefingService",
    # companion — proactive scheduling substrate
    "CronExpression",
    "DelegateProactiveTaskRunner",
    "IProactiveScheduler",
    "IProactiveTaskRunner",
    "IProactiveTaskSource",
    "InMemoryProactiveTaskSource",
    "NullProactiveTaskRunner",
    "NullProactiveTaskSource",
    "ProactiveScheduler",
    "ProactiveTask",
    "ProactiveTaskLoadError",
    "ProactiveTaskRunResult",
    "ProactiveTrigger",
    # inference — full runtime surface
    "GenerationOptions",
    "IChatGenerator",
    "ChatCapability",
    "ChatFragment",
    "ChatFragmentKind",
    "ModelSelection",
    "IModelSelector",
    "PowerBudget",
    "PowerBudgetPolicy",
    "PowerBudgetResolution",
    "generate_response_async",
    "stream_fragments_async",
    "DeterministicChatGenerator",
    "build_qwen_chat_prompt",
    "find_stop_sequence",
    "route_text",
    "KvCompressionMode",
    "KvCompressionApplyResult",
    "MnnKvCompression",
    "IKvCompressionNative",
    "InMemoryKvCompressionNative",
    "ContextWindowBudgetManager",
    "PrefixCacheService",
    "VisionInput",
    "BundleFileSpec",
    "IFileFetcher",
    "FileUrlFetcher",
    "IModelDownloadService",
    "ModelDownloadService",
    "strip_sha_algorithm_prefix",
    "ILayerStreamingRunner",
    "NullLayerStreamingRunner",
    "LayerStreamingOrchestrator",
    "LayerShardDiscovery",
    "LayerStreamingPlan",
    "LayerWeightShard",
    "LayerActivations",
    "IFeedbackTrainingQueue",
    "FileBackedFeedbackTrainingQueue",
    "TrainingSample",
    "NightlyAdapterTrainer",
    "NightlyAdapterTrainerOptions",
    "LoRAAdapterManager",
    "ILoRANative",
    "InMemoryLoRANative",
    "TrainingNotSupportedError",
    "char_tokenizer",
    # hosting — inference bridge
    "IInferenceBridge",
    "LocalProcessInferenceBridge",
    "ModelDescriptor",
    "ModelFormat",
    "InferenceRequest",
    "InferenceResponse",
    "InferenceStatus",
    "InferenceFragment",
    "InferenceFragmentKind",
    "DeviceCapabilities",
    # inference_server — OpenAI-compatible server
    "InferenceServerOptions",
    "ServerCounters",
    "AdmissionControl",
    "ApiKeyAuthHandler",
    "AuthSchemes",
    "IInferenceServerModelRegistry",
    "InferenceServerModelRegistry",
    "INativeRuntimeStatus",
    "NativeRuntimeStatus",
    "IModelLifecycleManager",
    "ModelLifecycleManager",
    "ICompanionSessionResolver",
    "InMemoryCompanionSessionResolver",
    "IBridgeFactory",
    "UnconfiguredBridgeFactory",
    "DeterministicBridgeFactory",
    "EndpointResult",
    "ChatCompletionsHandler",
    "EmbeddingsHandler",
    "CompanionTurnHandler",
    "AdminHandler",
    # inference_server_enterprise
    "ServerTier",
    "ITenantRouter",
    "IBatchScheduler",
    "IModelShardPlanner",
    "ICrossTierOffload",
    "RoundRobinTenantRouter",
    "InMemoryBatchScheduler",
    "EvenSplitModelShardPlanner",
    "PolicyCrossTierOffload",
    "NullTenantRouter",
    "NullBatchScheduler",
    "NullModelShardPlanner",
    "NullCrossTierOffload",
    # tools
    "FaceBoundingBox",
    "FaceExpressionClassification",
    "FacialMetricMatrix",
    "ToolDefinition",
    "ToolInvocation",
    "ToolParameter",
    "ToolResult",
    # sync
    "SchedulingHint",
    "SyncDeliveryMode",
    "SyncDelta",
    "SyncDomainKeys",
    "ISyncChannel",
    "SyncReconciliation",
    "VersionVector",
    "IMemorySyncService",
    "MemorySyncService",
    # security — peer-intelligence pipeline
    "AnomalySignal",
    "ThreatVector",
    "RedactedEvidenceJsonConverter",
    "SecurityCheckpoint",
    "SecurityResponse",
    "SecurityResponseKind",
    "ISecurityWatchdog",
    "DefaultSecurityWatchdog",
    "IAnomalyEventDispatcher",
    "DefaultAnomalyEventDispatcher",
    "AnomalyDispatchOutcome",
    "AnomalyDispatchResult",
    "UhidKeyRing",
    "PeerSecurityEventKind",
    "PeerThreatLevel",
    "PeerDirectiveKind",
    "PeerSecurityEvent",
    "PeerDirective",
    "PeerTrustScoreUpdate",
    "PeerSecurityPosture",
    "PeerNetworkHealthReport",
    "PeerThreatAssessment",
    "PeerRoutingAdvice",
    "IPeerDirectiveConsumer",
    "IPeerSecurityLayer",
    "IPeerIntelligence",
    "IPeerSecurityEventFeed",
    "SecurityOptions",
    "ThreatDetector",
    "NodeTrustRegistry",
    "NodeTrustEntry",
    "DirectivePublisher",
    "SecurityLayerService",
    "PeerIntelligenceService",
    "AISecurityLayerService",
    "AetherIntelligenceService",
    # core — model-management runtime
    "IModelLoader",
    "LocalModelLoader",
    "ModelInfo",
    "BundleFileInfo",
    "IModelManager",
    "LocalModelManager",
    "IModelDownloader",
    "ModelDownloader",
    "ModelEntry",
    "BundleFileEntry",
    "DownloadProgressReport",
    "IModelSource",
    "ModelScopeSource",
    "HuggingFaceSource",
    "SourceDownloadHelper",
    "SafeModelHandle",
    "load_model",
    "CircleEngine",
    "ICircleModule",
    "IEmbeddingService",
    "ICircleAITenantContext",
    "NullTenantContext",
    "SingleTenantContext",
    "ICircleAIAuditLog",
    "CircleAIAuditEntry",
    "CircleAIAuditQuery",
    "NoopAuditLog",
    "LoggerAuditLog",
    "CircleAIAuditing",
    "ShardKvCodec",
    "ShardCompressedFrame",
    # embeddings — text embedding + local store/index
    "TextEmbedder",
    "IEmbeddingBackend",
    "DeterministicEmbeddingBackend",
    "IEmbeddingEncoder",
    "EmbeddingDocument",
    "EmbeddingSearchHit",
    "ICircleEmbeddingStore",
    "EmbeddingIndexHit",
    "IEmbeddingIndex",
    "InMemoryEmbeddingStore",
    "TurboVecEmbeddingIndex",
    "HnswEmbeddingStore",
    # aether — Contract 1 telemetry + events
    "IAetherTelemetry",
    "IAetherTelemetryObserver",
    "NullAetherTelemetry",
    "InMemoryAetherTelemetry",
    "AetherNodeEvent",
    "AetherNodeEventKind",
    "AetherNodeHealth",
    "AetherTransportEvent",
    "AetherTransportEventKind",
    "AetherTransportKind",
    "AetherRouteEvent",
    "AetherRouteEventKind",
    "AetherSecurityEvent",
    "AetherSecurityEventKind",
    "AetherThreatLevel",
    "AetherNetworkEvent",
    "AetherNetworkEventKind",
    # aether — Contract 2 context
    "AetherInstallLevel",
    "AetherVersion",
    "IAetherContext",
    "InMemoryAetherContext",
    # aether — Contract 3 intelligence
    "NetworkHealthReport",
    "ThreatAssessment",
    "RoutingAdvice",
    "TrustScoreUpdate",
    "IAetherIntelligence",
    "InMemoryAetherIntelligence",
    # aether — Contract 4 security layer
    "SecurityDirectiveKind",
    "SecurityDirective",
    "SecurityPosture",
    "ISecurityDirectiveConsumer",
    "IAISecurityLayer",
    "InMemoryAISecurityLayer",
    # aether — Contract 5 auth challenge
    "AuthChallengeReason",
    "AuthMethod",
    "AuthChallengeResult",
    "IAuthChallenge",
    "InMemoryAuthChallenge",
    # aethernet — mesh capability discovery
    "MeshCapabilityAdvertisement",
    "IMeshCapabilityRegistry",
    "InMemoryMeshCapabilityRegistry",
    "IMeshCapabilityBroadcaster",
    "NullMeshCapabilityBroadcaster",
    # aethernet — bridge adapters
    "AetherNetContextAdapter",
    "AetherNetTelemetryAdapter",
    "AetherNetDirectiveSink",
    "AetherNetInboundDirectiveBridge",
    "CircleAiAetherNetAiProvider",
    "AetherNetCompanionStateChannel",
    "EventTranslator",
    # security_aethernet — mesh directive gate + bridges
    "AetherMapper",
    "AetherSecurityBridge",
    "AetherIntelligenceAdapter",
    "MeshDirectiveStore",
    "MeshSecurityGate",
    "GateDecision",
    "MeshSecurityBlockedException",
    "MeshGatedCompanionSession",
    # speech — CircleAI.Speech contracts + records
    "TranscribedSegment",
    "SpeechTranscriptionResult",
    "SynthesisResult",
    "OcrTextBlock",
    "OcrResult",
    "SpeechWakeWordEvent",
    "EndOfTurnResult",
    "VadFrameResult",
    "ISpeechRecognizer",
    "ISpeechSynthesizer",
    "ISpeechWakeWordDetector",
    "IEchoCanceller",
    "INoiseReducer",
    "IEndOfTurnDetector",
    "ISpeechVoiceActivityDetector",
    "IOpticalCharacterRecognizer",
    # speech — null implementations
    "NullSpeechRecognizer",
    "NullSpeechSynthesizer",
    "NullSpeechWakeWordDetector",
    "NullOpticalCharacterRecognizer",
    "NullEchoCanceller",
    "NullNoiseReducer",
    "NullSpeechVoiceActivityDetector",
    "NullEndOfTurnDetector",
    # speech — deterministic implementations
    "KeywordSpeechRecognizer",
    "TemplateSpeechSynthesizer",
    "KeywordWakeWordDetector",
    "NlmsEchoCanceller",
    "WebRtcEchoCanceller",
    "SpectralSubtractionNoiseReducer",
    "KrispNoiseReducer",
    "DeepFilterNetNoiseReducer",
    "EnergyVoiceActivityDetector",
    "SileroVoiceActivityDetector",
    "RuleBasedEndOfTurnDetector",
    "SmartTurnDetector",
    # speech — model-runner seams
    "IEchoCancellerModelRunner",
    "INoiseReducerModelRunner",
    "IVadModelRunner",
    "ITurnModelRunner",
    # speech — audio format conversion
    "AudioCodec",
    "AudioFormatConverter",
    # speech.cloud — voice-intent router
    "VoiceIntent",
    "VoiceIntentMatch",
    "IVoiceIntentRouter",
    "KeywordVoiceIntentRouter",
    "NullVoiceIntentRouter",
    # voice — CircleAI.Voice formats + results
    "AudioFormat",
    "PCM16_MONO_16K",
    "VoiceTranscriptionResult",
    "PartialTranscription",
    "TtsSynthesisResult",
    "VadSegment",
    "WakeWordDetectedEventArgs",
    "TranscribedEventArgs",
    # voice — contracts
    "IAudioCapture",
    "IVoiceTranscriber",
    "IVoiceWakeWordDetector",
    "IVoiceVoiceActivityDetector",
    "ITtsEngine",
    "ISpeakerIdentity",
    "ISpeechEmotionDetector",
    # voice — null implementations
    "NullAudioCapture",
    "NullVoiceTranscriber",
    "NullVoiceWakeWordDetector",
    "NullVoiceVoiceActivityDetector",
    "NullTtsEngine",
    # voice — deterministic implementations
    "EnergyVadDetector",
    "EnergyWakeWordDetector",
    "VoicePipeline",
    "OnnxSpeakerIdentity",
    "OnnxSpeechEmotionDetector",
    # voice — seams + configs
    "ISpeakerEmbedder",
    "SpeakerIdentityConfig",
    "SpeakerEmbedderInputKind",
    "EnrolledSpeaker",
    "IEmotionClassifier",
    "SpeechEmotionConfig",
    "SpeechEmotionFrame",
    # content_policy — safety-guardrails contracts + fast filters
    "SafetyVerdict",
    "SafetyFinding",
    "IContentFilter",
    "IRefusalPolicy",
    "IPromptInjectionDetector",
    "SafetyAuditEntry",
    "ISafetyAuditLog",
    "KeywordRule",
    "CommonKeywordRules",
    "KeywordContentFilter",
    "ThresholdRefusalPolicy",
    "KeywordPromptInjectionDetector",
    "NullContentFilter",
    "NullRefusalPolicy",
    "NullPromptInjectionDetector",
    "NullSafetyAuditLog",
    # model_alignment — abliteration toolkit + auditor
    "AlignmentProfile",
    "AlignmentResult",
    "IAlignmentToolkit",
    "IAlignmentAuditor",
    "InMemoryAlignmentToolkit",
    "RefuseAlignedPublishAuditor",
    "NullAlignmentToolkit",
    "NullAlignmentAuditor",
    # safety — personal-safety domain pack
    "IncidentSeverity",
    "Incident",
    "Hazard",
    "EmergencyContact",
    "ISafetyBoard",
    "InMemorySafetyBoard",
    "SafetyDomainContext",
    # safety_child — child-safety domain pack
    "TrustedAdult",
    "Geofence",
    "CheckIn",
    "IChildSafetyBoard",
    "InMemoryChildSafetyBoard",
    "SafetyChildDomainContext",
    # networking — transport abstraction (enums)
    "TransportKind",
    "ConnectivityState",
    "MessagePriority",
    "PeerRole",
    # networking — records
    "NetworkPayload",
    "NetworkContext",
    "PeerInfo",
    # networking — policy
    "INetworkPolicy",
    "DefaultNetworkPolicy",
    "NetworkPolicyBuilder",
    # networking — contracts
    "INetworkTransport",
    "IMeshNetwork",
    "IMessageChannel",
    "IConnectivityMonitor",
    "ITransportSelector",
    "IPeerDiscovery",
    # networking — working implementations
    "DefaultTransportSelector",
    "InMemoryWire",
    "InMemoryNetworkTransport",
    "InMemoryMeshNetwork",
    "IMessageSerializer",
    "JsonMessageSerializer",
    "TransportMessageChannel",
    "InMemoryConnectivityMonitor",
    "InboundChannel",
    # networking — AetherNet transport
    "AetherPeerKind",
    "AetherPeer",
    "AetherHopTelemetry",
    "AetherPacketSummary",
    "InMemoryAetherNetRegistry",
    "IAetherMeshEngine",
    "InMemoryAetherMeshEngine",
    "AetherNetworkTransport",
    "AetherPeerDiscovery",
    "AetherSyncChannel",
    # networking — Bluetooth transport
    "BluetoothConnectionState",
    "BluetoothEndpointDescriptor",
    "BluetoothCapabilityProfile",
    "BluetoothThroughputSample",
    "BluetoothCapabilityProfiles",
    "InMemoryBluetoothTransportRegistry",
    "IBleGattAdapter",
    "BluetoothNetworkTransport",
    "InMemoryBleGattAdapter",
    # networking — DTN transport
    "DtnPriority",
    "DtnBundle",
    "DtnCustodyRecord",
    "InMemoryDtnBundleStore",
    "DtnSyncChannel",
    # networking — gRPC transport
    "GrpcChannelState",
    "GrpcChannelDescriptor",
    "GrpcRetryPolicy",
    "GrpcCallSummary",
    "GrpcRetryPolicies",
    "InMemoryGrpcCallMetrics",
    "IGrpcChannel",
    "InMemoryGrpcChannel",
    "GrpcNetworkTransport",
    "GrpcSendNotSupportedError",
    # networking — HTTP transport
    "HttpStatusFamily",
    "HttpEndpointDescriptor",
    "HttpRequestSummary",
    "HttpCacheKey",
    "InMemoryHttpRequestMetrics",
    "IHttpMessageSender",
    "HttpNetworkTransport",
    "InMemoryHttpMessageSender",
    "HttpRequestException",
    "HttpTransientError",
    "HttpRequestFailedError",
    # networking — MQTT transport
    "MqttQos",
    "MqttTopicDescriptor",
    "MqttRetainedMessage",
    "MqttClientDescriptor",
    "InMemoryMqttBroker",
    "IMqttClient",
    "MqttNetworkTransport",
    "InMemoryMqttClient",
    # networking — NearLink transport
    "NearLinkPairingState",
    "NearLinkPowerProfile",
    "NearLinkDevice",
    "NearLinkSession",
    "NearLinkThroughputSample",
    "InMemoryNearLinkRegistry",
    "INearLinkAdapter",
    "NearLinkTransport",
    "InMemoryNearLinkAdapter",
    # networking — TCP transport
    "TcpConnectionState",
    "TcpEndpointDescriptor",
    "TcpThroughputSample",
    "TcpKnownPorts",
    "InMemoryTcpConnectionRegistry",
    "TcpStreamClosedError",
    "ITcpStream",
    "TcpNetworkTransport",
    "InMemoryTcpStream",
    # networking — WebSocket transport
    "WebSocketLinkState",
    "WebSocketMessageType",
    "WebSocketEndpointDescriptor",
    "WebSocketFrameSummary",
    "InMemoryWebSocketSessionRegistry",
    "WebSocketReceiveResult",
    "IWebSocketConnection",
    "WebSocketTransport",
    "InMemoryWebSocketConnection",
    # networking — WiFi transport
    "BROADCAST_ADDRESS",
    "UdpReceiveResult",
    "InMemoryUdpBus",
    "IUdpSocket",
    "InMemoryUdpSocket",
    "WiFiNetworkTransport",
    "WiFiPeerDiscovery",
    # vision — CircleAI.Vision primitives + records
    "BoundingBox",
    "LandmarkPoint",
    "DetectedFace",
    "FaceEmbedding",
    "LivenessResult",
    "DocumentField",
    "DocumentVerificationResult",
    "PlateRecognitionResult",
    "BluetoothAnomaly",
    # vision — contracts + camera capture
    "VideoPixelFormat",
    "VideoFrame",
    "IVideoCapture",
    "IComputerVisionRuntime",
    "IFaceDetector",
    "IFaceEmbedder",
    "IFaceLivenessDetector",
    "IDocumentVerifier",
    "IPlateRecognizer",
    "IBluetoothAnomalyDetector",
    "BluetoothAnomalyHandler",
    "IVisionDisposable",
    # vision — null implementations
    "NullVideoCapture",
    "NullComputerVisionRuntime",
    "NullFaceDetector",
    "NullFaceEmbedder",
    "NullFaceLivenessDetector",
    "NullDocumentVerifier",
    "NullPlateRecognizer",
    "NullBluetoothAnomalyDetector",
    # vision — ONNX implementations + injected seams
    "OnnxFaceDetector",
    "OnnxFaceDetectorOptions",
    "IFaceDetectorModelRunner",
    "FaceDetectorModelOutput",
    "OnnxFaceEmbedder",
    "OnnxFaceEmbedderOptions",
    "IFaceEmbedderModelRunner",
    "OnnxPlateRecognizer",
    "OnnxPlateRecognizerOptions",
    "IPlateModelRunner",
    "PlateModelOutput",
    # vision.cloud — CircleAI.Vision.Cloud image generation
    "ImageGenerationRequest",
    "ImageArtifact",
    "IImageGenerator",
    "NullImageGenerator",
    "OpenAiImageOptions",
    "StabilityImageOptions",
    "OpenAiImageGenerator",
    "StabilityImageGenerator",
    "ImageGeneratorFallbackChain",
    "ImageHttpRequest",
    "ImageHttpResponse",
    "IImageHttpTransport",
    "InMemoryImageHttpTransport",
    # video — CircleAI.Video primitives + records
    "StyleId",
    "VideoResolution",
    "StyleReferenceFrame",
    "StyleAttribution",
    "StyleReference",
    "AudioTrack",
    "VideoGenerationRequest",
    "VideoGenerationResult",
    "StyleScriptRequest",
    "StyleScriptResult",
    # video — contracts
    "IVideoGenerator",
    "IStyleScript",
    "IStyleReference",
    # video — implementations
    "NullVideoGenerator",
    "NullStyleScript",
    "InMemoryStyleReference",
]
