# security.py
#
# Python port of Circle.AI.Security portable types.
#
# Covers:
#   ThreatVector  — classification of locally-detected runtime anomalies
#   AnomalySignal — immutable signal carried from detection site to watchdog
#
# AnomalySignal is the PORTABLE SCHEMA only — the watchdog implementation
# (ISecurityWatchdog, SecurityResponse, SecurityCheckpoint) remains host-side
# in C#. Language ports carry the signal contract so cross-language detection
# sites can emit signals that interop with the C# orchestration layer.
#
# CRITICAL: ThreatVector ordinals must stay in sync with
# fixtures/anomaly_signal_schema.json. New values are appended at the end.

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import IntEnum
from typing import Dict, Optional
from uuid import UUID, uuid4


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


# ---------------------------------------------------------------------------
# ThreatVector
# ---------------------------------------------------------------------------

class ThreatVector(IntEnum):
    """Classification of a locally-detected runtime threat or anomaly.

    Ordinals are STABLE across language ports — never reorder existing
    values. Add new values at the end.
    """

    # Unexpected change in a runtime data structure's layout or content —
    # possible memory injection or buffer corruption.
    MEMORY_ANOMALY = 0

    # Execution flow deviated from the expected call graph —
    # possible ROP/JOP chain or code-reuse attack.
    CONTROL_FLOW_DRIFT = 1

    # A module or user session attempted to acquire capabilities
    # it is not authorised to hold.
    PRIVILEGE_ESCALATION = 2

    # A biometric authentication attempt was detected as a spoofing or
    # replay attack against the UHID profile.
    BIOMETRIC_SPOOF_ATTEMPT = 3

    # An attacker appears to be attempting lateral movement from a
    # compromised mesh node into the local execution namespace.
    NETWORK_PIVOT = 4

    # The AffectState or another core state vector was mutated by an
    # unexpected code path outside the trusted companion pipeline.
    STATE_CORRUPTION = 5

    # A software patch generated by an agent loop failed the BugHunter
    # quality gate — possible malicious or incorrect code generation.
    AGENT_PATCH_REJECTED = 6

    # Catch-all for anomalies that do not map to a specific vector.
    UNKNOWN = 7


# ---------------------------------------------------------------------------
# AnomalySignal
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class AnomalySignal:
    """An immutable record describing a locally-detected runtime anomaly.

    Created at the detection site (e.g. the companion pipeline, the biometric
    verifier, or an agent patch gate) and consumed by the host-side
    ``ISecurityWatchdog.OnAnomalyDetectedAsync`` handler.

    Use :py:meth:`create` to construct — it stamps a fresh UUID, the current
    UTC timestamp, and clamps ``confidence`` to ``[0.0, 1.0]``.
    """

    # Unique identifier for this signal instance.
    id: UUID

    # Classification of the detected threat.
    vector: ThreatVector

    # Confidence that this is a genuine threat, in [0.0, 1.0].
    # 1.0 = definitive; 0.0 = speculative.
    confidence: float

    # The module or subsystem where the anomaly was detected
    # (e.g. "Circle.AI.Companion", "Circle.AI.Identity").
    affected_module: str

    # Human-readable description of the anomaly.
    description: str

    # Optional structured evidence attached by the detection site.
    # Keys are evidence labels; values are serialised data or hashes.
    evidence: Dict[str, str] = field(default_factory=dict)

    # UTC timestamp of detection.
    detected_at: datetime = field(default_factory=_utc_now)

    @classmethod
    def create(
        cls,
        vector: ThreatVector,
        confidence: float,
        affected_module: str,
        description: str,
        evidence: Optional[Dict[str, str]] = None,
    ) -> "AnomalySignal":
        """Create an :class:`AnomalySignal` with a new UUID and current UTC time.

        Confidence is clamped to ``[0.0, 1.0]``.
        """
        return cls(
            id=uuid4(),
            vector=vector,
            confidence=max(0.0, min(1.0, confidence)),
            affected_module=affected_module,
            description=description,
            evidence=dict(evidence) if evidence else {},
            detected_at=_utc_now(),
        )
