//! The verticals.
//!
//! GENERATED by `rust/tools/gen_domains_rs.py` from the shared domain
//! table in `python/tools/gen_domains.py` - one table, three languages,
//! so a refusal reworded once is reworded everywhere.

pub mod accessibility;
pub mod agriculture;
pub mod beauty;
pub mod business;
pub mod civic;
pub mod commerce;
pub mod commerce_accounting;
pub mod commerce_finance;
pub mod commerce_payfast;
pub mod commerce_xero;
pub mod community;
pub mod construction;
pub mod creative;
pub mod education;
pub mod elderly;
pub mod energy;
pub mod faith;
pub mod family;
pub mod fitness;
pub mod food;
pub mod gaming;
pub mod hr;
pub mod healthcare;
pub mod home;
pub mod hospitality;
pub mod kids;
pub mod legal;
pub mod logistics;
pub mod parenting;
pub mod personal_finance;
pub mod personal_health;
pub mod personal_mental;
pub mod pets;
pub mod real_estate;
pub mod relationships;
pub mod retail;
pub mod safety;
pub mod safety_child;
pub mod social;
pub mod sports;
pub mod tourism;
pub mod travel;
pub mod wearable;
