// ThreatVector.cs
//
// Classification of locally-detected runtime anomalies.
//
// Distinct from PeerSecurityEventKind (which classifies external peer events).
// ThreatVector describes threats observed within the LOCAL process:
//   memory layout deviations, control-flow drift, privilege probes,
//   biometric spoofing attempts, and mesh-level pivoting.
//
// Used by AnomalySignal, SecurityResponse, and ISecurityWatchdog.

namespace CircleAI.Security;

/// <summary>
/// Classification of a locally-detected runtime threat or anomaly.
/// Differs from <see cref="PeerSecurityEventKind"/> which classifies
/// external peer events; <see cref="ThreatVector"/> classifies threats
/// observed in the LOCAL execution environment.
/// </summary>
public enum ThreatVector
{
    /// <summary>
    /// Unexpected change in a runtime data structure's layout or content —
    /// possible memory injection or buffer corruption.
    /// </summary>
    MemoryAnomaly,

    /// <summary>
    /// Execution flow deviated from the expected call graph —
    /// possible ROP/JOP chain or code-reuse attack.
    /// </summary>
    ControlFlowDrift,

    /// <summary>
    /// A module or user session attempted to acquire capabilities
    /// it is not authorised to hold.
    /// </summary>
    PrivilegeEscalation,

    /// <summary>
    /// A biometric authentication attempt was detected as a spoofing or
    /// replay attack against the <c>UHID</c> profile.
    /// </summary>
    BiometricSpoofAttempt,

    /// <summary>
    /// An attacker appears to be attempting lateral movement from a
    /// compromised mesh node into the local execution namespace.
    /// </summary>
    NetworkPivot,

    /// <summary>
    /// The AffectState or another core state vector was mutated by an
    /// unexpected code path outside the trusted companion pipeline.
    /// </summary>
    StateCorruption,

    /// <summary>
    /// A software patch generated by an agent loop failed the BugHunter
    /// quality gate — possible malicious or incorrect code generation.
    /// </summary>
    AgentPatchRejected,

    /// <summary>
    /// Catch-all for anomalies that do not map to a specific vector.
    /// </summary>
    Unknown,
}
