# threat_vector.py
#
# Port of CircleAI.Security.ThreatVector (C# — the EXACT spec).
#
# Classification of locally-detected runtime anomalies. Distinct from
# PeerSecurityEventKind (which classifies external peer events); ThreatVector
# describes threats observed within the LOCAL process: memory layout
# deviations, control-flow drift, privilege probes, biometric spoofing
# attempts, and mesh-level pivoting.
#
# Used by AnomalySignal, SecurityResponse, and ISecurityWatchdog.
#
# CRITICAL: ThreatVector ordinals must stay in sync with
# fixtures/anomaly_signal_schema.json. New values are appended at the end.

from __future__ import annotations

from enum import IntEnum


class ThreatVector(IntEnum):
    """Classification of a locally-detected runtime threat or anomaly.

    Differs from :class:`PeerSecurityEventKind` which classifies external peer
    events; ``ThreatVector`` classifies threats observed in the LOCAL execution
    environment.

    Ordinals are STABLE across language ports — never reorder existing values.
    Add new values at the end.
    """

    # Unexpected change in a runtime data structure's layout or content —
    # possible memory injection or buffer corruption.
    MEMORY_ANOMALY = 0

    # Execution flow deviated from the expected call graph —
    # possible ROP/JOP chain or code-reuse attack.
    CONTROL_FLOW_DRIFT = 1

    # A module or user session attempted to acquire capabilities
    # it is not authorised to hold.
    PRIVILEGE_ESCALATION = 2

    # A biometric authentication attempt was detected as a spoofing or
    # replay attack against the UHID profile.
    BIOMETRIC_SPOOF_ATTEMPT = 3

    # An attacker appears to be attempting lateral movement from a
    # compromised mesh node into the local execution namespace.
    NETWORK_PIVOT = 4

    # The AffectState or another core state vector was mutated by an
    # unexpected code path outside the trusted companion pipeline.
    STATE_CORRUPTION = 5

    # A software patch generated by an agent loop failed the BugHunter
    # quality gate — possible malicious or incorrect code generation.
    AGENT_PATCH_REJECTED = 6

    # Catch-all for anomalies that do not map to a specific vector.
    UNKNOWN = 7
