#!/usr/bin/env python3
"""Writes the HarmonyOS package barrel.

The barrel is generated rather than hand-kept for the same reason the modules
are: a hand-written list of four hundred exports goes stale the first time a
module is added, and a module missing from the barrel is a module the package
does not have as far as anyone consuming it is concerned.

WHAT IS EXPORTED: the top-level entry of each area, not every file. Exporting
every module would re-export the same names through several paths and produce
ambiguity at the point of use, which ArkTS reports as a conflict rather than
resolving.
"""
from __future__ import annotations

import io
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
ETS = os.path.join(ROOT, "harmonyos", "src", "main", "ets")

HEADER = """/**
 * Circle AI for HarmonyOS.
 *
 * GENERATED by `harmonyos/tools/gen_barrel.py`. The modules themselves are
 * ported from the TypeScript source by `harmonyos/tools/gen_arkts.py`; the
 * platform layer beneath them is hand-written ArkTS over `@ohos.*`.
 *
 * The platform layer comes FIRST: nothing else works until an ability has
 * called `bindPlatform`, and a consumer reading this file top to bottom should
 * meet that fact before anything that depends on it.
 */

export * from './platform';
"""


def main() -> None:
    entries: list[str] = []
    for name in sorted(os.listdir(ETS)):
        path = os.path.join(ETS, name)
        if os.path.isdir(path):
            # An area is exported through its own index if it has one; without
            # one there is no single name for the area and its files are reached
            # directly, which the barrel does not try to flatten.
            if os.path.exists(os.path.join(path, "index.ets")):
                entries.append("./%s/index" % name)
            continue
        if not name.endswith(".ets"):
            continue
        stem = name[: -len(".ets")]
        if stem in ("index", "platform"):
            continue
        entries.append("./%s" % stem)

    lines = [HEADER]
    for entry in entries:
        lines.append("export * from '%s';" % entry)
    io.open(
        os.path.join(ETS, "index.ets"), "w", encoding="utf-8", newline="\n"
    ).write("\n".join(lines) + "\n")
    print("barrel exports %d modules" % len(entries))


if __name__ == "__main__":
    main()
