// Faith: religious life.
//
// GENERATED by typescript/tools/gen_domains_ts.py from the table in
// python/tools/gen_domains.py. Do not edit this file; edit the table, which
// both this and the Python port are generated from - so a refusal cannot say
// one thing in one language and something else in another.

/** What the companion can do about religious life on this device. */
export interface FaithDomainContext {
  /** What it will speak to. */
  readonly topics: readonly string[];
  /**
   * The one thing it will not do, however it is asked. Held as a pair so the
   * refusal can be SHOWN with its reason - a refusal without a reason teaches
   * nobody what the assistant is for.
   */
  readonly refuses: string;
  readonly because: string;
  /**
   * Whether a host has wired anything real behind this. False means the adapter
   * answers from what it knows and says so, rather than pretending.
   */
  readonly isConnected: boolean;
}

export const faithDomainContext = (
  partial: Partial<FaithDomainContext> = {},
): FaithDomainContext =>
  Object.freeze({
    topics: Object.freeze(partial.topics ?? ["readings", "times", "calendars", "community"]),
    refuses: partial.refuses ?? "tell you what to believe",
    because: partial.because ?? "I can find the text and the times; the rest is not mine",
    isConnected: partial.isConnected ?? false,
  });

export const describeFaithContext = (context: FaithDomainContext): string =>
  `this can help with ${context.topics.join(", ")}; it will not ${context.refuses} - ${context.because}`;

/**
 * The companion's way into religious life.
 *
 * THE REFUSAL IS CHECKED BEFORE THE HANDLER RUNS, not after. Producing an
 * answer and then deciding it should not have been given has already produced
 * it, and on a device that streams, already shown it.
 */
export class FaithCompanionAdapter {
  constructor(
    readonly context: FaithDomainContext = faithDomainContext(),
    private readonly handle?: (request: string) => string,
    private readonly refusesWhen?: (request: string) => boolean,
  ) {}

  get topics(): readonly string[] {
    return this.context.topics;
  }

  /**
   * The refusal, or empty when there is none.
   *
   * A caller that ignores this gets no protection, which is why the adapter
   * itself calls it rather than leaving it to be remembered.
   */
  refusalFor(request: string): string {
    return this.refusesWhen?.(request)
      ? `I will not ${this.context.refuses} - ${this.context.because}`
      : "";
  }

  /**
   * Returns the text and whether it was a refusal.
   *
   * The flag is separate from the text so a caller can tell a refusal from an
   * answer without reading the words - a UI shows them differently, and a log
   * counts them differently.
   */
  respond(request: string): { text: string; wasRefused: boolean } {
    const refusal = this.refusalFor(request);
    if (refusal) return { text: refusal, wasRefused: true };
    if (!this.handle) {
      return {
        text: `this device has nothing wired up for ${this.context.topics.join(", ")} yet`,
        wasRefused: false,
      };
    }
    return { text: this.handle(request), wasRefused: false };
  }
}
