// Speech.Cloud: what a host chose to make available.
//
// GENERATED by typescript/tools/gen_domains_ts.py from the table in
// python/tools/gen_domains.py. Do not edit this file; edit the table, which
// both this and the Python port are generated from - so a refusal cannot say
// one thing in one language and something else in another.

/**
 * Registers what this module provides.
 *
 * A REGISTRATION POINT, not a factory. It records what a host chose to make
 * available and returns exactly that - so a component asking what it can use
 * gets an answer that reflects a decision somebody made, rather than whatever
 * happened to import.
 */
export class SpeechCloudServiceCollectionExtensions {
  private readonly registered = new Map<string, unknown>();

  /** Overwriting is deliberate and last-wins, so a host can replace a default
   * without having to remove it first. */
  add(name: string, service: unknown): SpeechCloudServiceCollectionExtensions {
    if (!name.trim()) throw new Error("a registration needs a name");
    this.registered.set(name, service);
    return this;
  }

  /** Undefined when absent, never a stand-in. A caller that gets a silent
   * placeholder cannot tell a working service from a missing one. */
  get(name: string): unknown {
    return this.registered.get(name);
  }

  names(): readonly string[] {
    return Object.freeze([...this.registered.keys()].sort());
  }

  build(): Readonly<Record<string, unknown>> {
    return Object.freeze(Object.fromEntries(this.registered));
  }
}
