"""Generates typescript/src/distribution/ubiquity-rails.ts.

READS THE SAME TABLE AS THE PYTHON GENERATOR. `python/tools/gen_rails.py` holds
the 44 constant rails, and this imports RAILS from it rather than restating
them. That is the whole point: these are DECISIONS - a regulator approval, a
cost ceiling, a list of corridors - and two ports carrying two copies of a
decision is how the copies diverge and nobody can say which one is the policy.

One table, two languages. A value changes in one place or it does not change.

WHAT IS NOT HERE: the twenty-nine rails that hold state or do work. Those are
hand-written in ubiquity-stateful.ts, because a generator that emitted a USSD
menu state machine would be a generator writing a program, and the program is
the interesting part.
"""

import io, os, sys

sys.path.insert(0, os.path.join("python", "tools"))
from gen_rails import RAILS  # noqa: E402 - the shared table is the point

HEADER = '''// The constant ubiquity rails - the decisions that turn a substrate into
// something a person can actually get, use and leave.
//
// GENERATED by typescript/tools/gen_rails_ts.py from the table in
// python/tools/gen_rails.py. Do not edit this file; edit the table, which both
// this and the Python port are generated from, so a decision cannot say one
// thing in one language and something else in another.
//
// WHY THESE ARE CONSTANTS AND NOT CONFIGURATION. Every one is a decision
// somebody has to be able to defend. A regulator approval that a config file
// could flip is not an approval; a cost ceiling a deployment can raise is not a
// ceiling. They are `readonly` and frozen for the same reason.
//
// MONEY IS IN MINOR UNITS, as integers. JavaScript has one number type and it
// is a double: 0.1 + 0.2 is not 0.3, and a total that does not match the sum of
// its parts is the bug that follows. Cents throughout, formatted at the edge.

'''


def to_camel(name):
    """`IOemPreloadCatalog` -> `oemPreloadCatalog` for the const instance.

    The interface keeps its name with the `I` dropped, which is TypeScript's own
    convention; the singleton instance beside it is camelCase, which is
    JavaScript's.
    """
    stem = name[1:] if name.startswith("I") and len(name) > 1 and name[1].isupper() else name
    return stem[0].lower() + stem[1:]


def ts_literal(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')
    if isinstance(value, (list, tuple)):
        return "[%s]" % ", ".join(ts_literal(v) for v in value)
    raise TypeError("no TypeScript literal for %r" % (value,))


def ts_type(value):
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, (int, float)):
        return "number"
    if isinstance(value, str):
        return "string"
    if isinstance(value, (list, tuple)):
        inner = {ts_type(v) for v in value} or {"string"}
        return "readonly %s[]" % (inner.pop() if len(inner) == 1 else "unknown")
    raise TypeError("no TypeScript type for %r" % (value,))


def doc_block(text, indent="  "):
    lines = [l.strip() for l in text.strip().split("\n")]
    body = "\n".join("%s * %s" % (indent, l) if l else "%s *" % indent for l in lines)
    return "%s/**\n%s\n%s */\n" % (indent, body, indent)


def emit():
    out = [HEADER]
    exported = []

    for rail in RAILS:
        name, kind, payload, doc = rail[0], rail[1], rail[2], rail[3]
        stem = name[1:] if name.startswith("I") else name
        instance = to_camel(name)

        if kind == "pair":
            props = payload
        else:
            props = [(payload[0], kind, payload[1])]

        # The interface. The `I` is dropped, which is what TypeScript does and
        # what the rest of this port does.
        out.append(doc_block(doc, "") if doc else "")
        out.append("export interface %s {\n" % stem)
        for prop, _kind, value in props:
            camel = prop if prop[0].islower() else prop[0].lower() + prop[1:]
            camel = "".join(
                part if i == 0 else part.capitalize()
                for i, part in enumerate(camel.split("_")))
            out.append("  readonly %s: %s;\n" % (camel, ts_type(value)))
        out.append("}\n\n")

        # The default. `as const` and Object.freeze together: `as const` is a
        # compile-time promise and freeze is what actually stops a caller
        # mutating a shared array at runtime. A decision that a caller can
        # push() onto is not a decision.
        out.append("/** The default. Frozen: a rail a caller can mutate is not a rail. */\n")
        out.append("export const %s: %s = Object.freeze({\n" % (instance, stem))
        for prop, _kind, value in props:
            camel = prop if prop[0].islower() else prop[0].lower() + prop[1:]
            camel = "".join(
                part if i == 0 else part.capitalize()
                for i, part in enumerate(camel.split("_")))
            literal = ts_literal(value)
            if isinstance(value, (list, tuple)):
                literal = "Object.freeze(%s)" % literal
            out.append("  %s: %s,\n" % (camel, literal))
        out.append("});\n\n")

        # The C# name kept as an alias, so a reader coming from the C# finds it
        # and the parity ruler can see it. An alias, not a second declaration -
        # there is one object.
        out.append("/** The C# spelling, kept so the two trees line up. */\n")
        out.append("export const Default%s = %s;\n" % (stem, instance))
        out.append("export type %s = %s;\n\n" % (name, stem))

        exported += [stem, instance, "Default" + stem, name]

    out.append("/** Every constant rail, for a screen that lists what was decided. */\n")
    out.append("export const allConstantRails = Object.freeze({\n")
    for rail in RAILS:
        stem = rail[0][1:] if rail[0].startswith("I") else rail[0]
        out.append("  %s: %s,\n" % (to_camel(rail[0]), to_camel(rail[0])))
    out.append("});\n")

    path = os.path.join("typescript", "src", "distribution", "ubiquity-rails.ts")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    io.open(path, "w", encoding="utf-8", newline="\n").write("".join(out))
    print("wrote ubiquity-rails.ts - %d rails, %d names" % (len(RAILS), len(exported)))


if __name__ == "__main__":
    emit()
