"""Generates the TypeScript vertical adapters and wiring modules.

READS THE SAME TABLE AS THE PYTHON GENERATOR. `python/tools/gen_domains.py`
holds the topics and, more importantly, the REFUSALS - the one thing each
vertical will not do however it is asked, in its own words. This imports that
table rather than restating it.

Two ports carrying two copies of a refusal is how healthcare declines to
diagnose in one language and not the other, and nobody notices until somebody
asks the wrong one.
"""

import io, os, sys

sys.path.insert(0, os.path.join("python", "tools"))
from gen_domains import DOMAINS, WIRING  # noqa: E402 - the shared table is the point

HEADER = '''// {title}
//
// GENERATED by typescript/tools/gen_domains_ts.py from the table in
// python/tools/gen_domains.py. Do not edit this file; edit the table, which
// both this and the Python port are generated from - so a refusal cannot say
// one thing in one language and something else in another.

'''

ADAPTER = '''/** What the companion can do about {purpose} on this device. */
export interface {name}DomainContext {{
  /** What it will speak to. */
  readonly topics: readonly string[];
  /**
   * The one thing it will not do, however it is asked. Held as a pair so the
   * refusal can be SHOWN with its reason - a refusal without a reason teaches
   * nobody what the assistant is for.
   */
  readonly refuses: string;
  readonly because: string;
  /**
   * Whether a host has wired anything real behind this. False means the adapter
   * answers from what it knows and says so, rather than pretending.
   */
  readonly isConnected: boolean;
}}

export const {instance}DomainContext = (
  partial: Partial<{name}DomainContext> = {{}},
): {name}DomainContext =>
  Object.freeze({{
    topics: Object.freeze(partial.topics ?? {topics}),
    refuses: partial.refuses ?? {refuses},
    because: partial.because ?? {because},
    isConnected: partial.isConnected ?? false,
  }});

export const describe{name}Context = (context: {name}DomainContext): string =>
  `this can help with ${{context.topics.join(", ")}}; it will not ${{context.refuses}} - ${{context.because}}`;

/**
 * {purpose_sentence}
 *
 * THE REFUSAL IS CHECKED BEFORE THE HANDLER RUNS, not after. Producing an
 * answer and then deciding it should not have been given has already produced
 * it, and on a device that streams, already shown it.
 */
export class {name}CompanionAdapter {{
  constructor(
    readonly context: {name}DomainContext = {instance}DomainContext(),
    private readonly handle?: (request: string) => string,
    private readonly refusesWhen?: (request: string) => boolean,
  ) {{}}

  get topics(): readonly string[] {{
    return this.context.topics;
  }}

  /**
   * The refusal, or empty when there is none.
   *
   * A caller that ignores this gets no protection, which is why the adapter
   * itself calls it rather than leaving it to be remembered.
   */
  refusalFor(request: string): string {{
    return this.refusesWhen?.(request)
      ? `I will not ${{this.context.refuses}} - ${{this.context.because}}`
      : "";
  }}

  /**
   * Returns the text and whether it was a refusal.
   *
   * The flag is separate from the text so a caller can tell a refusal from an
   * answer without reading the words - a UI shows them differently, and a log
   * counts them differently.
   */
  respond(request: string): {{ text: string; wasRefused: boolean }} {{
    const refusal = this.refusalFor(request);
    if (refusal) return {{ text: refusal, wasRefused: true }};
    if (!this.handle) {{
      return {{
        text: `this device has nothing wired up for ${{this.context.topics.join(", ")}} yet`,
        wasRefused: false,
      }};
    }}
    return {{ text: this.handle(request), wasRefused: false }};
  }}
}}
'''

WIRING_BODY = '''/**
 * Registers what this module provides.
 *
 * A REGISTRATION POINT, not a factory. It records what a host chose to make
 * available and returns exactly that - so a component asking what it can use
 * gets an answer that reflects a decision somebody made, rather than whatever
 * happened to import.
 */
export class {cls} {{
  private readonly registered = new Map<string, unknown>();

  /** Overwriting is deliberate and last-wins, so a host can replace a default
   * without having to remove it first. */
  add(name: string, service: unknown): {cls} {{
    if (!name.trim()) throw new Error("a registration needs a name");
    this.registered.set(name, service);
    return this;
  }}

  /** Undefined when absent, never a stand-in. A caller that gets a silent
   * placeholder cannot tell a working service from a missing one. */
  get(name: string): unknown {{
    return this.registered.get(name);
  }}

  names(): readonly string[] {{
    return Object.freeze([...this.registered.keys()].sort());
  }}

  build(): Readonly<Record<string, unknown>> {{
    return Object.freeze(Object.fromEntries(this.registered));
  }}
}}
'''


def ts_string(value):
    return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')


def ts_list(values):
    return "[%s]" % ", ".join(ts_string(v) for v in values)


def camel(name):
    return name[0].lower() + name[1:] if name else name


def main():
    root = os.path.join("typescript", "src", "domains")
    os.makedirs(root, exist_ok=True)
    written = 0

    for module, (suffix, purpose, topics, (refuses, because)) in sorted(DOMAINS.items()):
        name = module.replace(".", "")
        body = HEADER.format(title="%s: %s." % (module, purpose)) + ADAPTER.format(
            name=name,
            instance=camel(name),
            purpose=purpose,
            purpose_sentence="The companion's way into %s." % purpose,
            topics=ts_list(topics),
            refuses=ts_string(refuses),
            because=ts_string(because),
        )
        path = os.path.join(root, "%s.ts" % suffix.replace("_", "-"))
        io.open(path, "w", encoding="utf-8", newline="\n").write(body)
        written += 1

    for module, (suffix, cls) in sorted(WIRING.items()):
        body = HEADER.format(
            title="%s: what a host chose to make available." % module
        ) + WIRING_BODY.format(cls=cls)
        path = os.path.join(root, "%s.ts" % suffix.replace("_", "-"))
        io.open(path, "w", encoding="utf-8", newline="\n").write(body)
        written += 1

    print("wrote %d modules into %s" % (written, root))


if __name__ == "__main__":
    main()
