// Security.swift
//
// ThreatVector + AnomalySignal — the local-runtime security primitives.
//
// Detection sites (the companion pipeline, the biometric verifier, an agent
// patch gate, …) create an AnomalySignal and hand it to a security watchdog.
// The signal is conceptually IMMUTABLE — its struct fields are `let`-bound and
// confidence is clamped into [0, 1] at construction.
//
// Distinct from any peer-security event kind (which classifies external peer
// events); ThreatVector describes threats observed within the LOCAL process.
//
// Ordinals are STABLE across language ports — see
// fixtures/anomaly_signal_schema.json. Add new ThreatVector cases only at the
// end of the enum so existing wire-format payloads keep decoding correctly.

import Foundation

// MARK: - ThreatVector

/// Classification of a locally-detected runtime threat or anomaly.
///
/// Ordinals are stable across language ports; new values must be appended.
public enum ThreatVector: Int, Codable, Sendable {
    /// Unexpected change in a runtime data structure's layout or content —
    /// possible memory injection or buffer corruption.
    case memoryAnomaly         = 0

    /// Execution flow deviated from the expected call graph —
    /// possible ROP/JOP chain or code-reuse attack.
    case controlFlowDrift      = 1

    /// A module or user session attempted to acquire capabilities
    /// it is not authorised to hold.
    case privilegeEscalation   = 2

    /// A biometric authentication attempt was detected as a spoofing or
    /// replay attack against the UHID profile.
    case biometricSpoofAttempt = 3

    /// An attacker appears to be attempting lateral movement from a
    /// compromised mesh node into the local execution namespace.
    case networkPivot          = 4

    /// The AffectState or another core state vector was mutated by an
    /// unexpected code path outside the trusted companion pipeline.
    case stateCorruption       = 5

    /// A software patch generated by an agent loop failed the BugHunter
    /// quality gate — possible malicious or incorrect code generation.
    case agentPatchRejected    = 6

    /// Catch-all for anomalies that do not map to a specific vector.
    case unknown               = 7
}

// MARK: - AnomalySignal

/// An immutable record describing a locally-detected runtime anomaly.
/// Created at the detection site (e.g. the companion pipeline, the biometric
/// verifier, or an agent patch gate) and consumed by the host-side security
/// watchdog.
public struct AnomalySignal: Sendable, Identifiable {
    /// Unique identifier for this signal instance.
    public let id: UUID

    /// Classification of the detected threat.
    public let vector: ThreatVector

    /// Confidence that this is a genuine threat, in [0.0, 1.0].
    /// 1.0 = definitive; 0.0 = speculative.
    public let confidence: Float

    /// The module or subsystem where the anomaly was detected
    /// (e.g. "Circle.AI.Companion", "Circle.AI.Identity").
    public let affectedModule: String

    /// Human-readable description of the anomaly.
    public let description: String

    /// Optional structured evidence attached by the detection site.
    /// Keys are evidence labels; values are serialised data or hashes.
    public let evidence: [String: String]

    /// UTC timestamp of detection.
    public let detectedAt: Date

    /// Creates an `AnomalySignal` with a new UUID and the current UTC time.
    /// `confidence` is clamped into [0.0, 1.0].
    public static func create(
        vector: ThreatVector,
        confidence: Float,
        affectedModule: String,
        description: String,
        evidence: [String: String] = [:]
    ) -> AnomalySignal {
        AnomalySignal(
            id: UUID(),
            vector: vector,
            confidence: max(0, min(1, confidence)),
            affectedModule: affectedModule,
            description: description,
            evidence: evidence,
            detectedAt: Date()
        )
    }
}
