// Capabilities.cs
//
// GENERATED by tools/gen-services/gen_services.py. Do not edit by hand.
//
// WHAT THE APP CAN DO, DERIVED FROM WHAT IS ACTUALLY BUILT. The repository
// carries 165 projects and the app used to surface one of them - somebody with
// the whole source tree open could not have said it does agriculture, so a
// person holding the phone had no chance.
//
// The first version of this file was thirty-nine tiles written by hand: an
// opinion about what the app does rather than a description of it, overlapping
// the real module list only by accident. Now every project under src/ is
// classified exactly once - a service a person asks for, or plumbing the
// machine needs - and anything unclassified FAILS the generator instead of
// quietly not appearing.
//
// Every tile opens the conversation pointed at the thing. That is what makes
// breadth free: sixty tiles need sixty first sentences, not sixty screens, and
// it is how an assistant works - you ask it, you do not navigate to it.

namespace CircleAI.Samples.It;

/// <summary>One thing the app can help with.</summary>
/// <param name="Title">What it is, in the words somebody would use.</param>
/// <param name="Icon">A glyph, for scanning rather than reading.</param>
/// <param name="Opener">
/// What to ask when it is tapped. A FIRST SENTENCE, not a category: a tile
/// exists to get somebody past the blank page, and "Help me plan my money" is
/// a question the assistant can answer where "Money" is not.
/// </param>
/// <param name="Route">
/// A screen, where one genuinely exists. Only a handful do - the rest are
/// answered by asking, and forty screens for forty capabilities is how an
/// assistant becomes a menu system.
/// </param>
public sealed record Capability(string Title, string Icon, string Opener, string? Route = null);

/// <summary>A section of the grid.</summary>
public sealed record CapabilityGroup(string Title, Capability[] Items);

/// <summary>Everything the app can help with, grouped for a grid.</summary>
public static class Capabilities
{
    /// <summary>The groups, in the order they are shown.</summary>
    /// <remarks>
    /// ORDERED BY WHAT MATTERS ON A CHEAP PHONE HERE, not by what is most
    /// impressive: money and work first, because that is what somebody needs an
    /// assistant for when they cannot afford one. Enjoyment is last and is still
    /// there, because an assistant that only does chores is one people stop
    /// opening.
    /// </remarks>
    public static IReadOnlyList<CapabilityGroup> All { get; } =
    [
        new("Money",
        [
            // src/CircleAI.Career
            new("Your CV", "📄", "Help me build my CV", "career"),
            // src/CircleAI.HR
            new("Work rights", "📋", "I have a question about my job or my rights at work"),
            // src/CircleAI.Banking
            new("Banking", "🏦", "Help me understand my bank account"),
            // src/CircleAI.Personal.Finance
            new("Money", "💰", "Help me plan my money this month"),
            // src/CircleAI.Markets
            new("Markets", "📈", "Explain what is happening in the markets"),
        ]),

        new("Work and business",
        [
            // src/CircleAI.Commerce
            new("Buying and selling", "🛒", "Help me sell something"),
            // src/CircleAI.Commerce.Accounting
            new("Bookkeeping", "🧮", "Help me keep my books"),
            // src/CircleAI.Commerce.Finance
            new("Invoices", "🧾", "Help me write an invoice"),
            // src/CircleAI.Business
            new("My business", "💼", "Help me run my small business"),
            // src/CircleAI.BusinessOps
            new("Running it", "⚙", "Help me organise my business"),
            // src/CircleAI.AutonomousBiz
            new("Growing it", "🚀", "Help me grow my business"),
            // src/CircleAI.CRM
            new("Customers", "🤝", "Help me keep track of my customers"),
        ]),

        new("Trades and land",
        [
            // src/CircleAI.Retail
            new("Shop", "🏪", "Help me run my shop"),
            // src/CircleAI.Logistics
            new("Deliveries", "🚚", "Help me plan deliveries"),
            // src/CircleAI.Construction
            new("Building", "🏗", "Help me with a building job"),
            // src/CircleAI.Agriculture
            new("Farming", "🌱", "Help me with my crops or livestock"),
            // src/CircleAI.Hospitality
            new("Hosting", "🍴", "Help me run a place that feeds people"),
            // src/CircleAI.Beauty
            new("Hair and beauty", "💅", "Help me with my salon"),
        ]),

        new("Health",
        [
            // src/CircleAI.Healthcare
            new("Health", "❤", "I have a health question"),
            // src/CircleAI.Personal.Health
            new("My health", "🩺", "Help me keep track of my health"),
            // src/CircleAI.Personal.Mental
            new("How I feel", "🧠", "I want to talk about how I am feeling"),
            // src/CircleAI.Fitness
            new("Fitness", "🏃", "Help me get fitter"),
            // src/CircleAI.Food
            new("Food", "🍛", "Help me plan meals"),
            // src/CircleAI.Safety
            new("Staying safe", "🛡", "Help me stay safe"),
            // src/CircleAI.Elderly
            new("Older family", "🧓", "Help me care for an older relative"),
            // src/CircleAI.Pets
            new("Pets", "🐕", "I have a question about my pet"),
        ]),

        new("Family and home",
        [
            // src/CircleAI.Family
            new("Family", "👪", "Help me with something at home"),
            // src/CircleAI.Kids
            new("Children", "🧒", "Help me with my children"),
            // src/CircleAI.Parenting
            new("Parenting", "🍼", "I have a parenting question"),
            // src/CircleAI.Relationships
            new("Relationships", "💞", "I want to talk about a relationship"),
            // src/CircleAI.Home
            new("Home", "🏠", "Help me sort something out at home"),
            // src/CircleAI.Energy
            new("Electricity", "⚡", "Help me with electricity and load shedding"),
            // src/CircleAI.RealEstate
            new("Housing", "🔑", "I have a question about renting or housing"),
        ]),

        new("Learning",
        [
            // src/CircleAI.Education
            new("Study help", "📚", "Help me study"),
            // src/CircleAI.Languages
            new("Languages", "🌐", "Help me with a language", "languages"),
            // src/CircleAI.Languages.Translation
            new("Interpret", "🔤", "Interpret between two languages", "interpret"),
            // src/CircleAI.Research
            new("Research", "🔎", "Help me research something"),
            // src/CircleAI.CodeAgent
            new("Code", "💻", "Help me with some code"),
        ]),

        new("Making things",
        [
            // src/CircleAI.Documents
            new("Write something", "✍", "Help me write something"),
            // src/CircleAI.Presentations
            new("A presentation", "📊", "Help me make a presentation"),
            // src/CircleAI.Charts
            new("A chart", "📉", "Help me make a chart of some numbers"),
            // src/CircleAI.Visualization
            new("Show me", "🖼", "Draw me a picture of this"),
            // src/CircleAI.Vision
            new("Read a picture", "📷", "Look at a picture and tell me what it says", "chat"),
            // src/CircleAI.Search
            new("Look it up", "🔍", "Look something up for me"),
            // src/CircleAI.Creative
            new("Make something up", "✨", "Help me write something creative"),
        ]),

        new("Getting by",
        [
            // src/CircleAI.Legal
            new("Legal", "⚖", "I have a legal question"),
            // src/CircleAI.Civic
            new("Government", "🏛", "Help me deal with a government office"),
            // src/CircleAI.Community
            new("Community", "🤝", "Help me with something in my community"),
            // src/CircleAI.Faith
            new("Faith", "🕊", "I want to talk about my faith"),
            // src/CircleAI.Social
            new("People", "💬", "Help me write a message to somebody"),
            // src/CircleAI.Travel
            new("Travel", "🚌", "Help me plan a trip"),
            // src/CircleAI.Tourism
            new("Places to go", "🗺", "Tell me about a place"),
        ]),

        new("For enjoyment",
        [
            // src/CircleAI.Music
            new("Music", "🎵", "Talk to me about music"),
            // src/CircleAI.Sports
            new("Sport", "⚽", "Talk to me about sport"),
            // src/CircleAI.Media
            new("Watch and read", "📺", "Recommend me something to watch or read"),
            // src/CircleAI.Video
            new("Video", "🎬", "Help me with a video"),
            // src/CircleAI.Games
            new("Games", "🎲", "Play a game with me"),
            // src/CircleAI.Gaming
            new("Gaming", "🕹", "Talk to me about gaming"),
        ]),

    ];
}
