// BrandMarkAssetTests.cs
//
// The mark is drawn in five places. These tests keep them one shape.
//
//   MarkView.OnDraw                      native Android head, live on a Canvas
//   BrandMark.razor                      shared Razor UI, SVG plus CSS
//   ic_launcher_foreground.xml           native head's launcher icon
//   Resources/AppIcon/appiconfg.svg      MAUI head's launcher foreground
//   Resources/Splash/splash.svg          MAUI head's splash
//
// WHY THIS EARNS ITS PLACE. Two of those had already diverged into different
// logos before anybody noticed: the launcher icon was a half circle open on the
// RIGHT with three solid arcs, while the live mark opens at the TOP with three
// that fade 235/150/80. Nothing caught it because an icon and a home screen are
// never on screen together, and a wrong logo throws no exception.
//
// The last three files are generated by tools/brand-mark/gen_mark.py. These tests
// assert the SHIPPED bytes still match that geometry, so a hand edit fails here
// instead of shipping a second logo.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using Xunit;

namespace CircleAI.Tests;

public class BrandMarkAssetTests
{
    // The geometry, as MarkView.OnDraw states it.
    private const double RingR = 0.46, RingW = 0.11, ArcW = 0.085;
    private const double RingStart = -50.0, RingSweep = 280.0;
    private const double ArcStart = -34.0, ArcSweep = 68.0;
    private static readonly double[] ArcSpread = [0.16, 0.32, 0.48];
    private static readonly double[] IdleAlpha = [235, 150, 80];

    /// <summary>The repository root, found by walking up to the solution file.</summary>
    private static string Repo()
    {
        var dir = AppContext.BaseDirectory;
        while (dir is not null && !File.Exists(Path.Combine(dir, "CircleAI.sln")))
            dir = Path.GetDirectoryName(dir);
        Assert.NotNull(dir);
        return dir!;
    }

    private static string Asset(params string[] parts)
        => Path.Combine([Repo(), .. parts]);

    private sealed record Stroke(double Radius, double Start, double Sweep, double Width, double Opacity);

    /// <summary>
    /// Every arc in a file, recovered from its own pathData rather than recomputed.
    /// </summary>
    /// <remarks>
    /// THE INVERSION IS THE TEST. Re-deriving the endpoints from the same constants
    /// would agree with itself no matter what the file says. Solving each arc back
    /// to a centre and a sweep - the SVG 1.1 F.6.5 conversion, run backwards - is
    /// what catches a flipped large-arc or sweep flag, which does not fail a build
    /// and silently mirrors the mark.
    /// </remarks>
    private static List<Stroke> StrokesIn(string text, double canvas)
    {
        var centre = canvas / 2;
        var found = new List<Stroke>();

        // Matches both spellings: android:pathData="..." and SVG d="...".
        var arcs = Regex.Matches(
            text,
            @"(?:pathData|\bd)=""M\s*([\d.]+)\s+([\d.]+)\s+A\s*([\d.]+)\s+[\d.]+\s+0\s+(\d)\s+(\d)\s+([\d.]+)\s+([\d.]+)""");

        // Widths and opacities, in document order, in either dialect.
        var widths = Regex.Matches(text, @"(?:android:strokeWidth|stroke-width)=""([\d.]+)""")
            .Select(m => double.Parse(m.Groups[1].Value, CultureInfo.InvariantCulture)).ToList();
        var alphas = Regex.Matches(text, @"(?:android:strokeAlpha|stroke-opacity)=""([\d.]+)""")
            .Select(m => double.Parse(m.Groups[1].Value, CultureInfo.InvariantCulture)).ToList();

        for (var i = 0; i < arcs.Count; i++)
        {
            var g = arcs[i].Groups;
            double D(int n) => double.Parse(g[n].Value, CultureInfo.InvariantCulture);
            double x0 = D(1), y0 = D(2), r = D(3), x1 = D(6), y1 = D(7);
            var sweepFlag = int.Parse(g[5].Value, CultureInfo.InvariantCulture);

            var a0 = Math.Atan2(y0 - centre, x0 - centre) * 180 / Math.PI;
            var a1 = Math.Atan2(y1 - centre, x1 - centre) * 180 / Math.PI;
            var sweep = a1 - a0;
            if (sweepFlag == 1 && sweep < 0) sweep += 360;
            if (sweepFlag == 0 && sweep > 0) sweep -= 360;

            // The recovered centre must be the canvas centre, or the arc is not
            // concentric with the rest of the mark.
            var cx = x0 - r * Math.Cos(a0 * Math.PI / 180);
            var cy = y0 - r * Math.Sin(a0 * Math.PI / 180);
            Assert.True(Math.Abs(cx - centre) < 0.05 && Math.Abs(cy - centre) < 0.05,
                $"arc {i} is centred on ({cx:F2},{cy:F2}), not ({centre:F2},{centre:F2})");

            // strokeAlpha is omitted when it is 1, so the opacity list is shorter
            // than the arc list and lines up from the END.
            var opacity = i == 0 && alphas.Count == arcs.Count - 1
                ? 1.0
                : alphas.Count == arcs.Count ? alphas[i] : alphas[i - 1];

            found.Add(new Stroke(r, a0, sweep, widths[i], opacity));
        }
        return found;
    }

    private static void AssertMarkShape(string path, double canvas)
    {
        Assert.True(File.Exists(path), $"missing generated asset: {path}");
        var strokes = StrokesIn(File.ReadAllText(path), canvas);

        Assert.Equal(4, strokes.Count);      // one ring, three arcs

        var ring = strokes[0];
        // r is whatever fits the canvas; the RATIOS are the identity of the mark.
        var r = ring.Radius / RingR;

        Assert.Equal(RingStart, ring.Start, 1);
        Assert.Equal(RingSweep, ring.Sweep, 1);
        Assert.Equal(RingW * r, ring.Width, 2);

        for (var i = 0; i < 3; i++)
        {
            var arc = strokes[i + 1];
            Assert.Equal((RingR + ArcSpread[i]) * r, arc.Radius, 1);
            Assert.Equal(ArcStart, arc.Start, 1);
            Assert.Equal(ArcSweep, arc.Sweep, 1);
            Assert.Equal(ArcW * r, arc.Width, 2);
            Assert.Equal(IdleAlpha[i] / 255.0, arc.Opacity, 2);
        }
    }

    [Fact]
    public void The_native_launcher_icon_is_the_live_mark()
        => AssertMarkShape(
            Asset("samples", "CircleAI.Samples.It.Android", "Resources", "drawable",
                  "ic_launcher_foreground.xml"), canvas: 108);

    [Fact]
    public void The_maui_launcher_foreground_is_the_live_mark()
        => AssertMarkShape(
            Asset("samples", "CircleAI.Samples.It.Hybrid", "CircleAI.Samples.It.App",
                  "Resources", "AppIcon", "appiconfg.svg"), canvas: 456);

    [Fact]
    public void The_splash_is_the_live_mark()
        => AssertMarkShape(
            Asset("samples", "CircleAI.Samples.It.Hybrid", "CircleAI.Samples.It.App",
                  "Resources", "Splash", "splash.svg"), canvas: 456);

    [Fact]
    public void The_ring_opens_at_the_top_not_the_right()
    {
        // The specific regression. -50 sweeping 280 clockwise covers -50..230,
        // leaving 230..310 open, and that straddles 270 - which is 12 o'clock in
        // both canvas and SVG angles, where y grows downward. The old hand-drawn
        // icon was a 180-degree arc open at 0 degrees, on the right.
        var gapCentre = ((RingStart + RingSweep) + (RingStart + 360)) / 2;
        Assert.Equal(270.0, gapCentre, 1);
        Assert.Equal(80.0, 360 - RingSweep, 1);
    }

    [Fact]
    public void The_splash_wears_the_apps_own_page_colour()
    {
        // #121A21 is Shade(#2c3e50, 0.42) - Ui.Bg on the native head - and it is
        // what a screenshot of the running app measures. The splash exists to be
        // the bridge INTO the app: a splash in any other colour is a visible jump,
        // and the default it replaced was #FAFAFA flashing white into a dark app.
        var splash = File.ReadAllText(
            Asset("samples", "CircleAI.Samples.It.Hybrid", "CircleAI.Samples.It.App",
                  "Resources", "Splash", "splash.svg"));
        Assert.Contains("#121A21", splash, StringComparison.OrdinalIgnoreCase);

        var csproj = File.ReadAllText(
            Asset("samples", "CircleAI.Samples.It.Hybrid", "CircleAI.Samples.It.App",
                  "CircleAI.Samples.It.App.csproj"));
        // MauiSplashScreen's Color is what actually paints the window; the svg's
        // own rect only shows if that is wrong. Both must say the same thing.
        var declared = Regex.Match(csproj,
            @"MauiSplashScreen[^>]*Color=""(#[0-9A-Fa-f]{6})""", RegexOptions.Singleline);
        Assert.True(declared.Success, "MauiSplashScreen declares no Color");
        Assert.Equal("#121A21", declared.Groups[1].Value, ignoreCase: true);
    }

    [Fact]
    public void The_maui_head_declares_a_splash_at_all()
    {
        // The whole point of the exercise. The native head has no splash because
        // it declares no theme, so Android draws its own #FAFAFA preview window;
        // a MAUI head without MauiSplashScreen would reproduce that exactly.
        var csproj = File.ReadAllText(
            Asset("samples", "CircleAI.Samples.It.Hybrid", "CircleAI.Samples.It.App",
                  "CircleAI.Samples.It.App.csproj"));
        Assert.Contains("MauiSplashScreen", csproj, StringComparison.Ordinal);
        Assert.Contains("MauiIcon", csproj, StringComparison.Ordinal);
    }
}
