// ServiceCoverageTests.cs
//
// The app must know what the repository can do.
//
// WHY THIS EARNS ITS PLACE. The repository carries 165 projects and the sample
// surfaced ONE of them. Somebody with the whole source tree open could not have
// said the thing does agriculture; a person holding the phone had no chance. The
// screen literally named "What it can do" answered with Talking, Listening and
// Seeing - modalities, not capabilities - so it was a download manager wearing
// the name of the question.
//
// The list is generated now, and these tests are what keep it honest: a module
// added next month either becomes a service somebody can find, or fails here.
// Silently not appearing is the one outcome that is not allowed, because that is
// the failure nobody notices for a year.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using Xunit;

namespace CircleAI.Tests;

public class ServiceCoverageTests
{
    private static string Repo()
    {
        var dir = AppContext.BaseDirectory;
        while (dir is not null && !File.Exists(Path.Combine(dir, "CircleAI.sln")))
            dir = Path.GetDirectoryName(dir);
        Assert.NotNull(dir);
        return dir!;
    }

    private static string GeneratorPath()
        => Path.Combine(Repo(), "tools", "gen-services", "gen_services.py");

    private static string CapabilitiesPath()
        => Path.Combine(Repo(), "samples", "CircleAI.Samples.It.Contracts", "Capabilities.cs");

    /// <summary>Every project directory under src/, by short name.</summary>
    private static IReadOnlyList<string> Modules()
        => Directory.GetDirectories(Path.Combine(Repo(), "src"), "CircleAI.*")
            .Select(d => Path.GetFileName(d)!["CircleAI.".Length..])
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

    [Fact]
    public void There_are_modules_to_cover()
    {
        // A guard on the guard: if src/ moved, the rest would pass vacuously.
        Assert.True(Modules().Count > 100, "expected the full module tree");
    }

    [Fact]
    public void Every_module_is_either_a_service_or_declared_plumbing()
    {
        // THE ONE THAT MATTERS. A module that is neither is a capability the app
        // does not know it has - which is precisely how 165 projects became one
        // visible feature.
        var generator = File.ReadAllText(GeneratorPath());

        var infrastructure = Regex.Match(generator, @"INFRASTRUCTURE = \((.*?)\n\)", RegexOptions.Singleline)
            .Groups[1].Value;
        var infra = Regex.Matches(infrastructure, @"""([^""]+)""").Select(m => m.Groups[1].Value).ToList();
        Assert.NotEmpty(infra);

        var services = Regex.Matches(generator, @"^\s{4}""([\w.]+)"":", RegexOptions.Multiline)
            .Select(m => m.Groups[1].Value).ToHashSet(StringComparer.Ordinal);
        Assert.NotEmpty(services);

        var unclassified = Modules()
            .Where(m => !services.Contains(m))
            .Where(m => !infra.Any(i => m == i || m.StartsWith(i + ".", StringComparison.Ordinal)))
            .ToList();

        Assert.True(unclassified.Count == 0,
            "These modules are neither offered to a person nor declared plumbing, so the "
            + "app cannot say it does them:\n  " + string.Join("\n  ", unclassified));
    }

    [Fact]
    public void The_generated_list_is_current()
    {
        // Hand-editing the generated file is how it drifted from the modules the
        // first time. The generator is the source; this catches an edit that went
        // to the output instead.
        var generated = File.ReadAllText(CapabilitiesPath());
        Assert.Contains("GENERATED by tools/gen-services/gen_services.py", generated,
            StringComparison.Ordinal);

        // Every tile carries the module it came from, so a reader can check the
        // claim rather than trust it.
        var tiles = Regex.Matches(generated, @"^\s+new\(""", RegexOptions.Multiline).Count;
        var provenance = Regex.Matches(generated, @"^\s+// src/CircleAI\.", RegexOptions.Multiline).Count;
        Assert.True(provenance > 0, "no tile says which module it came from");

        // tiles counts groups as well as capabilities, so provenance is the lower
        // bound: every capability is attributed.
        Assert.True(tiles >= provenance, $"{tiles} entries, {provenance} attributed");
    }

    [Fact]
    public void The_app_offers_substantially_more_than_it_used_to()
    {
        // It surfaced ONE domain. This is not a target to game - it is a floor
        // that fails loudly if somebody trims the grid back to a handful.
        var generated = File.ReadAllText(CapabilitiesPath());
        var capabilities = Regex.Matches(generated, @"^\s+// src/CircleAI\.", RegexOptions.Multiline).Count;

        Assert.True(capabilities >= 40,
            $"only {capabilities} capabilities are offered; the repository has 165 modules "
            + "and the app is meant to say so");
    }
}
