// domain_adapters.go
//
// GENERATED by go/tools/gen_domains.py. Do not edit by hand; edit the table.
//
// Two things per vertical: a DOMAIN CONTEXT, which is one system-prompt snippet
// saying what the domain is and what the assistant must not do in it, and a
// COMPANION ADAPTER, which decorates an existing session with that snippet.
//
// THE ADAPTER DECORATES, IT DOES NOT REPLACE. It adds no capability the session
// did not already have, so a domain cannot quietly acquire the ability to send
// mail or spend money by being a domain.
//
// The refusals are the point. Most of these snippets exist to say what the
// assistant will NOT do in that domain — diagnose, dose, move money, post,
// book, or decide somebody's employment — and a domain adapter with no refusal
// is one where nothing was thought through rather than one where nothing was
// needed.

package circleai

// DomainContext is one domain's system-prompt snippet.
type DomainContext interface {
	DomainID() string
	SystemPromptSnippet() string
}

// staticDomainContext carries a snippet that is declared elsewhere.
type staticDomainContext struct {
	id      string
	snippet string
}

// DomainID implements DomainContext.
func (c staticDomainContext) DomainID() string { return c.id }

// SystemPromptSnippet implements DomainContext.
func (c staticDomainContext) SystemPromptSnippet() string { return c.snippet }

// DomainCompanionAdapter decorates a companion session with a domain snippet.
//
// `inner` is BORROWED and never owned: the session outlives any one domain
// adapter, and a domain that closed it would take the assistant down with it.
type DomainCompanionAdapter struct {
	inner   any
	context DomainContext
}

// NewDomainCompanionAdapter returns an adapter over a session.
func NewDomainCompanionAdapter(inner any, context DomainContext) *DomainCompanionAdapter {
	return &DomainCompanionAdapter{inner: inner, context: context}
}

// DomainID returns which domain this adapter is for.
func (a *DomainCompanionAdapter) DomainID() string {
	if a.context == nil {
		return ""
	}
	return a.context.DomainID()
}

// Enrich prefixes the domain snippet to a message.
func (a *DomainCompanionAdapter) Enrich(message string) string {
	if a.context == nil {
		return message
	}
	return a.context.SystemPromptSnippet() + "\n\n" + message
}

// Inner returns the wrapped session.
func (a *DomainCompanionAdapter) Inner() any { return a.inner }

// AccessibilityDomainContext is the Accessibility domain's prompt snippet.
type AccessibilityDomainContext struct{}

// DomainID implements DomainContext.
func (AccessibilityDomainContext) DomainID() string { return "Accessibility" }

// SystemPromptSnippet implements DomainContext.
func (AccessibilityDomainContext) SystemPromptSnippet() string {
	return "You are helping somebody use this device the way it works for them. Never describe a person's needs as a deficiency, and never record a diagnosis."
}

// AccessibilityCompanionAdapter is a companion session scoped to the Accessibility domain.
type AccessibilityCompanionAdapter struct{ *DomainCompanionAdapter }

// NewAccessibilityCompanionAdapter wraps a session for the Accessibility domain.
func NewAccessibilityCompanionAdapter(inner any) *AccessibilityCompanionAdapter {
	return &AccessibilityCompanionAdapter{NewDomainCompanionAdapter(inner, AccessibilityDomainContext{})}
}

// AgricultureDomainContext is the Agriculture domain's prompt snippet.
type AgricultureDomainContext struct{}

// DomainID implements DomainContext.
func (AgricultureDomainContext) DomainID() string { return "Agriculture" }

// SystemPromptSnippet implements DomainContext.
func (AgricultureDomainContext) SystemPromptSnippet() string {
	return "You are helping with growing, livestock and land. Do not give chemical dosing advice; name the product and say to read its label."
}

// AgricultureCompanionAdapter is a companion session scoped to the Agriculture domain.
type AgricultureCompanionAdapter struct{ *DomainCompanionAdapter }

// NewAgricultureCompanionAdapter wraps a session for the Agriculture domain.
func NewAgricultureCompanionAdapter(inner any) *AgricultureCompanionAdapter {
	return &AgricultureCompanionAdapter{NewDomainCompanionAdapter(inner, AgricultureDomainContext{})}
}

// BeautyDomainContext is the Beauty domain's prompt snippet.
type BeautyDomainContext struct{}

// DomainID implements DomainContext.
func (BeautyDomainContext) DomainID() string { return "Beauty" }

// SystemPromptSnippet implements DomainContext.
func (BeautyDomainContext) SystemPromptSnippet() string {
	return "You are helping with grooming and appearance. Never comment on a person's appearance unless they asked."
}

// BeautyCompanionAdapter is a companion session scoped to the Beauty domain.
type BeautyCompanionAdapter struct{ *DomainCompanionAdapter }

// NewBeautyCompanionAdapter wraps a session for the Beauty domain.
func NewBeautyCompanionAdapter(inner any) *BeautyCompanionAdapter {
	return &BeautyCompanionAdapter{NewDomainCompanionAdapter(inner, BeautyDomainContext{})}
}

// BusinessDomainContext is the Business domain's prompt snippet.
type BusinessDomainContext struct{}

// DomainID implements DomainContext.
func (BusinessDomainContext) DomainID() string { return "Business" }

// SystemPromptSnippet implements DomainContext.
func (BusinessDomainContext) SystemPromptSnippet() string {
	return "You are helping run a business."
}

// BusinessCompanionAdapter is a companion session scoped to the Business domain.
type BusinessCompanionAdapter struct{ *DomainCompanionAdapter }

// NewBusinessCompanionAdapter wraps a session for the Business domain.
func NewBusinessCompanionAdapter(inner any) *BusinessCompanionAdapter {
	return &BusinessCompanionAdapter{NewDomainCompanionAdapter(inner, BusinessDomainContext{})}
}

// CivicDomainContext is the Civic domain's prompt snippet.
type CivicDomainContext struct{}

// DomainID implements DomainContext.
func (CivicDomainContext) DomainID() string { return "Civic" }

// SystemPromptSnippet implements DomainContext.
func (CivicDomainContext) SystemPromptSnippet() string {
	return "You are helping somebody deal with public bodies and representatives. Report who holds an office and how to reach them. Never advise how to vote."
}

// CivicCompanionAdapter is a companion session scoped to the Civic domain.
type CivicCompanionAdapter struct{ *DomainCompanionAdapter }

// NewCivicCompanionAdapter wraps a session for the Civic domain.
func NewCivicCompanionAdapter(inner any) *CivicCompanionAdapter {
	return &CivicCompanionAdapter{NewDomainCompanionAdapter(inner, CivicDomainContext{})}
}

// CommerceDomainContext is the Commerce domain's prompt snippet.
type CommerceDomainContext struct{}

// DomainID implements DomainContext.
func (CommerceDomainContext) DomainID() string { return "Commerce" }

// SystemPromptSnippet implements DomainContext.
func (CommerceDomainContext) SystemPromptSnippet() string {
	return "You are helping with buying and selling. Never complete a purchase; prepare it and hand it back."
}

// CommerceCompanionAdapter is a companion session scoped to the Commerce domain.
type CommerceCompanionAdapter struct{ *DomainCompanionAdapter }

// NewCommerceCompanionAdapter wraps a session for the Commerce domain.
func NewCommerceCompanionAdapter(inner any) *CommerceCompanionAdapter {
	return &CommerceCompanionAdapter{NewDomainCompanionAdapter(inner, CommerceDomainContext{})}
}

// CommerceAccountingDomainContext is the Commerce.Accounting domain's prompt snippet.
type CommerceAccountingDomainContext struct{}

// DomainID implements DomainContext.
func (CommerceAccountingDomainContext) DomainID() string { return "Commerce.Accounting" }

// SystemPromptSnippet implements DomainContext.
func (CommerceAccountingDomainContext) SystemPromptSnippet() string {
	return "You are helping keep the books. You are not an accountant and this is not filed advice."
}

// CommerceAccountingCompanionAdapter is a companion session scoped to the Commerce.Accounting domain.
type CommerceAccountingCompanionAdapter struct{ *DomainCompanionAdapter }

// NewCommerceAccountingCompanionAdapter wraps a session for the Commerce.Accounting domain.
func NewCommerceAccountingCompanionAdapter(inner any) *CommerceAccountingCompanionAdapter {
	return &CommerceAccountingCompanionAdapter{NewDomainCompanionAdapter(inner, CommerceAccountingDomainContext{})}
}

// CommerceFinanceDomainContext is the Commerce.Finance domain's prompt snippet.
type CommerceFinanceDomainContext struct{}

// DomainID implements DomainContext.
func (CommerceFinanceDomainContext) DomainID() string { return "Commerce.Finance" }

// SystemPromptSnippet implements DomainContext.
func (CommerceFinanceDomainContext) SystemPromptSnippet() string {
	return "You are helping with payments and cash flow. Never move money."
}

// CommerceFinanceCompanionAdapter is a companion session scoped to the Commerce.Finance domain.
type CommerceFinanceCompanionAdapter struct{ *DomainCompanionAdapter }

// NewCommerceFinanceCompanionAdapter wraps a session for the Commerce.Finance domain.
func NewCommerceFinanceCompanionAdapter(inner any) *CommerceFinanceCompanionAdapter {
	return &CommerceFinanceCompanionAdapter{NewDomainCompanionAdapter(inner, CommerceFinanceDomainContext{})}
}

// CommerceIntegrationPayFastDomainContext is the Commerce.Integration.PayFast domain's prompt snippet.
type CommerceIntegrationPayFastDomainContext struct{}

// DomainID implements DomainContext.
func (CommerceIntegrationPayFastDomainContext) DomainID() string {
	return "Commerce.Integration.PayFast"
}

// SystemPromptSnippet implements DomainContext.
func (CommerceIntegrationPayFastDomainContext) SystemPromptSnippet() string {
	return "You are helping with PayFast payment integration. Never handle a live merchant key; sandbox unless told otherwise."
}

// CommerceIntegrationPayFastCompanionAdapter is a companion session scoped to the Commerce.Integration.PayFast domain.
type CommerceIntegrationPayFastCompanionAdapter struct{ *DomainCompanionAdapter }

// NewCommerceIntegrationPayFastCompanionAdapter wraps a session for the Commerce.Integration.PayFast domain.
func NewCommerceIntegrationPayFastCompanionAdapter(inner any) *CommerceIntegrationPayFastCompanionAdapter {
	return &CommerceIntegrationPayFastCompanionAdapter{NewDomainCompanionAdapter(inner, CommerceIntegrationPayFastDomainContext{})}
}

// CommerceIntegrationXeroDomainContext is the Commerce.Integration.Xero domain's prompt snippet.
type CommerceIntegrationXeroDomainContext struct{}

// DomainID implements DomainContext.
func (CommerceIntegrationXeroDomainContext) DomainID() string { return "Commerce.Integration.Xero" }

// SystemPromptSnippet implements DomainContext.
func (CommerceIntegrationXeroDomainContext) SystemPromptSnippet() string {
	return "You are helping with Xero accounting integration."
}

// CommerceIntegrationXeroCompanionAdapter is a companion session scoped to the Commerce.Integration.Xero domain.
type CommerceIntegrationXeroCompanionAdapter struct{ *DomainCompanionAdapter }

// NewCommerceIntegrationXeroCompanionAdapter wraps a session for the Commerce.Integration.Xero domain.
func NewCommerceIntegrationXeroCompanionAdapter(inner any) *CommerceIntegrationXeroCompanionAdapter {
	return &CommerceIntegrationXeroCompanionAdapter{NewDomainCompanionAdapter(inner, CommerceIntegrationXeroDomainContext{})}
}

// CommunityDomainContext is the Community domain's prompt snippet.
type CommunityDomainContext struct{}

// DomainID implements DomainContext.
func (CommunityDomainContext) DomainID() string { return "Community" }

// SystemPromptSnippet implements DomainContext.
func (CommunityDomainContext) SystemPromptSnippet() string {
	return "You are helping with community organising and volunteering."
}

// CommunityCompanionAdapter is a companion session scoped to the Community domain.
type CommunityCompanionAdapter struct{ *DomainCompanionAdapter }

// NewCommunityCompanionAdapter wraps a session for the Community domain.
func NewCommunityCompanionAdapter(inner any) *CommunityCompanionAdapter {
	return &CommunityCompanionAdapter{NewDomainCompanionAdapter(inner, CommunityDomainContext{})}
}

// ConstructionDomainContext is the Construction domain's prompt snippet.
type ConstructionDomainContext struct{}

// DomainID implements DomainContext.
func (ConstructionDomainContext) DomainID() string { return "Construction" }

// SystemPromptSnippet implements DomainContext.
func (ConstructionDomainContext) SystemPromptSnippet() string {
	return "You are helping with building work, costs and scheduling. Never give structural or safety-critical advice; name the professional to ask."
}

// ConstructionCompanionAdapter is a companion session scoped to the Construction domain.
type ConstructionCompanionAdapter struct{ *DomainCompanionAdapter }

// NewConstructionCompanionAdapter wraps a session for the Construction domain.
func NewConstructionCompanionAdapter(inner any) *ConstructionCompanionAdapter {
	return &ConstructionCompanionAdapter{NewDomainCompanionAdapter(inner, ConstructionDomainContext{})}
}

// CreativeDomainContext is the Creative domain's prompt snippet.
type CreativeDomainContext struct{}

// DomainID implements DomainContext.
func (CreativeDomainContext) DomainID() string { return "Creative" }

// SystemPromptSnippet implements DomainContext.
func (CreativeDomainContext) SystemPromptSnippet() string {
	return "You are helping make something."
}

// CreativeCompanionAdapter is a companion session scoped to the Creative domain.
type CreativeCompanionAdapter struct{ *DomainCompanionAdapter }

// NewCreativeCompanionAdapter wraps a session for the Creative domain.
func NewCreativeCompanionAdapter(inner any) *CreativeCompanionAdapter {
	return &CreativeCompanionAdapter{NewDomainCompanionAdapter(inner, CreativeDomainContext{})}
}

// EducationDomainContext is the Education domain's prompt snippet.
type EducationDomainContext struct{}

// DomainID implements DomainContext.
func (EducationDomainContext) DomainID() string { return "Education" }

// SystemPromptSnippet implements DomainContext.
func (EducationDomainContext) SystemPromptSnippet() string {
	return "You are helping somebody learn or teach. Explain rather than answer when the point is that somebody learns it."
}

// EducationCompanionAdapter is a companion session scoped to the Education domain.
type EducationCompanionAdapter struct{ *DomainCompanionAdapter }

// NewEducationCompanionAdapter wraps a session for the Education domain.
func NewEducationCompanionAdapter(inner any) *EducationCompanionAdapter {
	return &EducationCompanionAdapter{NewDomainCompanionAdapter(inner, EducationDomainContext{})}
}

// ElderlyDomainContext is the Elderly domain's prompt snippet.
type ElderlyDomainContext struct{}

// DomainID implements DomainContext.
func (ElderlyDomainContext) DomainID() string { return "Elderly" }

// SystemPromptSnippet implements DomainContext.
func (ElderlyDomainContext) SystemPromptSnippet() string {
	return "You are helping care for somebody older. Never record that a medication was taken; only that a reminder was acknowledged."
}

// ElderlyCompanionAdapter is a companion session scoped to the Elderly domain.
type ElderlyCompanionAdapter struct{ *DomainCompanionAdapter }

// NewElderlyCompanionAdapter wraps a session for the Elderly domain.
func NewElderlyCompanionAdapter(inner any) *ElderlyCompanionAdapter {
	return &ElderlyCompanionAdapter{NewDomainCompanionAdapter(inner, ElderlyDomainContext{})}
}

// EnergyDomainContext is the Energy domain's prompt snippet.
type EnergyDomainContext struct{}

// DomainID implements DomainContext.
func (EnergyDomainContext) DomainID() string { return "Energy" }

// SystemPromptSnippet implements DomainContext.
func (EnergyDomainContext) SystemPromptSnippet() string {
	return "You are helping with power use, meters and tariffs."
}

// EnergyCompanionAdapter is a companion session scoped to the Energy domain.
type EnergyCompanionAdapter struct{ *DomainCompanionAdapter }

// NewEnergyCompanionAdapter wraps a session for the Energy domain.
func NewEnergyCompanionAdapter(inner any) *EnergyCompanionAdapter {
	return &EnergyCompanionAdapter{NewDomainCompanionAdapter(inner, EnergyDomainContext{})}
}

// FaithDomainContext is the Faith domain's prompt snippet.
type FaithDomainContext struct{}

// DomainID implements DomainContext.
func (FaithDomainContext) DomainID() string { return "Faith" }

// SystemPromptSnippet implements DomainContext.
func (FaithDomainContext) SystemPromptSnippet() string {
	return "You are helping with matters of faith and practice. Never adjudicate between traditions, and never repeat what was shared in confidence."
}

// FaithCompanionAdapter is a companion session scoped to the Faith domain.
type FaithCompanionAdapter struct{ *DomainCompanionAdapter }

// NewFaithCompanionAdapter wraps a session for the Faith domain.
func NewFaithCompanionAdapter(inner any) *FaithCompanionAdapter {
	return &FaithCompanionAdapter{NewDomainCompanionAdapter(inner, FaithDomainContext{})}
}

// FamilyDomainContext is the Family domain's prompt snippet.
type FamilyDomainContext struct{}

// DomainID implements DomainContext.
func (FamilyDomainContext) DomainID() string { return "Family" }

// SystemPromptSnippet implements DomainContext.
func (FamilyDomainContext) SystemPromptSnippet() string {
	return "You are helping a household run."
}

// FamilyCompanionAdapter is a companion session scoped to the Family domain.
type FamilyCompanionAdapter struct{ *DomainCompanionAdapter }

// NewFamilyCompanionAdapter wraps a session for the Family domain.
func NewFamilyCompanionAdapter(inner any) *FamilyCompanionAdapter {
	return &FamilyCompanionAdapter{NewDomainCompanionAdapter(inner, FamilyDomainContext{})}
}

// FitnessDomainContext is the Fitness domain's prompt snippet.
type FitnessDomainContext struct{}

// DomainID implements DomainContext.
func (FitnessDomainContext) DomainID() string { return "Fitness" }

// SystemPromptSnippet implements DomainContext.
func (FitnessDomainContext) SystemPromptSnippet() string {
	return "You are helping with training. You are not a physiotherapist; stop at pain and name who to ask."
}

// FitnessCompanionAdapter is a companion session scoped to the Fitness domain.
type FitnessCompanionAdapter struct{ *DomainCompanionAdapter }

// NewFitnessCompanionAdapter wraps a session for the Fitness domain.
func NewFitnessCompanionAdapter(inner any) *FitnessCompanionAdapter {
	return &FitnessCompanionAdapter{NewDomainCompanionAdapter(inner, FitnessDomainContext{})}
}

// FoodDomainContext is the Food domain's prompt snippet.
type FoodDomainContext struct{}

// DomainID implements DomainContext.
func (FoodDomainContext) DomainID() string { return "Food" }

// SystemPromptSnippet implements DomainContext.
func (FoodDomainContext) SystemPromptSnippet() string {
	return "You are helping with meals, shopping and cooking. Take an allergy at face value and never work around one."
}

// FoodCompanionAdapter is a companion session scoped to the Food domain.
type FoodCompanionAdapter struct{ *DomainCompanionAdapter }

// NewFoodCompanionAdapter wraps a session for the Food domain.
func NewFoodCompanionAdapter(inner any) *FoodCompanionAdapter {
	return &FoodCompanionAdapter{NewDomainCompanionAdapter(inner, FoodDomainContext{})}
}

// GamingDomainContext is the Gaming domain's prompt snippet.
type GamingDomainContext struct{}

// DomainID implements DomainContext.
func (GamingDomainContext) DomainID() string { return "Gaming" }

// SystemPromptSnippet implements DomainContext.
func (GamingDomainContext) SystemPromptSnippet() string {
	return "You are helping with games."
}

// GamingCompanionAdapter is a companion session scoped to the Gaming domain.
type GamingCompanionAdapter struct{ *DomainCompanionAdapter }

// NewGamingCompanionAdapter wraps a session for the Gaming domain.
func NewGamingCompanionAdapter(inner any) *GamingCompanionAdapter {
	return &GamingCompanionAdapter{NewDomainCompanionAdapter(inner, GamingDomainContext{})}
}

// HRDomainContext is the HR domain's prompt snippet.
type HRDomainContext struct{}

// DomainID implements DomainContext.
func (HRDomainContext) DomainID() string { return "HR" }

// SystemPromptSnippet implements DomainContext.
func (HRDomainContext) SystemPromptSnippet() string {
	return "You are helping with people and employment matters. Never draft a decision about a named person's employment. A policy can be summarised; who to let go cannot be recommended."
}

// HRCompanionAdapter is a companion session scoped to the HR domain.
type HRCompanionAdapter struct{ *DomainCompanionAdapter }

// NewHRCompanionAdapter wraps a session for the HR domain.
func NewHRCompanionAdapter(inner any) *HRCompanionAdapter {
	return &HRCompanionAdapter{NewDomainCompanionAdapter(inner, HRDomainContext{})}
}

// HealthcareDomainContext is the Healthcare domain's prompt snippet.
type HealthcareDomainContext struct{}

// DomainID implements DomainContext.
func (HealthcareDomainContext) DomainID() string { return "Healthcare" }

// SystemPromptSnippet implements DomainContext.
func (HealthcareDomainContext) SystemPromptSnippet() string {
	return "You are helping somebody navigate care. You do not diagnose and you do not dose. Say what to ask and who to ask."
}

// HealthcareCompanionAdapter is a companion session scoped to the Healthcare domain.
type HealthcareCompanionAdapter struct{ *DomainCompanionAdapter }

// NewHealthcareCompanionAdapter wraps a session for the Healthcare domain.
func NewHealthcareCompanionAdapter(inner any) *HealthcareCompanionAdapter {
	return &HealthcareCompanionAdapter{NewDomainCompanionAdapter(inner, HealthcareDomainContext{})}
}

// HomeDomainContext is the Home domain's prompt snippet.
type HomeDomainContext struct{}

// DomainID implements DomainContext.
func (HomeDomainContext) DomainID() string { return "Home" }

// SystemPromptSnippet implements DomainContext.
func (HomeDomainContext) SystemPromptSnippet() string {
	return "You are helping run and maintain a home."
}

// HomeCompanionAdapter is a companion session scoped to the Home domain.
type HomeCompanionAdapter struct{ *DomainCompanionAdapter }

// NewHomeCompanionAdapter wraps a session for the Home domain.
func NewHomeCompanionAdapter(inner any) *HomeCompanionAdapter {
	return &HomeCompanionAdapter{NewDomainCompanionAdapter(inner, HomeDomainContext{})}
}

// HospitalityDomainContext is the Hospitality domain's prompt snippet.
type HospitalityDomainContext struct{}

// DomainID implements DomainContext.
func (HospitalityDomainContext) DomainID() string { return "Hospitality" }

// SystemPromptSnippet implements DomainContext.
func (HospitalityDomainContext) SystemPromptSnippet() string {
	return "You are helping run a place where people stay. A guest's details are theirs; never repeat them to another guest."
}

// HospitalityCompanionAdapter is a companion session scoped to the Hospitality domain.
type HospitalityCompanionAdapter struct{ *DomainCompanionAdapter }

// NewHospitalityCompanionAdapter wraps a session for the Hospitality domain.
func NewHospitalityCompanionAdapter(inner any) *HospitalityCompanionAdapter {
	return &HospitalityCompanionAdapter{NewDomainCompanionAdapter(inner, HospitalityDomainContext{})}
}

// KidsDomainContext is the Kids domain's prompt snippet.
type KidsDomainContext struct{}

// DomainID implements DomainContext.
func (KidsDomainContext) DomainID() string { return "Kids" }

// SystemPromptSnippet implements DomainContext.
func (KidsDomainContext) SystemPromptSnippet() string {
	return "You are talking with a child. Refuse rather than soften. A softened answer to a child is still an answer."
}

// KidsCompanionAdapter is a companion session scoped to the Kids domain.
type KidsCompanionAdapter struct{ *DomainCompanionAdapter }

// NewKidsCompanionAdapter wraps a session for the Kids domain.
func NewKidsCompanionAdapter(inner any) *KidsCompanionAdapter {
	return &KidsCompanionAdapter{NewDomainCompanionAdapter(inner, KidsDomainContext{})}
}

// LegalDomainContext is the Legal domain's prompt snippet.
type LegalDomainContext struct{}

// DomainID implements DomainContext.
func (LegalDomainContext) DomainID() string { return "Legal" }

// SystemPromptSnippet implements DomainContext.
func (LegalDomainContext) SystemPromptSnippet() string {
	return "You are helping somebody understand a legal situation. This is not legal advice, and say so in the answer rather than only in the prompt. A disclaimer the model was told about but did not say is a disclaimer nobody received."
}

// LegalCompanionAdapter is a companion session scoped to the Legal domain.
type LegalCompanionAdapter struct{ *DomainCompanionAdapter }

// NewLegalCompanionAdapter wraps a session for the Legal domain.
func NewLegalCompanionAdapter(inner any) *LegalCompanionAdapter {
	return &LegalCompanionAdapter{NewDomainCompanionAdapter(inner, LegalDomainContext{})}
}

// LogisticsDomainContext is the Logistics domain's prompt snippet.
type LogisticsDomainContext struct{}

// DomainID implements DomainContext.
func (LogisticsDomainContext) DomainID() string { return "Logistics" }

// SystemPromptSnippet implements DomainContext.
func (LogisticsDomainContext) SystemPromptSnippet() string {
	return "You are helping move things."
}

// LogisticsCompanionAdapter is a companion session scoped to the Logistics domain.
type LogisticsCompanionAdapter struct{ *DomainCompanionAdapter }

// NewLogisticsCompanionAdapter wraps a session for the Logistics domain.
func NewLogisticsCompanionAdapter(inner any) *LogisticsCompanionAdapter {
	return &LogisticsCompanionAdapter{NewDomainCompanionAdapter(inner, LogisticsDomainContext{})}
}

// MediaCompanionAdapter is a companion session scoped to the Media domain.
//
// The snippet is declared elsewhere in this package as a struct with a method,
// and is used directly rather than restated.
type MediaCompanionAdapter struct{ *DomainCompanionAdapter }

// NewMediaCompanionAdapter wraps a session for the Media domain.
func NewMediaCompanionAdapter(inner any) *MediaCompanionAdapter {
	return &MediaCompanionAdapter{NewDomainCompanionAdapter(inner,
		staticDomainContext{id: "Media", snippet: MediaDomainContext{}.SystemPromptSnippet()})}
}

// ParentingDomainContext is the Parenting domain's prompt snippet.
type ParentingDomainContext struct{}

// DomainID implements DomainContext.
func (ParentingDomainContext) DomainID() string { return "Parenting" }

// SystemPromptSnippet implements DomainContext.
func (ParentingDomainContext) SystemPromptSnippet() string {
	return "You are helping somebody parent. Offer options, not verdicts. You are not in the room."
}

// ParentingCompanionAdapter is a companion session scoped to the Parenting domain.
type ParentingCompanionAdapter struct{ *DomainCompanionAdapter }

// NewParentingCompanionAdapter wraps a session for the Parenting domain.
func NewParentingCompanionAdapter(inner any) *ParentingCompanionAdapter {
	return &ParentingCompanionAdapter{NewDomainCompanionAdapter(inner, ParentingDomainContext{})}
}

// PersonalFinanceDomainContext is the Personal.Finance domain's prompt snippet.
type PersonalFinanceDomainContext struct{}

// DomainID implements DomainContext.
func (PersonalFinanceDomainContext) DomainID() string { return "Personal.Finance" }

// SystemPromptSnippet implements DomainContext.
func (PersonalFinanceDomainContext) SystemPromptSnippet() string {
	return "You are helping somebody with their own money. Explain and total. Never move money, and never recommend an investment."
}

// PersonalFinanceCompanionAdapter is a companion session scoped to the Personal.Finance domain.
type PersonalFinanceCompanionAdapter struct{ *DomainCompanionAdapter }

// NewPersonalFinanceCompanionAdapter wraps a session for the Personal.Finance domain.
func NewPersonalFinanceCompanionAdapter(inner any) *PersonalFinanceCompanionAdapter {
	return &PersonalFinanceCompanionAdapter{NewDomainCompanionAdapter(inner, PersonalFinanceDomainContext{})}
}

// PersonalHealthDomainContext is the Personal.Health domain's prompt snippet.
type PersonalHealthDomainContext struct{}

// DomainID implements DomainContext.
func (PersonalHealthDomainContext) DomainID() string { return "Personal.Health" }

// SystemPromptSnippet implements DomainContext.
func (PersonalHealthDomainContext) SystemPromptSnippet() string {
	return "You are helping somebody track their own health. Readings are readings. You do not diagnose."
}

// PersonalHealthCompanionAdapter is a companion session scoped to the Personal.Health domain.
type PersonalHealthCompanionAdapter struct{ *DomainCompanionAdapter }

// NewPersonalHealthCompanionAdapter wraps a session for the Personal.Health domain.
func NewPersonalHealthCompanionAdapter(inner any) *PersonalHealthCompanionAdapter {
	return &PersonalHealthCompanionAdapter{NewDomainCompanionAdapter(inner, PersonalHealthDomainContext{})}
}

// PersonalMentalDomainContext is the Personal.Mental domain's prompt snippet.
type PersonalMentalDomainContext struct{}

// DomainID implements DomainContext.
func (PersonalMentalDomainContext) DomainID() string { return "Personal.Mental" }

// SystemPromptSnippet implements DomainContext.
func (PersonalMentalDomainContext) SystemPromptSnippet() string {
	return "You are helping somebody with how they are doing. Some things are not yours to handle. Say so plainly and name who is."
}

// PersonalMentalCompanionAdapter is a companion session scoped to the Personal.Mental domain.
type PersonalMentalCompanionAdapter struct{ *DomainCompanionAdapter }

// NewPersonalMentalCompanionAdapter wraps a session for the Personal.Mental domain.
func NewPersonalMentalCompanionAdapter(inner any) *PersonalMentalCompanionAdapter {
	return &PersonalMentalCompanionAdapter{NewDomainCompanionAdapter(inner, PersonalMentalDomainContext{})}
}

// PetsDomainContext is the Pets domain's prompt snippet.
type PetsDomainContext struct{}

// DomainID implements DomainContext.
func (PetsDomainContext) DomainID() string { return "Pets" }

// SystemPromptSnippet implements DomainContext.
func (PetsDomainContext) SystemPromptSnippet() string {
	return "You are helping look after an animal. Never advise on medication or dosage; name the vet."
}

// PetsCompanionAdapter is a companion session scoped to the Pets domain.
type PetsCompanionAdapter struct{ *DomainCompanionAdapter }

// NewPetsCompanionAdapter wraps a session for the Pets domain.
func NewPetsCompanionAdapter(inner any) *PetsCompanionAdapter {
	return &PetsCompanionAdapter{NewDomainCompanionAdapter(inner, PetsDomainContext{})}
}

// RealEstateDomainContext is the RealEstate domain's prompt snippet.
type RealEstateDomainContext struct{}

// DomainID implements DomainContext.
func (RealEstateDomainContext) DomainID() string { return "RealEstate" }

// SystemPromptSnippet implements DomainContext.
func (RealEstateDomainContext) SystemPromptSnippet() string {
	return "You are helping with property."
}

// RealEstateCompanionAdapter is a companion session scoped to the RealEstate domain.
type RealEstateCompanionAdapter struct{ *DomainCompanionAdapter }

// NewRealEstateCompanionAdapter wraps a session for the RealEstate domain.
func NewRealEstateCompanionAdapter(inner any) *RealEstateCompanionAdapter {
	return &RealEstateCompanionAdapter{NewDomainCompanionAdapter(inner, RealEstateDomainContext{})}
}

// RelationshipsDomainContext is the Relationships domain's prompt snippet.
type RelationshipsDomainContext struct{}

// DomainID implements DomainContext.
func (RelationshipsDomainContext) DomainID() string { return "Relationships" }

// SystemPromptSnippet implements DomainContext.
func (RelationshipsDomainContext) SystemPromptSnippet() string {
	return "You are helping somebody keep in touch. Never draft a message as though the person wrote it themselves."
}

// RelationshipsCompanionAdapter is a companion session scoped to the Relationships domain.
type RelationshipsCompanionAdapter struct{ *DomainCompanionAdapter }

// NewRelationshipsCompanionAdapter wraps a session for the Relationships domain.
func NewRelationshipsCompanionAdapter(inner any) *RelationshipsCompanionAdapter {
	return &RelationshipsCompanionAdapter{NewDomainCompanionAdapter(inner, RelationshipsDomainContext{})}
}

// RetailDomainContext is the Retail domain's prompt snippet.
type RetailDomainContext struct{}

// DomainID implements DomainContext.
func (RetailDomainContext) DomainID() string { return "Retail" }

// SystemPromptSnippet implements DomainContext.
func (RetailDomainContext) SystemPromptSnippet() string {
	return "You are helping run a shop."
}

// RetailCompanionAdapter is a companion session scoped to the Retail domain.
type RetailCompanionAdapter struct{ *DomainCompanionAdapter }

// NewRetailCompanionAdapter wraps a session for the Retail domain.
func NewRetailCompanionAdapter(inner any) *RetailCompanionAdapter {
	return &RetailCompanionAdapter{NewDomainCompanionAdapter(inner, RetailDomainContext{})}
}

// SafetyCompanionAdapter is a companion session scoped to the Safety domain.
//
// The snippet itself is declared elsewhere in this package and is reached
// through it rather than restated: two snippets for one domain is one edit away
// from an assistant that says different things depending on which constructor a
// host reached for.
type SafetyCompanionAdapter struct{ *DomainCompanionAdapter }

// NewSafetyCompanionAdapter wraps a session for the Safety domain.
func NewSafetyCompanionAdapter(inner any) *SafetyCompanionAdapter {
	return &SafetyCompanionAdapter{NewDomainCompanionAdapter(inner,
		staticDomainContext{id: "Safety", snippet: SafetyDomainContext.SystemPromptSnippet()})}
}

// SafetyChildCompanionAdapter is a companion session scoped to the Safety.Child domain.
//
// The snippet itself is declared elsewhere in this package and is reached
// through it rather than restated: two snippets for one domain is one edit away
// from an assistant that says different things depending on which constructor a
// host reached for.
type SafetyChildCompanionAdapter struct{ *DomainCompanionAdapter }

// NewSafetyChildCompanionAdapter wraps a session for the Safety.Child domain.
func NewSafetyChildCompanionAdapter(inner any) *SafetyChildCompanionAdapter {
	return &SafetyChildCompanionAdapter{NewDomainCompanionAdapter(inner,
		staticDomainContext{id: "Safety.Child", snippet: SafetyChildDomainContext.SystemPromptSnippet()})}
}

// SocialDomainContext is the Social domain's prompt snippet.
type SocialDomainContext struct{}

// DomainID implements DomainContext.
func (SocialDomainContext) DomainID() string { return "Social" }

// SystemPromptSnippet implements DomainContext.
func (SocialDomainContext) SystemPromptSnippet() string {
	return "You are helping with what somebody shares publicly. Never post. Prepare and hand it back."
}

// SocialCompanionAdapter is a companion session scoped to the Social domain.
type SocialCompanionAdapter struct{ *DomainCompanionAdapter }

// NewSocialCompanionAdapter wraps a session for the Social domain.
func NewSocialCompanionAdapter(inner any) *SocialCompanionAdapter {
	return &SocialCompanionAdapter{NewDomainCompanionAdapter(inner, SocialDomainContext{})}
}

// SportsDomainContext is the Sports domain's prompt snippet.
type SportsDomainContext struct{}

// DomainID implements DomainContext.
func (SportsDomainContext) DomainID() string { return "Sports" }

// SystemPromptSnippet implements DomainContext.
func (SportsDomainContext) SystemPromptSnippet() string {
	return "You are helping with sport and training."
}

// SportsCompanionAdapter is a companion session scoped to the Sports domain.
type SportsCompanionAdapter struct{ *DomainCompanionAdapter }

// NewSportsCompanionAdapter wraps a session for the Sports domain.
func NewSportsCompanionAdapter(inner any) *SportsCompanionAdapter {
	return &SportsCompanionAdapter{NewDomainCompanionAdapter(inner, SportsDomainContext{})}
}

// TourismDomainContext is the Tourism domain's prompt snippet.
type TourismDomainContext struct{}

// DomainID implements DomainContext.
func (TourismDomainContext) DomainID() string { return "Tourism" }

// SystemPromptSnippet implements DomainContext.
func (TourismDomainContext) SystemPromptSnippet() string {
	return "You are helping somebody see a place."
}

// TourismCompanionAdapter is a companion session scoped to the Tourism domain.
type TourismCompanionAdapter struct{ *DomainCompanionAdapter }

// NewTourismCompanionAdapter wraps a session for the Tourism domain.
func NewTourismCompanionAdapter(inner any) *TourismCompanionAdapter {
	return &TourismCompanionAdapter{NewDomainCompanionAdapter(inner, TourismDomainContext{})}
}

// TravelDomainContext is the Travel domain's prompt snippet.
type TravelDomainContext struct{}

// DomainID implements DomainContext.
func (TravelDomainContext) DomainID() string { return "Travel" }

// SystemPromptSnippet implements DomainContext.
func (TravelDomainContext) SystemPromptSnippet() string {
	return "You are helping somebody travel. Never book anything; prepare it and hand it back."
}

// TravelCompanionAdapter is a companion session scoped to the Travel domain.
type TravelCompanionAdapter struct{ *DomainCompanionAdapter }

// NewTravelCompanionAdapter wraps a session for the Travel domain.
func NewTravelCompanionAdapter(inner any) *TravelCompanionAdapter {
	return &TravelCompanionAdapter{NewDomainCompanionAdapter(inner, TravelDomainContext{})}
}

// WearableDomainContext is the Wearable domain's prompt snippet.
type WearableDomainContext struct{}

// DomainID implements DomainContext.
func (WearableDomainContext) DomainID() string { return "Wearable" }

// SystemPromptSnippet implements DomainContext.
func (WearableDomainContext) SystemPromptSnippet() string {
	return "You are answering on a device with a very small screen. Shorten the answer itself. Truncating a long one leaves a sentence that stops."
}

// WearableCompanionAdapter is a companion session scoped to the Wearable domain.
type WearableCompanionAdapter struct{ *DomainCompanionAdapter }

// NewWearableCompanionAdapter wraps a session for the Wearable domain.
func NewWearableCompanionAdapter(inner any) *WearableCompanionAdapter {
	return &WearableCompanionAdapter{NewDomainCompanionAdapter(inner, WearableDomainContext{})}
}
