// wiring.go
//
// GENERATED by go/tools/gen_domains.py. Do not edit by hand; edit the table.
//
// The C# registers each module's implementations against a ServiceCollection.
// Go has no DI container, so what survives the port is the part that actually
// matters: WHAT THE DEFAULTS ARE.
//
// Every one of them is the safe end — a null store, a disabled runner, an empty
// provider chain, a carrier that dials nobody. Having them in one generated
// place is what makes that reviewable in a sitting, rather than spread across
// twenty-five files where one of them quietly defaults the other way.

package circleai

// Wiring is a module's default wiring, stated rather than registered.
type Wiring interface {
	// Wires says what this module registers.
	Wires() string
	// Defaults says what a host gets when it configures nothing. Always the
	// safe end.
	Defaults() string
}

// CircleAIRuntimeServiceCollectionExtensions states the defaults for the runtime.
type CircleAIRuntimeServiceCollectionExtensions struct{}

// Wires implements Wiring.
func (CircleAIRuntimeServiceCollectionExtensions) Wires() string { return "the runtime" }

// Defaults implements Wiring.
func (CircleAIRuntimeServiceCollectionExtensions) Defaults() string { return "a backend selector that picks CPU unless a host says otherwise" }

// MemoryServiceCollectionExtensions states the defaults for the memory store.
type MemoryServiceCollectionExtensions struct{}

// Wires implements Wiring.
func (MemoryServiceCollectionExtensions) Wires() string { return "the memory store" }

// Defaults implements Wiring.
func (MemoryServiceCollectionExtensions) Defaults() string { return "an in-memory store and an append-only log with no file behind it" }

// PluginsServiceCollectionExtensions states the defaults for the plugin host.
type PluginsServiceCollectionExtensions struct{}

// Wires implements Wiring.
func (PluginsServiceCollectionExtensions) Wires() string { return "the plugin host" }

// Defaults implements Wiring.
func (PluginsServiceCollectionExtensions) Defaults() string { return "a root resolver pointing at the project, and every plugin disabled" }

// CloudFallbackServiceCollectionExtensions states the defaults for the cloud fallback chain.
type CloudFallbackServiceCollectionExtensions struct{}

// Wires implements Wiring.
func (CloudFallbackServiceCollectionExtensions) Wires() string { return "the cloud fallback chain" }

// Defaults implements Wiring.
func (CloudFallbackServiceCollectionExtensions) Defaults() string { return "an empty chain: no provider is configured, so nothing leaves the device" }

// McpServiceCollectionExtensions states the defaults for the MCP endpoints.
type McpServiceCollectionExtensions struct{}

// Wires implements Wiring.
func (McpServiceCollectionExtensions) Wires() string { return "the MCP endpoints" }

// Defaults implements Wiring.
func (McpServiceCollectionExtensions) Defaults() string { return "the endpoints registered but no tools imported" }

// MultiplayerServiceCollectionExtensions states the defaults for multiplayer hosting.
type MultiplayerServiceCollectionExtensions struct{}

// Wires implements Wiring.
func (MultiplayerServiceCollectionExtensions) Wires() string { return "multiplayer hosting" }

// Defaults implements Wiring.
func (MultiplayerServiceCollectionExtensions) Defaults() string { return "a per-session peer identity, never the device's AetherTag" }

// NeuronServiceCollectionExtensions states the defaults for the resident-model manager.
type NeuronServiceCollectionExtensions struct{}

// Wires implements Wiring.
func (NeuronServiceCollectionExtensions) Wires() string { return "the resident-model manager" }

// Defaults implements Wiring.
func (NeuronServiceCollectionExtensions) Defaults() string { return "one slot and a RAM ceiling the host must set" }

// RealtimeServiceCollectionExtensions states the defaults for the realtime contracts.
type RealtimeServiceCollectionExtensions struct{}

// Wires implements Wiring.
func (RealtimeServiceCollectionExtensions) Wires() string { return "the realtime contracts" }

// Defaults implements Wiring.
func (RealtimeServiceCollectionExtensions) Defaults() string { return "no transport, so the local voice loop runs" }

// RealtimeCloudServiceCollectionExtensions states the defaults for the realtime cloud services.
type RealtimeCloudServiceCollectionExtensions struct{}

// Wires implements Wiring.
func (RealtimeCloudServiceCollectionExtensions) Wires() string { return "the realtime cloud services" }

// Defaults implements Wiring.
func (RealtimeCloudServiceCollectionExtensions) Defaults() string { return "a null transport factory: the local loop runs unless a provider is wired" }

// SpeechCloudServiceCollectionExtensions states the defaults for the cloud speech services.
type SpeechCloudServiceCollectionExtensions struct{}

// Wires implements Wiring.
func (SpeechCloudServiceCollectionExtensions) Wires() string { return "the cloud speech services" }

// Defaults implements Wiring.
func (SpeechCloudServiceCollectionExtensions) Defaults() string { return "nothing configured, so audio stays on the device" }

// VisionCloudServiceCollectionExtensions states the defaults for the cloud image generators.
type VisionCloudServiceCollectionExtensions struct{}

// Wires implements Wiring.
func (VisionCloudServiceCollectionExtensions) Wires() string { return "the cloud image generators" }

// Defaults implements Wiring.
func (VisionCloudServiceCollectionExtensions) Defaults() string { return "nothing configured" }

// TwilioServiceCollectionExtensions states the defaults for the Twilio carrier.
type TwilioServiceCollectionExtensions struct{}

// Wires implements Wiring.
func (TwilioServiceCollectionExtensions) Wires() string { return "the Twilio carrier" }

// Defaults implements Wiring.
func (TwilioServiceCollectionExtensions) Defaults() string { return "absent unless credentials are supplied, so no test can place a real call" }

// TelnyxServiceCollectionExtensions states the defaults for the Telnyx carrier.
type TelnyxServiceCollectionExtensions struct{}

// Wires implements Wiring.
func (TelnyxServiceCollectionExtensions) Wires() string { return "the Telnyx carrier" }

// Defaults implements Wiring.
func (TelnyxServiceCollectionExtensions) Defaults() string { return "absent unless credentials are supplied" }

// PlivoServiceCollectionExtensions states the defaults for the Plivo carrier.
type PlivoServiceCollectionExtensions struct{}

// Wires implements Wiring.
func (PlivoServiceCollectionExtensions) Wires() string { return "the Plivo carrier" }

// Defaults implements Wiring.
func (PlivoServiceCollectionExtensions) Defaults() string { return "absent unless credentials are supplied" }

