"""Pets: animals in the house.

GENERATED by tools/gen_domains.py. The shape is stated once there; what differs
between verticals - the topics, and above all the refusals - lives in the table
rather than in forty hand-copied files.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Sequence


@dataclass(frozen=True)
class PetsDomainContext:
    """What the companion can do about animals in the house on this device."""

    #: What it will speak to.
    topics: tuple[str, ...] = ('feeding', 'vaccinations', 'vets', 'routines')
    #: The one thing it will not do, however it is asked. Held as a pair so the
    #: refusal can be SHOWN with its reason - a refusal without a reason teaches
    #: nobody what the assistant is for.
    refuses: str = 'dose an animal'
    because: str = "weights and doses are the vet's"
    #: Whether a host has wired anything real behind this. False means the
    #: adapter answers from what it knows and says so, rather than pretending.
    is_connected: bool = False

    def describe(self) -> str:
        return (
            "this can help with " + ", ".join(self.topics)
            + f"; it will not {self.refuses} - {self.because}"
        )


class PetsCompanionAdapter:
    """The companion's way into animals in the house.

    THE REFUSAL IS CHECKED BEFORE THE HANDLER RUNS, not after. Producing an
    answer and then deciding it should not have been given has already produced
    it, and on a device that streams, already shown it.
    """

    def __init__(
        self,
        context: "PetsDomainContext | None" = None,
        handle: "Callable[[str], str] | None" = None,
        refuses_when: "Callable[[str], bool] | None" = None,
    ) -> None:
        self._context = context or PetsDomainContext()
        self._handle = handle
        self._refuses_when = refuses_when

    @property
    def context(self) -> PetsDomainContext:
        return self._context

    @property
    def topics(self) -> tuple[str, ...]:
        return self._context.topics

    def refusal_for(self, request: str) -> str:
        """The refusal, or empty when there is none.

        A caller that ignores this gets no protection, which is why the adapter
        itself calls it rather than leaving it to be remembered.
        """
        if self._refuses_when is not None and self._refuses_when(request):
            return f"I will not {self._context.refuses} - {self._context.because}"
        return ""

    def respond(self, request: str) -> tuple[str, bool]:
        """Returns (text, was_refused).

        The flag is separate from the text so a caller can tell a refusal from
        an answer without reading the words - a UI shows them differently, and a
        log counts them differently.
        """
        refusal = self.refusal_for(request)
        if refusal:
            return refusal, True
        if self._handle is None:
            return (
                "this device has nothing wired up for "
                + ", ".join(self._context.topics) + " yet", False)
        return self._handle(request), False


