"""Speech.Cloud: what a host chose to make available.

GENERATED by tools/gen_domains.py. The shape is stated once there; what differs
between verticals - the topics, and above all the refusals - lives in the table
rather than in forty hand-copied files.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Sequence


class SpeechCloudServiceCollectionExtensions:
    """Registers what this module provides.

    A REGISTRATION POINT, not a factory. It records what a host chose to make
    available and returns exactly that - so a component asking what it can use
    gets an answer that reflects a decision somebody made, rather than whatever
    happened to import.
    """

    def __init__(self) -> None:
        self._registered: dict[str, object] = {}

    def add(self, name: str, service: object) -> "SpeechCloudServiceCollectionExtensions":
        """Overwriting is deliberate and last-wins, so a host can replace a
        default without having to remove it first."""
        if not name.strip():
            raise ValueError("a registration needs a name")
        self._registered[name] = service
        return self

    def get(self, name: str) -> "object | None":
        """None when absent, never a stand-in. A caller that gets a silent
        placeholder cannot tell a working service from a missing one."""
        return self._registered.get(name)

    def names(self) -> tuple[str, ...]:
        return tuple(sorted(self._registered))

    def build(self) -> dict[str, object]:
        return dict(self._registered)
