from .companion_types import (
    CompanionContext,
    CompanionProactiveEvent,
    CompanionTurn,
    InterfaceKind,
)
from .face_affect_mapper import apply as apply_face_affect
from .face_companion_bridge import CONFUSION_THRESHOLD, observe
from .belief import (
    Attribution,
    HeuristicBeliefExtractor,
    IBeliefExtractor,
    PersonalBelief,
    SelfBeliefStore,
)
from .memory_encoder import CompanionMemoryEncoder
from .session import (
    CompanionSession,
    CompanionSessionOptions,
    ProactiveMessageHandler,
)
from .session_factory import (
    CompanionSessionFactory,
    ICompanionSessionFactory,
    IIdentityProvider,
    IServiceProvider,
)
from .voice_listener import (
    IVoiceListener,
    IVoicePipeline,
    ResponseReadyEventArgs,
    TranscribedEventArgs,
    TranscriptionResult,
    UtteranceDetectedEventArgs,
    VoiceCompanionListener,
)

# HER/Jarvis companion reasoning core — all 24 contracts + records
from .herjarvis_contracts import (
    AcquiredSkill,
    AgentToAgentMessage,
    AnticipatedNeed,
    BioSignal,
    CausalPrediction,
    CodeGenJob,
    ConfidenceBand,
    DelegationCredential,
    EmotionFrame,
    EpisodeRecord,
    FineTuneJobStatus,
    FirstTokenBudget,
    FusedPercept,
    IAgentPeerNetwork,
    IAlwaysOnPresence,
    IBioSignalStream,
    ICalibratedConfidence,
    ICodeGenerationLoop,
    IContinuousLearner,
    ICryptoDelegation,
    IEmotionSensor,
    IEpisodicMemory,
    IFederatedFineTuner,
    IFirstTokenOptimizer,
    IFusedPerception,
    IGoalPursuer,
    IIdentitySync,
    IInnerMonologue,
    ILiveWorldKnowledge,
    IPersonalKnowledgeGraph,
    IPhysicalActuator,
    IPredictiveEngine,
    ISelfImprovementLoop,
    ISkillAcquisition,
    ITheoryOfMind,
    IVoiceIdentity,
    IWorldModel,
    KnowledgeNode,
    KnowledgeRelation,
    LongHorizonGoal,
    OtherMindEstimate,
    PhysicalCommand,
    PhysicalCommandResult,
    SelfImprovementVerdict,
    SelfReflection,
    WorldFact,
)

# HER/Jarvis reasoning core — implementations
from .world_model import BayesianWorldModel, FrequencyWorldModel
from .predictive_engine import HistogramPredictiveEngine, SequencePredictiveEngine
from .inner_monologue import ReasoningLoopInnerMonologue, TemplateInnerMonologue
from .theory_of_mind import BeliefTrackerTheoryOfMind
from .herjarvis_impl import (
    AdjacencyPersonalKnowledgeGraph,
    ChannelBioSignalStream,
    ChannelFusedPerception,
    DemoStoreSkillAcquisition,
    EnergyBandVoiceIdentity,
    EwaContinuousLearner,
    HeartbeatAlwaysOnPresence,
    HistoricalCalibratedConfidence,
    HmacCryptoDelegation,
    ISignatureProvider,
    InMemoryFederatedFineTuner,
    InMemoryGoalPursuer,
    JsonIdentitySync,
    KeywordEmotionSensor,
    MailboxAgentPeerNetwork,
    RegistryPhysicalActuator,
    SlidingP50FirstTokenOptimizer,
    SyntaxCheckingCodeGenerationLoop,
    TfEpisodicMemory,
    TopicLiveWorldKnowledge,
    TrackingSelfImprovementLoop,
)

# SelfBench-backed self-improvement loop
from .self_bench_loop import (
    AbVerdict,
    BenchSummary,
    IAbBenchRunner,
    IBenchSuiteRegistry,
    RegressionGateConfig,
    SelfBenchSelfImprovementLoop,
)

# Capability registry
from .capability_registry import CapabilityEntry, ExternalCapabilityRegistry

# Proactive briefing service
from .proactive_briefing import (
    CalendarEvent,
    EmailMessage,
    IAIService,
    IBriefingNotifier,
    ICalendarConnector,
    IEmailConnector,
    INewsSource,
    IWeatherProvider,
    NewsItem,
    ProactiveBriefingOptions,
    ProactiveBriefingService,
    WeatherSample,
)

# Proactive scheduling substrate (CircleAI.Companion.Proactive)
from .proactive import (
    CronExpression,
    DelegateProactiveTaskRunner,
    IProactiveScheduler,
    IProactiveTaskRunner,
    IProactiveTaskSource,
    InMemoryProactiveTaskSource,
    NullProactiveTaskRunner,
    NullProactiveTaskSource,
    ProactiveScheduler,
    ProactiveTask,
    ProactiveTaskLoadError,
    ProactiveTaskRunResult,
    ProactiveTrigger,
)

__all__ = [
    "CompanionContext",
    "CompanionProactiveEvent",
    "CompanionTurn",
    "InterfaceKind",
    "CONFUSION_THRESHOLD",
    "apply_face_affect",
    "observe",
    # memory-brain companion layer
    "Attribution",
    "HeuristicBeliefExtractor",
    "IBeliefExtractor",
    "PersonalBelief",
    "SelfBeliefStore",
    "CompanionMemoryEncoder",
    "CompanionSession",
    "CompanionSessionOptions",
    "ProactiveMessageHandler",
    # session factory
    "CompanionSessionFactory",
    "ICompanionSessionFactory",
    "IIdentityProvider",
    "IServiceProvider",
    # voice listener
    "IVoiceListener",
    "IVoicePipeline",
    "ResponseReadyEventArgs",
    "TranscribedEventArgs",
    "TranscriptionResult",
    "UtteranceDetectedEventArgs",
    "VoiceCompanionListener",
    # HER/Jarvis reasoning core — contracts + records
    "AcquiredSkill",
    "AgentToAgentMessage",
    "AnticipatedNeed",
    "BioSignal",
    "CausalPrediction",
    "CodeGenJob",
    "ConfidenceBand",
    "DelegationCredential",
    "EmotionFrame",
    "EpisodeRecord",
    "FineTuneJobStatus",
    "FirstTokenBudget",
    "FusedPercept",
    "IAgentPeerNetwork",
    "IAlwaysOnPresence",
    "IBioSignalStream",
    "ICalibratedConfidence",
    "ICodeGenerationLoop",
    "IContinuousLearner",
    "ICryptoDelegation",
    "IEmotionSensor",
    "IEpisodicMemory",
    "IFederatedFineTuner",
    "IFirstTokenOptimizer",
    "IFusedPerception",
    "IGoalPursuer",
    "IIdentitySync",
    "IInnerMonologue",
    "ILiveWorldKnowledge",
    "IPersonalKnowledgeGraph",
    "IPhysicalActuator",
    "IPredictiveEngine",
    "ISelfImprovementLoop",
    "ISkillAcquisition",
    "ITheoryOfMind",
    "IVoiceIdentity",
    "IWorldModel",
    "KnowledgeNode",
    "KnowledgeRelation",
    "LongHorizonGoal",
    "OtherMindEstimate",
    "PhysicalCommand",
    "PhysicalCommandResult",
    "SelfImprovementVerdict",
    "SelfReflection",
    "WorldFact",
    # HER/Jarvis reasoning core — implementations
    "BayesianWorldModel",
    "FrequencyWorldModel",
    "SequencePredictiveEngine",
    "HistogramPredictiveEngine",
    "ReasoningLoopInnerMonologue",
    "TemplateInnerMonologue",
    "BeliefTrackerTheoryOfMind",
    "AdjacencyPersonalKnowledgeGraph",
    "ChannelBioSignalStream",
    "ChannelFusedPerception",
    "DemoStoreSkillAcquisition",
    "EnergyBandVoiceIdentity",
    "EwaContinuousLearner",
    "HeartbeatAlwaysOnPresence",
    "HistoricalCalibratedConfidence",
    "HmacCryptoDelegation",
    "ISignatureProvider",
    "InMemoryFederatedFineTuner",
    "InMemoryGoalPursuer",
    "JsonIdentitySync",
    "KeywordEmotionSensor",
    "MailboxAgentPeerNetwork",
    "RegistryPhysicalActuator",
    "SlidingP50FirstTokenOptimizer",
    "SyntaxCheckingCodeGenerationLoop",
    "TfEpisodicMemory",
    "TopicLiveWorldKnowledge",
    "TrackingSelfImprovementLoop",
    # SelfBench-backed self-improvement loop
    "AbVerdict",
    "BenchSummary",
    "IAbBenchRunner",
    "IBenchSuiteRegistry",
    "RegressionGateConfig",
    "SelfBenchSelfImprovementLoop",
    # capability registry
    "CapabilityEntry",
    "ExternalCapabilityRegistry",
    # proactive briefing
    "CalendarEvent",
    "EmailMessage",
    "IAIService",
    "IBriefingNotifier",
    "ICalendarConnector",
    "IEmailConnector",
    "INewsSource",
    "IWeatherProvider",
    "NewsItem",
    "ProactiveBriefingOptions",
    "ProactiveBriefingService",
    "WeatherSample",
    # proactive scheduling substrate
    "CronExpression",
    "DelegateProactiveTaskRunner",
    "IProactiveScheduler",
    "IProactiveTaskRunner",
    "IProactiveTaskSource",
    "InMemoryProactiveTaskSource",
    "NullProactiveTaskRunner",
    "NullProactiveTaskSource",
    "ProactiveScheduler",
    "ProactiveTask",
    "ProactiveTaskLoadError",
    "ProactiveTaskRunResult",
    "ProactiveTrigger",
]
