//! threat_vector.rs
//!
//! Classification of locally-detected runtime anomalies.
//!
//! Distinct from any peer-security event kind (which classifies external peer
//! events). `ThreatVector` describes threats observed within the LOCAL process:
//! memory layout deviations, control-flow drift, privilege probes, biometric
//! spoofing attempts, and mesh-level pivoting.
//!
//! Ordinals are STABLE across language ports — match
//! `fixtures/anomaly_signal_schema.json`. Add new values only at the end.

use serde::{Deserialize, Serialize};

/// Classification of a locally-detected runtime threat or anomaly.
///
/// Ordinals are stable across language ports; new values must be appended.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[repr(u8)]
pub enum ThreatVector {
    /// Unexpected change in a runtime data structure's layout or content —
    /// possible memory injection or buffer corruption.
    MemoryAnomaly = 0,

    /// Execution flow deviated from the expected call graph —
    /// possible ROP/JOP chain or code-reuse attack.
    ControlFlowDrift = 1,

    /// A module or user session attempted to acquire capabilities
    /// it is not authorised to hold.
    PrivilegeEscalation = 2,

    /// A biometric authentication attempt was detected as a spoofing or
    /// replay attack against the `UHID` profile.
    BiometricSpoofAttempt = 3,

    /// An attacker appears to be attempting lateral movement from a
    /// compromised mesh node into the local execution namespace.
    NetworkPivot = 4,

    /// The `AffectState` or another core state vector was mutated by an
    /// unexpected code path outside the trusted companion pipeline.
    StateCorruption = 5,

    /// A software patch generated by an agent loop failed the BugHunter
    /// quality gate — possible malicious or incorrect code generation.
    AgentPatchRejected = 6,

    /// Catch-all for anomalies that do not map to a specific vector.
    Unknown = 7,
}
